/* Background.c generated by valac 0.30.0, the Vala compiler
 * generated from Background.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <json-glib/json-glib.h>
#include <json-glib/json-gobject.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>


#define GHERKIN_AST_TYPE_ABSTRACT_NODE (gherkin_ast_abstract_node_get_type ())
#define GHERKIN_AST_ABSTRACT_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNode))
#define GHERKIN_AST_ABSTRACT_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNodeClass))
#define GHERKIN_AST_IS_ABSTRACT_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_ABSTRACT_NODE))
#define GHERKIN_AST_IS_ABSTRACT_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_ABSTRACT_NODE))
#define GHERKIN_AST_ABSTRACT_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNodeClass))

typedef struct _GherkinAstAbstractNode GherkinAstAbstractNode;
typedef struct _GherkinAstAbstractNodeClass GherkinAstAbstractNodeClass;
typedef struct _GherkinAstAbstractNodePrivate GherkinAstAbstractNodePrivate;

#define GHERKIN_AST_TYPE_BACKGROUND (gherkin_ast_background_get_type ())
#define GHERKIN_AST_BACKGROUND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_BACKGROUND, GherkinAstBackground))
#define GHERKIN_AST_BACKGROUND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_BACKGROUND, GherkinAstBackgroundClass))
#define GHERKIN_AST_IS_BACKGROUND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_BACKGROUND))
#define GHERKIN_AST_IS_BACKGROUND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_BACKGROUND))
#define GHERKIN_AST_BACKGROUND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_BACKGROUND, GherkinAstBackgroundClass))

typedef struct _GherkinAstBackground GherkinAstBackground;
typedef struct _GherkinAstBackgroundClass GherkinAstBackgroundClass;
typedef struct _GherkinAstBackgroundPrivate GherkinAstBackgroundPrivate;

#define GHERKIN_AST_TYPE_STEP (gherkin_ast_step_get_type ())
#define GHERKIN_AST_STEP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_STEP, GherkinAstStep))
#define GHERKIN_AST_STEP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_STEP, GherkinAstStepClass))
#define GHERKIN_AST_IS_STEP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_STEP))
#define GHERKIN_AST_IS_STEP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_STEP))
#define GHERKIN_AST_STEP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_STEP, GherkinAstStepClass))

typedef struct _GherkinAstStep GherkinAstStep;
typedef struct _GherkinAstStepClass GherkinAstStepClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define GHERKIN_AST_TYPE_LOCATION (gherkin_ast_location_get_type ())
#define GHERKIN_AST_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocation))
#define GHERKIN_AST_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocationClass))
#define GHERKIN_AST_IS_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_LOCATION))
#define GHERKIN_AST_IS_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_LOCATION))
#define GHERKIN_AST_LOCATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocationClass))

typedef struct _GherkinAstLocation GherkinAstLocation;
typedef struct _GherkinAstLocationClass GherkinAstLocationClass;
#define _json_array_unref0(var) ((var == NULL) ? NULL : (var = (json_array_unref (var), NULL)))
#define __vala_JsonNode_free0(var) ((var == NULL) ? NULL : (var = (_vala_JsonNode_free (var), NULL)))
typedef struct _Block23Data Block23Data;

struct _GherkinAstAbstractNode {
	GObject parent_instance;
	GherkinAstAbstractNodePrivate * priv;
};

struct _GherkinAstAbstractNodeClass {
	GObjectClass parent_class;
	JsonNode* (*serialize_property) (GherkinAstAbstractNode* self, const gchar* property_name, GValue* value, GParamSpec* pspec);
	gboolean (*deserialize_property) (GherkinAstAbstractNode* self, const gchar* property_name, GValue* value, GParamSpec* pspec, JsonNode* property_node);
};

struct _GherkinAstBackground {
	GherkinAstAbstractNode parent_instance;
	GherkinAstBackgroundPrivate * priv;
};

struct _GherkinAstBackgroundClass {
	GherkinAstAbstractNodeClass parent_class;
};

struct _GherkinAstBackgroundPrivate {
	gchar* _keyword;
	gchar* _name;
	gchar* _description;
	GeeArrayList* _steps;
};

struct _Block23Data {
	int _ref_count_;
	GherkinAstBackground* self;
	GeeArrayList* stepvar;
};


static gpointer gherkin_ast_background_parent_class = NULL;

GType gherkin_ast_abstract_node_get_type (void) G_GNUC_CONST;
GType gherkin_ast_background_get_type (void) G_GNUC_CONST;
GType gherkin_ast_step_get_type (void) G_GNUC_CONST;
#define GHERKIN_AST_BACKGROUND_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GHERKIN_AST_TYPE_BACKGROUND, GherkinAstBackgroundPrivate))
enum  {
	GHERKIN_AST_BACKGROUND_DUMMY_PROPERTY,
	GHERKIN_AST_BACKGROUND_KEYWORD,
	GHERKIN_AST_BACKGROUND_NAME,
	GHERKIN_AST_BACKGROUND_DESCRIPTION,
	GHERKIN_AST_BACKGROUND_STEPS
};
GType gherkin_ast_location_get_type (void) G_GNUC_CONST;
GherkinAstBackground* gherkin_ast_background_new (GherkinAstLocation* location, const gchar* keyword, const gchar* name, const gchar* description, GeeArrayList* steps);
GherkinAstBackground* gherkin_ast_background_construct (GType object_type, GherkinAstLocation* location, const gchar* keyword, const gchar* name, const gchar* description, GeeArrayList* steps);
GherkinAstAbstractNode* gherkin_ast_abstract_node_construct (GType object_type, GherkinAstLocation* location);
void gherkin_ast_background_set_keyword (GherkinAstBackground* self, const gchar* value);
void gherkin_ast_background_set_name (GherkinAstBackground* self, const gchar* value);
void gherkin_ast_background_set_description (GherkinAstBackground* self, const gchar* value);
void gherkin_ast_background_set_steps (GherkinAstBackground* self, GeeArrayList* value);
static JsonNode* gherkin_ast_background_real_serialize_property (GherkinAstAbstractNode* base, const gchar* property_name, GValue* value, GParamSpec* pspec);
GeeArrayList* gherkin_ast_background_get_steps (GherkinAstBackground* self);
static void _vala_JsonNode_free (JsonNode* self);
JsonNode* gherkin_ast_abstract_node_serialize_property (GherkinAstAbstractNode* self, const gchar* property_name, GValue* value, GParamSpec* pspec);
static gboolean gherkin_ast_background_real_deserialize_property (GherkinAstAbstractNode* base, const gchar* property_name, GValue* value, GParamSpec* pspec, JsonNode* property_node);
static Block23Data* block23_data_ref (Block23Data* _data23_);
static void block23_data_unref (void * _userdata_);
static void ___lambda27_ (Block23Data* _data23_, JsonArray* a, guint i, JsonNode* n);
static void ____lambda27__json_array_foreach (JsonArray* array, guint index_, JsonNode* element_node, gpointer self);
gboolean gherkin_ast_abstract_node_deserialize_property (GherkinAstAbstractNode* self, const gchar* property_name, GValue* value, GParamSpec* pspec, JsonNode* property_node);
const gchar* gherkin_ast_background_get_keyword (GherkinAstBackground* self);
const gchar* gherkin_ast_background_get_name (GherkinAstBackground* self);
const gchar* gherkin_ast_background_get_description (GherkinAstBackground* self);
static void gherkin_ast_background_finalize (GObject* obj);
static void _vala_gherkin_ast_background_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_gherkin_ast_background_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


GherkinAstBackground* gherkin_ast_background_construct (GType object_type, GherkinAstLocation* location, const gchar* keyword, const gchar* name, const gchar* description, GeeArrayList* steps) {
	GherkinAstBackground * self = NULL;
	GherkinAstLocation* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	GeeArrayList* _tmp4_ = NULL;
#line 11 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_return_val_if_fail (location != NULL, NULL);
#line 11 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_return_val_if_fail (keyword != NULL, NULL);
#line 11 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 11 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_return_val_if_fail (steps != NULL, NULL);
#line 12 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp0_ = location;
#line 12 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	self = (GherkinAstBackground*) gherkin_ast_abstract_node_construct (object_type, _tmp0_);
#line 13 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp1_ = keyword;
#line 13 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	gherkin_ast_background_set_keyword (self, _tmp1_);
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp2_ = name;
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	gherkin_ast_background_set_name (self, _tmp2_);
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp3_ = description;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	gherkin_ast_background_set_description (self, _tmp3_);
#line 16 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp4_ = steps;
#line 16 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	gherkin_ast_background_set_steps (self, _tmp4_);
#line 11 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	return self;
#line 172 "Background.c"
}


GherkinAstBackground* gherkin_ast_background_new (GherkinAstLocation* location, const gchar* keyword, const gchar* name, const gchar* description, GeeArrayList* steps) {
#line 11 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	return gherkin_ast_background_construct (GHERKIN_AST_TYPE_BACKGROUND, location, keyword, name, description, steps);
#line 179 "Background.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	return self ? g_object_ref (self) : NULL;
#line 186 "Background.c"
}


static void _vala_JsonNode_free (JsonNode* self) {
#line 20 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_boxed_free (json_node_get_type (), self);
#line 193 "Background.c"
}


static JsonNode* gherkin_ast_background_real_serialize_property (GherkinAstAbstractNode* base, const gchar* property_name, GValue* value, GParamSpec* pspec) {
	GherkinAstBackground * self;
	JsonNode* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp19_ = NULL;
	GValue _tmp20_ = {0};
	GParamSpec* _tmp21_ = NULL;
	JsonNode* _tmp22_ = NULL;
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	self = (GherkinAstBackground*) base;
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_return_val_if_fail (property_name != NULL, NULL);
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_return_val_if_fail (value != NULL, NULL);
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_return_val_if_fail (pspec != NULL, NULL);
#line 20 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp0_ = property_name;
#line 20 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	if (g_strcmp0 (_tmp0_, "steps") == 0) {
#line 217 "Background.c"
		JsonNode* node = NULL;
		JsonNode* _tmp1_ = NULL;
		JsonArray* array = NULL;
		JsonArray* _tmp2_ = NULL;
		JsonNode* _tmp17_ = NULL;
		JsonArray* _tmp18_ = NULL;
#line 21 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		_tmp1_ = json_node_new (JSON_NODE_ARRAY);
#line 21 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		node = _tmp1_;
#line 22 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		_tmp2_ = json_array_new ();
#line 22 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		array = _tmp2_;
#line 232 "Background.c"
		{
			GeeArrayList* _step_list = NULL;
			GeeArrayList* _tmp3_ = NULL;
			GeeArrayList* _tmp4_ = NULL;
			gint _step_size = 0;
			GeeArrayList* _tmp5_ = NULL;
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			gint _step_index = 0;
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
			_tmp3_ = self->priv->_steps;
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
			_tmp4_ = _g_object_ref0 (_tmp3_);
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
			_step_list = _tmp4_;
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
			_tmp5_ = _step_list;
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
			_tmp6_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp5_);
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
			_tmp7_ = _tmp6_;
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
			_step_size = _tmp7_;
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
			_step_index = -1;
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
			while (TRUE) {
#line 260 "Background.c"
				gint _tmp8_ = 0;
				gint _tmp9_ = 0;
				gint _tmp10_ = 0;
				GherkinAstStep* step = NULL;
				GeeArrayList* _tmp11_ = NULL;
				gint _tmp12_ = 0;
				gpointer _tmp13_ = NULL;
				JsonArray* _tmp14_ = NULL;
				GherkinAstStep* _tmp15_ = NULL;
				JsonNode* _tmp16_ = NULL;
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
				_tmp8_ = _step_index;
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
				_step_index = _tmp8_ + 1;
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
				_tmp9_ = _step_index;
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
				_tmp10_ = _step_size;
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
				if (!(_tmp9_ < _tmp10_)) {
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
					break;
#line 283 "Background.c"
				}
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
				_tmp11_ = _step_list;
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
				_tmp12_ = _step_index;
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
				_tmp13_ = gee_abstract_list_get ((GeeAbstractList*) _tmp11_, _tmp12_);
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
				step = (GherkinAstStep*) _tmp13_;
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
				_tmp14_ = array;
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
				_tmp15_ = step;
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
				_tmp16_ = json_gobject_serialize ((GObject*) _tmp15_);
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
				json_array_add_element (_tmp14_, _tmp16_);
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
				_g_object_unref0 (step);
#line 303 "Background.c"
			}
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
			_g_object_unref0 (_step_list);
#line 307 "Background.c"
		}
#line 25 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		_tmp17_ = node;
#line 25 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		_tmp18_ = array;
#line 25 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		json_node_init_array (_tmp17_, _tmp18_);
#line 26 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		result = node;
#line 26 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		_json_array_unref0 (array);
#line 26 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		return result;
#line 321 "Background.c"
	}
#line 28 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp19_ = property_name;
#line 28 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp20_ = *value;
#line 28 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp21_ = pspec;
#line 28 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp22_ = GHERKIN_AST_ABSTRACT_NODE_CLASS (gherkin_ast_background_parent_class)->serialize_property (G_TYPE_CHECK_INSTANCE_CAST (self, GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNode), _tmp19_, &_tmp20_, _tmp21_);
#line 28 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	result = _tmp22_;
#line 28 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	return result;
#line 335 "Background.c"
}


static Block23Data* block23_data_ref (Block23Data* _data23_) {
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_atomic_int_inc (&_data23_->_ref_count_);
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	return _data23_;
#line 344 "Background.c"
}


static void block23_data_unref (void * _userdata_) {
	Block23Data* _data23_;
	_data23_ = (Block23Data*) _userdata_;
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	if (g_atomic_int_dec_and_test (&_data23_->_ref_count_)) {
#line 353 "Background.c"
		GherkinAstBackground* self;
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		self = _data23_->self;
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		_g_object_unref0 (_data23_->stepvar);
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		_g_object_unref0 (self);
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		g_slice_free (Block23Data, _data23_);
#line 363 "Background.c"
	}
}


static gpointer _json_array_ref0 (gpointer self) {
#line 35 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	return self ? json_array_ref (self) : NULL;
#line 371 "Background.c"
}


static void ___lambda27_ (Block23Data* _data23_, JsonArray* a, guint i, JsonNode* n) {
	GherkinAstBackground* self;
	GeeArrayList* _tmp0_ = NULL;
	JsonNode* _tmp1_ = NULL;
	GObject* _tmp2_ = NULL;
	GherkinAstStep* _tmp3_ = NULL;
	GherkinAstStep* _tmp4_ = NULL;
#line 36 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	self = _data23_->self;
#line 36 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_return_if_fail (a != NULL);
#line 36 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_return_if_fail (n != NULL);
#line 37 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp0_ = _data23_->stepvar;
#line 37 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp1_ = n;
#line 37 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp2_ = json_gobject_deserialize (GHERKIN_AST_TYPE_STEP, _tmp1_);
#line 37 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp3_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp2_, GHERKIN_AST_TYPE_STEP) ? ((GherkinAstStep*) _tmp2_) : NULL;
#line 37 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	if (_tmp3_ == NULL) {
#line 37 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		_g_object_unref0 (_tmp2_);
#line 400 "Background.c"
	}
#line 37 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp4_ = _tmp3_;
#line 37 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp0_, _tmp4_);
#line 37 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_g_object_unref0 (_tmp4_);
#line 408 "Background.c"
}


static void ____lambda27__json_array_foreach (JsonArray* array, guint index_, JsonNode* element_node, gpointer self) {
#line 36 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	___lambda27_ (self, array, index_, element_node);
#line 415 "Background.c"
}


static gboolean gherkin_ast_background_real_deserialize_property (GherkinAstAbstractNode* base, const gchar* property_name, GValue* value, GParamSpec* pspec, JsonNode* property_node) {
	GherkinAstBackground * self;
	GValue _vala_value = {0};
	gboolean result = FALSE;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp7_ = NULL;
	GParamSpec* _tmp8_ = NULL;
	JsonNode* _tmp9_ = NULL;
	GValue _tmp10_ = {0};
	gboolean _tmp11_ = FALSE;
#line 31 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	self = (GherkinAstBackground*) base;
#line 31 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_return_val_if_fail (property_name != NULL, FALSE);
#line 31 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_return_val_if_fail (pspec != NULL, FALSE);
#line 31 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_return_val_if_fail (property_node != NULL, FALSE);
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp0_ = property_name;
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	if (g_strcmp0 (_tmp0_, "steps") == 0) {
#line 441 "Background.c"
		Block23Data* _data23_;
		GeeArrayList* _tmp1_ = NULL;
		JsonArray* array = NULL;
		JsonNode* _tmp2_ = NULL;
		JsonArray* _tmp3_ = NULL;
		JsonArray* _tmp4_ = NULL;
		JsonArray* _tmp5_ = NULL;
		GeeArrayList* _tmp6_ = NULL;
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		_data23_ = g_slice_new0 (Block23Data);
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		_data23_->_ref_count_ = 1;
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		_data23_->self = g_object_ref (self);
#line 34 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		_tmp1_ = gee_array_list_new (GHERKIN_AST_TYPE_STEP, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
#line 34 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		_data23_->stepvar = _tmp1_;
#line 35 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		_tmp2_ = property_node;
#line 35 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		_tmp3_ = json_node_get_array (_tmp2_);
#line 35 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		_tmp4_ = _json_array_ref0 (_tmp3_);
#line 35 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		array = _tmp4_;
#line 36 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		_tmp5_ = array;
#line 36 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		json_array_foreach_element (_tmp5_, ____lambda27__json_array_foreach, _data23_);
#line 39 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		_tmp6_ = _data23_->stepvar;
#line 39 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		g_value_init_from_instance (&_vala_value, _tmp6_);
#line 40 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		result = TRUE;
#line 40 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		_json_array_unref0 (array);
#line 40 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		block23_data_unref (_data23_);
#line 40 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		_data23_ = NULL;
#line 40 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		if (value) {
#line 40 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
			*value = _vala_value;
#line 488 "Background.c"
		} else {
#line 40 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
			G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
#line 492 "Background.c"
		}
#line 40 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		return result;
#line 496 "Background.c"
	}
#line 43 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp7_ = property_name;
#line 43 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp8_ = pspec;
#line 43 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp9_ = property_node;
#line 43 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp11_ = GHERKIN_AST_ABSTRACT_NODE_CLASS (gherkin_ast_background_parent_class)->deserialize_property (G_TYPE_CHECK_INSTANCE_CAST (self, GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNode), _tmp7_, &_tmp10_, _tmp8_, _tmp9_);
#line 43 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
#line 43 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_vala_value = _tmp10_;
#line 43 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	result = _tmp11_;
#line 43 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	if (value) {
#line 43 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		*value = _vala_value;
#line 516 "Background.c"
	} else {
#line 43 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
#line 520 "Background.c"
	}
#line 43 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	return result;
#line 524 "Background.c"
}


const gchar* gherkin_ast_background_get_keyword (GherkinAstBackground* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp0_ = self->priv->_keyword;
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	result = _tmp0_;
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	return result;
#line 539 "Background.c"
}


void gherkin_ast_background_set_keyword (GherkinAstBackground* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_return_if_fail (self != NULL);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp0_ = value;
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_g_free0 (self->priv->_keyword);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	self->priv->_keyword = _tmp1_;
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_object_notify ((GObject *) self, "keyword");
#line 558 "Background.c"
}


const gchar* gherkin_ast_background_get_name (GherkinAstBackground* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp0_ = self->priv->_name;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	result = _tmp0_;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	return result;
#line 573 "Background.c"
}


void gherkin_ast_background_set_name (GherkinAstBackground* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_return_if_fail (self != NULL);
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp0_ = value;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_g_free0 (self->priv->_name);
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	self->priv->_name = _tmp1_;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_object_notify ((GObject *) self, "name");
#line 592 "Background.c"
}


const gchar* gherkin_ast_background_get_description (GherkinAstBackground* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp0_ = self->priv->_description;
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	result = _tmp0_;
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	return result;
#line 607 "Background.c"
}


void gherkin_ast_background_set_description (GherkinAstBackground* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_return_if_fail (self != NULL);
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp0_ = value;
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_g_free0 (self->priv->_description);
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	self->priv->_description = _tmp1_;
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_object_notify ((GObject *) self, "description");
#line 626 "Background.c"
}


GeeArrayList* gherkin_ast_background_get_steps (GherkinAstBackground* self) {
	GeeArrayList* result;
	GeeArrayList* _tmp0_ = NULL;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp0_ = self->priv->_steps;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	result = _tmp0_;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	return result;
#line 641 "Background.c"
}


void gherkin_ast_background_set_steps (GherkinAstBackground* self, GeeArrayList* value) {
	GeeArrayList* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_return_if_fail (self != NULL);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp0_ = value;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_g_object_unref0 (self->priv->_steps);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	self->priv->_steps = _tmp1_;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_object_notify ((GObject *) self, "steps");
#line 660 "Background.c"
}


static void gherkin_ast_background_class_init (GherkinAstBackgroundClass * klass) {
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	gherkin_ast_background_parent_class = g_type_class_peek_parent (klass);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_type_class_add_private (klass, sizeof (GherkinAstBackgroundPrivate));
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	((GherkinAstAbstractNodeClass *) klass)->serialize_property = gherkin_ast_background_real_serialize_property;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	((GherkinAstAbstractNodeClass *) klass)->deserialize_property = gherkin_ast_background_real_deserialize_property;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_gherkin_ast_background_get_property;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_gherkin_ast_background_set_property;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	G_OBJECT_CLASS (klass)->finalize = gherkin_ast_background_finalize;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), GHERKIN_AST_BACKGROUND_KEYWORD, g_param_spec_string ("keyword", "keyword", "keyword", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), GHERKIN_AST_BACKGROUND_NAME, g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), GHERKIN_AST_BACKGROUND_DESCRIPTION, g_param_spec_string ("description", "description", "description", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), GHERKIN_AST_BACKGROUND_STEPS, g_param_spec_object ("steps", "steps", "steps", GEE_TYPE_ARRAY_LIST, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 687 "Background.c"
}


static void gherkin_ast_background_instance_init (GherkinAstBackground * self) {
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	self->priv = GHERKIN_AST_BACKGROUND_GET_PRIVATE (self);
#line 694 "Background.c"
}


static void gherkin_ast_background_finalize (GObject* obj) {
	GherkinAstBackground * self;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GHERKIN_AST_TYPE_BACKGROUND, GherkinAstBackground);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_g_free0 (self->priv->_keyword);
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_g_free0 (self->priv->_name);
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_g_free0 (self->priv->_description);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	_g_object_unref0 (self->priv->_steps);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	G_OBJECT_CLASS (gherkin_ast_background_parent_class)->finalize (obj);
#line 712 "Background.c"
}


GType gherkin_ast_background_get_type (void) {
	static volatile gsize gherkin_ast_background_type_id__volatile = 0;
	if (g_once_init_enter (&gherkin_ast_background_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GherkinAstBackgroundClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gherkin_ast_background_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GherkinAstBackground), 0, (GInstanceInitFunc) gherkin_ast_background_instance_init, NULL };
		GType gherkin_ast_background_type_id;
		gherkin_ast_background_type_id = g_type_register_static (GHERKIN_AST_TYPE_ABSTRACT_NODE, "GherkinAstBackground", &g_define_type_info, 0);
		g_once_init_leave (&gherkin_ast_background_type_id__volatile, gherkin_ast_background_type_id);
	}
	return gherkin_ast_background_type_id__volatile;
}


static void _vala_gherkin_ast_background_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GherkinAstBackground * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GHERKIN_AST_TYPE_BACKGROUND, GherkinAstBackground);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	switch (property_id) {
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		case GHERKIN_AST_BACKGROUND_KEYWORD:
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		g_value_set_string (value, gherkin_ast_background_get_keyword (self));
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		break;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		case GHERKIN_AST_BACKGROUND_NAME:
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		g_value_set_string (value, gherkin_ast_background_get_name (self));
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		break;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		case GHERKIN_AST_BACKGROUND_DESCRIPTION:
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		g_value_set_string (value, gherkin_ast_background_get_description (self));
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		break;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		case GHERKIN_AST_BACKGROUND_STEPS:
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		g_value_set_object (value, gherkin_ast_background_get_steps (self));
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		break;
#line 757 "Background.c"
		default:
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		break;
#line 763 "Background.c"
	}
}


static void _vala_gherkin_ast_background_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GherkinAstBackground * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GHERKIN_AST_TYPE_BACKGROUND, GherkinAstBackground);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
	switch (property_id) {
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		case GHERKIN_AST_BACKGROUND_KEYWORD:
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		gherkin_ast_background_set_keyword (self, g_value_get_string (value));
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		break;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		case GHERKIN_AST_BACKGROUND_NAME:
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		gherkin_ast_background_set_name (self, g_value_get_string (value));
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		break;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		case GHERKIN_AST_BACKGROUND_DESCRIPTION:
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		gherkin_ast_background_set_description (self, g_value_get_string (value));
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		break;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		case GHERKIN_AST_BACKGROUND_STEPS:
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		gherkin_ast_background_set_steps (self, g_value_get_object (value));
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		break;
#line 797 "Background.c"
		default:
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Background.vala"
		break;
#line 803 "Background.c"
	}
}



