/* Comment.c generated by valac 0.30.0, the Vala compiler
 * generated from Comment.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <json-glib/json-glib.h>
#include <json-glib/json-gobject.h>
#include <stdlib.h>
#include <string.h>


#define GHERKIN_AST_TYPE_ABSTRACT_NODE (gherkin_ast_abstract_node_get_type ())
#define GHERKIN_AST_ABSTRACT_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNode))
#define GHERKIN_AST_ABSTRACT_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNodeClass))
#define GHERKIN_AST_IS_ABSTRACT_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_ABSTRACT_NODE))
#define GHERKIN_AST_IS_ABSTRACT_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_ABSTRACT_NODE))
#define GHERKIN_AST_ABSTRACT_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNodeClass))

typedef struct _GherkinAstAbstractNode GherkinAstAbstractNode;
typedef struct _GherkinAstAbstractNodeClass GherkinAstAbstractNodeClass;
typedef struct _GherkinAstAbstractNodePrivate GherkinAstAbstractNodePrivate;

#define GHERKIN_AST_TYPE_COMMENT (gherkin_ast_comment_get_type ())
#define GHERKIN_AST_COMMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_COMMENT, GherkinAstComment))
#define GHERKIN_AST_COMMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_COMMENT, GherkinAstCommentClass))
#define GHERKIN_AST_IS_COMMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_COMMENT))
#define GHERKIN_AST_IS_COMMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_COMMENT))
#define GHERKIN_AST_COMMENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_COMMENT, GherkinAstCommentClass))

typedef struct _GherkinAstComment GherkinAstComment;
typedef struct _GherkinAstCommentClass GherkinAstCommentClass;
typedef struct _GherkinAstCommentPrivate GherkinAstCommentPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

#define GHERKIN_AST_TYPE_LOCATION (gherkin_ast_location_get_type ())
#define GHERKIN_AST_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocation))
#define GHERKIN_AST_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocationClass))
#define GHERKIN_AST_IS_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_LOCATION))
#define GHERKIN_AST_IS_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_LOCATION))
#define GHERKIN_AST_LOCATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocationClass))

typedef struct _GherkinAstLocation GherkinAstLocation;
typedef struct _GherkinAstLocationClass GherkinAstLocationClass;

struct _GherkinAstAbstractNode {
	GObject parent_instance;
	GherkinAstAbstractNodePrivate * priv;
};

struct _GherkinAstAbstractNodeClass {
	GObjectClass parent_class;
	JsonNode* (*serialize_property) (GherkinAstAbstractNode* self, const gchar* property_name, GValue* value, GParamSpec* pspec);
	gboolean (*deserialize_property) (GherkinAstAbstractNode* self, const gchar* property_name, GValue* value, GParamSpec* pspec, JsonNode* property_node);
};

struct _GherkinAstComment {
	GherkinAstAbstractNode parent_instance;
	GherkinAstCommentPrivate * priv;
};

struct _GherkinAstCommentClass {
	GherkinAstAbstractNodeClass parent_class;
};

struct _GherkinAstCommentPrivate {
	gchar* _text;
};


static gpointer gherkin_ast_comment_parent_class = NULL;

GType gherkin_ast_abstract_node_get_type (void) G_GNUC_CONST;
GType gherkin_ast_comment_get_type (void) G_GNUC_CONST;
#define GHERKIN_AST_COMMENT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GHERKIN_AST_TYPE_COMMENT, GherkinAstCommentPrivate))
enum  {
	GHERKIN_AST_COMMENT_DUMMY_PROPERTY
};
GType gherkin_ast_location_get_type (void) G_GNUC_CONST;
GherkinAstComment* gherkin_ast_comment_new (GherkinAstLocation* location, const gchar* text);
GherkinAstComment* gherkin_ast_comment_construct (GType object_type, GherkinAstLocation* location, const gchar* text);
GherkinAstAbstractNode* gherkin_ast_abstract_node_construct (GType object_type, GherkinAstLocation* location);
static void gherkin_ast_comment_set_text (GherkinAstComment* self, const gchar* value);
static const gchar* gherkin_ast_comment_get_text (GherkinAstComment* self);
static void gherkin_ast_comment_finalize (GObject* obj);
static void _vala_gherkin_ast_comment_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_gherkin_ast_comment_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


GherkinAstComment* gherkin_ast_comment_construct (GType object_type, GherkinAstLocation* location, const gchar* text) {
	GherkinAstComment * self = NULL;
	GherkinAstLocation* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	g_return_val_if_fail (location != NULL, NULL);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	g_return_val_if_fail (text != NULL, NULL);
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	_tmp0_ = location;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	self = (GherkinAstComment*) gherkin_ast_abstract_node_construct (object_type, _tmp0_);
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	_tmp1_ = text;
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	gherkin_ast_comment_set_text (self, _tmp1_);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	return self;
#line 109 "Comment.c"
}


GherkinAstComment* gherkin_ast_comment_new (GherkinAstLocation* location, const gchar* text) {
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	return gherkin_ast_comment_construct (GHERKIN_AST_TYPE_COMMENT, location, text);
#line 116 "Comment.c"
}


static const gchar* gherkin_ast_comment_get_text (GherkinAstComment* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	_tmp0_ = self->priv->_text;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	result = _tmp0_;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	return result;
#line 131 "Comment.c"
}


static void gherkin_ast_comment_set_text (GherkinAstComment* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	g_return_if_fail (self != NULL);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	_tmp0_ = value;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	_g_free0 (self->priv->_text);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	self->priv->_text = _tmp1_;
#line 148 "Comment.c"
}


static void gherkin_ast_comment_class_init (GherkinAstCommentClass * klass) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	gherkin_ast_comment_parent_class = g_type_class_peek_parent (klass);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	g_type_class_add_private (klass, sizeof (GherkinAstCommentPrivate));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_gherkin_ast_comment_get_property;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_gherkin_ast_comment_set_property;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	G_OBJECT_CLASS (klass)->finalize = gherkin_ast_comment_finalize;
#line 163 "Comment.c"
}


static void gherkin_ast_comment_instance_init (GherkinAstComment * self) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	self->priv = GHERKIN_AST_COMMENT_GET_PRIVATE (self);
#line 170 "Comment.c"
}


static void gherkin_ast_comment_finalize (GObject* obj) {
	GherkinAstComment * self;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GHERKIN_AST_TYPE_COMMENT, GherkinAstComment);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	_g_free0 (self->priv->_text);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	G_OBJECT_CLASS (gherkin_ast_comment_parent_class)->finalize (obj);
#line 182 "Comment.c"
}


GType gherkin_ast_comment_get_type (void) {
	static volatile gsize gherkin_ast_comment_type_id__volatile = 0;
	if (g_once_init_enter (&gherkin_ast_comment_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GherkinAstCommentClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gherkin_ast_comment_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GherkinAstComment), 0, (GInstanceInitFunc) gherkin_ast_comment_instance_init, NULL };
		GType gherkin_ast_comment_type_id;
		gherkin_ast_comment_type_id = g_type_register_static (GHERKIN_AST_TYPE_ABSTRACT_NODE, "GherkinAstComment", &g_define_type_info, 0);
		g_once_init_leave (&gherkin_ast_comment_type_id__volatile, gherkin_ast_comment_type_id);
	}
	return gherkin_ast_comment_type_id__volatile;
}


static void _vala_gherkin_ast_comment_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GherkinAstComment * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GHERKIN_AST_TYPE_COMMENT, GherkinAstComment);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	switch (property_id) {
#line 203 "Comment.c"
		default:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
		break;
#line 209 "Comment.c"
	}
}


static void _vala_gherkin_ast_comment_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GherkinAstComment * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GHERKIN_AST_TYPE_COMMENT, GherkinAstComment);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
	switch (property_id) {
#line 219 "Comment.c"
		default:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Comment.vala"
		break;
#line 225 "Comment.c"
	}
}



