/* DocString.c generated by valac 0.30.0, the Vala compiler
 * generated from DocString.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <json-glib/json-glib.h>
#include <json-glib/json-gobject.h>
#include <stdlib.h>
#include <string.h>


#define GHERKIN_AST_TYPE_ABSTRACT_NODE (gherkin_ast_abstract_node_get_type ())
#define GHERKIN_AST_ABSTRACT_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNode))
#define GHERKIN_AST_ABSTRACT_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNodeClass))
#define GHERKIN_AST_IS_ABSTRACT_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_ABSTRACT_NODE))
#define GHERKIN_AST_IS_ABSTRACT_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_ABSTRACT_NODE))
#define GHERKIN_AST_ABSTRACT_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNodeClass))

typedef struct _GherkinAstAbstractNode GherkinAstAbstractNode;
typedef struct _GherkinAstAbstractNodeClass GherkinAstAbstractNodeClass;
typedef struct _GherkinAstAbstractNodePrivate GherkinAstAbstractNodePrivate;

#define GHERKIN_AST_TYPE_DOC_STRING (gherkin_ast_doc_string_get_type ())
#define GHERKIN_AST_DOC_STRING(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_DOC_STRING, GherkinAstDocString))
#define GHERKIN_AST_DOC_STRING_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_DOC_STRING, GherkinAstDocStringClass))
#define GHERKIN_AST_IS_DOC_STRING(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_DOC_STRING))
#define GHERKIN_AST_IS_DOC_STRING_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_DOC_STRING))
#define GHERKIN_AST_DOC_STRING_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_DOC_STRING, GherkinAstDocStringClass))

typedef struct _GherkinAstDocString GherkinAstDocString;
typedef struct _GherkinAstDocStringClass GherkinAstDocStringClass;
typedef struct _GherkinAstDocStringPrivate GherkinAstDocStringPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

#define GHERKIN_AST_TYPE_LOCATION (gherkin_ast_location_get_type ())
#define GHERKIN_AST_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocation))
#define GHERKIN_AST_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocationClass))
#define GHERKIN_AST_IS_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_LOCATION))
#define GHERKIN_AST_IS_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_LOCATION))
#define GHERKIN_AST_LOCATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocationClass))

typedef struct _GherkinAstLocation GherkinAstLocation;
typedef struct _GherkinAstLocationClass GherkinAstLocationClass;

struct _GherkinAstAbstractNode {
	GObject parent_instance;
	GherkinAstAbstractNodePrivate * priv;
};

struct _GherkinAstAbstractNodeClass {
	GObjectClass parent_class;
	JsonNode* (*serialize_property) (GherkinAstAbstractNode* self, const gchar* property_name, GValue* value, GParamSpec* pspec);
	gboolean (*deserialize_property) (GherkinAstAbstractNode* self, const gchar* property_name, GValue* value, GParamSpec* pspec, JsonNode* property_node);
};

struct _GherkinAstDocString {
	GherkinAstAbstractNode parent_instance;
	GherkinAstDocStringPrivate * priv;
};

struct _GherkinAstDocStringClass {
	GherkinAstAbstractNodeClass parent_class;
};

struct _GherkinAstDocStringPrivate {
	gchar* _contentType;
	gchar* _content;
};


static gpointer gherkin_ast_doc_string_parent_class = NULL;

GType gherkin_ast_abstract_node_get_type (void) G_GNUC_CONST;
GType gherkin_ast_doc_string_get_type (void) G_GNUC_CONST;
#define GHERKIN_AST_DOC_STRING_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GHERKIN_AST_TYPE_DOC_STRING, GherkinAstDocStringPrivate))
enum  {
	GHERKIN_AST_DOC_STRING_DUMMY_PROPERTY,
	GHERKIN_AST_DOC_STRING_CONTENT_TYPE,
	GHERKIN_AST_DOC_STRING_CONTENT
};
GType gherkin_ast_location_get_type (void) G_GNUC_CONST;
GherkinAstDocString* gherkin_ast_doc_string_new (GherkinAstLocation* location, const gchar* contentType, const gchar* content);
GherkinAstDocString* gherkin_ast_doc_string_construct (GType object_type, GherkinAstLocation* location, const gchar* contentType, const gchar* content);
GherkinAstAbstractNode* gherkin_ast_abstract_node_construct (GType object_type, GherkinAstLocation* location);
void gherkin_ast_doc_string_set_contentType (GherkinAstDocString* self, const gchar* value);
void gherkin_ast_doc_string_set_content (GherkinAstDocString* self, const gchar* value);
const gchar* gherkin_ast_doc_string_get_contentType (GherkinAstDocString* self);
const gchar* gherkin_ast_doc_string_get_content (GherkinAstDocString* self);
static void gherkin_ast_doc_string_finalize (GObject* obj);
static void _vala_gherkin_ast_doc_string_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_gherkin_ast_doc_string_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


GherkinAstDocString* gherkin_ast_doc_string_construct (GType object_type, GherkinAstLocation* location, const gchar* contentType, const gchar* content) {
	GherkinAstDocString * self = NULL;
	GherkinAstLocation* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	g_return_val_if_fail (location != NULL, NULL);
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	g_return_val_if_fail (content != NULL, NULL);
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	_tmp0_ = location;
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	self = (GherkinAstDocString*) gherkin_ast_abstract_node_construct (object_type, _tmp0_);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	_tmp1_ = contentType;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	gherkin_ast_doc_string_set_contentType (self, _tmp1_);
#line 10 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	_tmp2_ = content;
#line 10 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	gherkin_ast_doc_string_set_content (self, _tmp2_);
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	return self;
#line 119 "DocString.c"
}


GherkinAstDocString* gherkin_ast_doc_string_new (GherkinAstLocation* location, const gchar* contentType, const gchar* content) {
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	return gherkin_ast_doc_string_construct (GHERKIN_AST_TYPE_DOC_STRING, location, contentType, content);
#line 126 "DocString.c"
}


const gchar* gherkin_ast_doc_string_get_contentType (GherkinAstDocString* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	_tmp0_ = self->priv->_contentType;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	result = _tmp0_;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	return result;
#line 141 "DocString.c"
}


void gherkin_ast_doc_string_set_contentType (GherkinAstDocString* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	g_return_if_fail (self != NULL);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	_tmp0_ = value;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	_g_free0 (self->priv->_contentType);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	self->priv->_contentType = _tmp1_;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	g_object_notify ((GObject *) self, "contentType");
#line 160 "DocString.c"
}


const gchar* gherkin_ast_doc_string_get_content (GherkinAstDocString* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	_tmp0_ = self->priv->_content;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	result = _tmp0_;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	return result;
#line 175 "DocString.c"
}


void gherkin_ast_doc_string_set_content (GherkinAstDocString* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	g_return_if_fail (self != NULL);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	_tmp0_ = value;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	_g_free0 (self->priv->_content);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	self->priv->_content = _tmp1_;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	g_object_notify ((GObject *) self, "content");
#line 194 "DocString.c"
}


static void gherkin_ast_doc_string_class_init (GherkinAstDocStringClass * klass) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	gherkin_ast_doc_string_parent_class = g_type_class_peek_parent (klass);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	g_type_class_add_private (klass, sizeof (GherkinAstDocStringPrivate));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_gherkin_ast_doc_string_get_property;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_gherkin_ast_doc_string_set_property;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	G_OBJECT_CLASS (klass)->finalize = gherkin_ast_doc_string_finalize;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), GHERKIN_AST_DOC_STRING_CONTENT_TYPE, g_param_spec_string ("contentType", "contentType", "contentType", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), GHERKIN_AST_DOC_STRING_CONTENT, g_param_spec_string ("content", "content", "content", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 213 "DocString.c"
}


static void gherkin_ast_doc_string_instance_init (GherkinAstDocString * self) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	self->priv = GHERKIN_AST_DOC_STRING_GET_PRIVATE (self);
#line 220 "DocString.c"
}


static void gherkin_ast_doc_string_finalize (GObject* obj) {
	GherkinAstDocString * self;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GHERKIN_AST_TYPE_DOC_STRING, GherkinAstDocString);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	_g_free0 (self->priv->_contentType);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	_g_free0 (self->priv->_content);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	G_OBJECT_CLASS (gherkin_ast_doc_string_parent_class)->finalize (obj);
#line 234 "DocString.c"
}


GType gherkin_ast_doc_string_get_type (void) {
	static volatile gsize gherkin_ast_doc_string_type_id__volatile = 0;
	if (g_once_init_enter (&gherkin_ast_doc_string_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GherkinAstDocStringClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gherkin_ast_doc_string_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GherkinAstDocString), 0, (GInstanceInitFunc) gherkin_ast_doc_string_instance_init, NULL };
		GType gherkin_ast_doc_string_type_id;
		gherkin_ast_doc_string_type_id = g_type_register_static (GHERKIN_AST_TYPE_ABSTRACT_NODE, "GherkinAstDocString", &g_define_type_info, 0);
		g_once_init_leave (&gherkin_ast_doc_string_type_id__volatile, gherkin_ast_doc_string_type_id);
	}
	return gherkin_ast_doc_string_type_id__volatile;
}


static void _vala_gherkin_ast_doc_string_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GherkinAstDocString * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GHERKIN_AST_TYPE_DOC_STRING, GherkinAstDocString);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	switch (property_id) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
		case GHERKIN_AST_DOC_STRING_CONTENT_TYPE:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
		g_value_set_string (value, gherkin_ast_doc_string_get_contentType (self));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
		break;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
		case GHERKIN_AST_DOC_STRING_CONTENT:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
		g_value_set_string (value, gherkin_ast_doc_string_get_content (self));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
		break;
#line 267 "DocString.c"
		default:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
		break;
#line 273 "DocString.c"
	}
}


static void _vala_gherkin_ast_doc_string_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GherkinAstDocString * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GHERKIN_AST_TYPE_DOC_STRING, GherkinAstDocString);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
	switch (property_id) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
		case GHERKIN_AST_DOC_STRING_CONTENT_TYPE:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
		gherkin_ast_doc_string_set_contentType (self, g_value_get_string (value));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
		break;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
		case GHERKIN_AST_DOC_STRING_CONTENT:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
		gherkin_ast_doc_string_set_content (self, g_value_get_string (value));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
		break;
#line 295 "DocString.c"
		default:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/DocString.vala"
		break;
#line 301 "DocString.c"
	}
}



