/* Location.c generated by valac 0.30.0, the Vala compiler
 * generated from Location.vala, do not modify */


#include <glib.h>
#include <glib-object.h>


#define GHERKIN_AST_TYPE_LOCATION (gherkin_ast_location_get_type ())
#define GHERKIN_AST_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocation))
#define GHERKIN_AST_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocationClass))
#define GHERKIN_AST_IS_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_LOCATION))
#define GHERKIN_AST_IS_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_LOCATION))
#define GHERKIN_AST_LOCATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocationClass))

typedef struct _GherkinAstLocation GherkinAstLocation;
typedef struct _GherkinAstLocationClass GherkinAstLocationClass;
typedef struct _GherkinAstLocationPrivate GherkinAstLocationPrivate;

struct _GherkinAstLocation {
	GObject parent_instance;
	GherkinAstLocationPrivate * priv;
};

struct _GherkinAstLocationClass {
	GObjectClass parent_class;
};

struct _GherkinAstLocationPrivate {
	gint _line;
	gint _column;
};


static gpointer gherkin_ast_location_parent_class = NULL;

GType gherkin_ast_location_get_type (void) G_GNUC_CONST;
#define GHERKIN_AST_LOCATION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocationPrivate))
enum  {
	GHERKIN_AST_LOCATION_DUMMY_PROPERTY,
	GHERKIN_AST_LOCATION_LINE,
	GHERKIN_AST_LOCATION_COLUMN
};
GherkinAstLocation* gherkin_ast_location_new (gint line, gint column);
GherkinAstLocation* gherkin_ast_location_construct (GType object_type, gint line, gint column);
void gherkin_ast_location_set_line (GherkinAstLocation* self, gint value);
void gherkin_ast_location_set_column (GherkinAstLocation* self, gint value);
gint gherkin_ast_location_get_line (GherkinAstLocation* self);
gint gherkin_ast_location_get_column (GherkinAstLocation* self);
static void gherkin_ast_location_finalize (GObject* obj);
static void _vala_gherkin_ast_location_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_gherkin_ast_location_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


GherkinAstLocation* gherkin_ast_location_construct (GType object_type, gint line, gint column) {
	GherkinAstLocation * self = NULL;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	self = (GherkinAstLocation*) g_object_new (object_type, NULL);
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	_tmp0_ = line;
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	gherkin_ast_location_set_line (self, _tmp0_);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	_tmp1_ = column;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	gherkin_ast_location_set_column (self, _tmp1_);
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	return self;
#line 72 "Location.c"
}


GherkinAstLocation* gherkin_ast_location_new (gint line, gint column) {
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	return gherkin_ast_location_construct (GHERKIN_AST_TYPE_LOCATION, line, column);
#line 79 "Location.c"
}


gint gherkin_ast_location_get_line (GherkinAstLocation* self) {
	gint result;
	gint _tmp0_ = 0;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	_tmp0_ = self->priv->_line;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	result = _tmp0_;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	return result;
#line 94 "Location.c"
}


void gherkin_ast_location_set_line (GherkinAstLocation* self, gint value) {
	gint _tmp0_ = 0;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	g_return_if_fail (self != NULL);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	_tmp0_ = value;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	self->priv->_line = _tmp0_;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	g_object_notify ((GObject *) self, "line");
#line 108 "Location.c"
}


gint gherkin_ast_location_get_column (GherkinAstLocation* self) {
	gint result;
	gint _tmp0_ = 0;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	_tmp0_ = self->priv->_column;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	result = _tmp0_;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	return result;
#line 123 "Location.c"
}


void gherkin_ast_location_set_column (GherkinAstLocation* self, gint value) {
	gint _tmp0_ = 0;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	g_return_if_fail (self != NULL);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	_tmp0_ = value;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	self->priv->_column = _tmp0_;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	g_object_notify ((GObject *) self, "column");
#line 137 "Location.c"
}


static void gherkin_ast_location_class_init (GherkinAstLocationClass * klass) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	gherkin_ast_location_parent_class = g_type_class_peek_parent (klass);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	g_type_class_add_private (klass, sizeof (GherkinAstLocationPrivate));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_gherkin_ast_location_get_property;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_gherkin_ast_location_set_property;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	G_OBJECT_CLASS (klass)->finalize = gherkin_ast_location_finalize;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), GHERKIN_AST_LOCATION_LINE, g_param_spec_int ("line", "line", "line", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), GHERKIN_AST_LOCATION_COLUMN, g_param_spec_int ("column", "column", "column", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 156 "Location.c"
}


static void gherkin_ast_location_instance_init (GherkinAstLocation * self) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	self->priv = GHERKIN_AST_LOCATION_GET_PRIVATE (self);
#line 163 "Location.c"
}


static void gherkin_ast_location_finalize (GObject* obj) {
	GherkinAstLocation * self;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GHERKIN_AST_TYPE_LOCATION, GherkinAstLocation);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	G_OBJECT_CLASS (gherkin_ast_location_parent_class)->finalize (obj);
#line 173 "Location.c"
}


GType gherkin_ast_location_get_type (void) {
	static volatile gsize gherkin_ast_location_type_id__volatile = 0;
	if (g_once_init_enter (&gherkin_ast_location_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GherkinAstLocationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gherkin_ast_location_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GherkinAstLocation), 0, (GInstanceInitFunc) gherkin_ast_location_instance_init, NULL };
		GType gherkin_ast_location_type_id;
		gherkin_ast_location_type_id = g_type_register_static (G_TYPE_OBJECT, "GherkinAstLocation", &g_define_type_info, 0);
		g_once_init_leave (&gherkin_ast_location_type_id__volatile, gherkin_ast_location_type_id);
	}
	return gherkin_ast_location_type_id__volatile;
}


static void _vala_gherkin_ast_location_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GherkinAstLocation * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GHERKIN_AST_TYPE_LOCATION, GherkinAstLocation);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	switch (property_id) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
		case GHERKIN_AST_LOCATION_LINE:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
		g_value_set_int (value, gherkin_ast_location_get_line (self));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
		break;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
		case GHERKIN_AST_LOCATION_COLUMN:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
		g_value_set_int (value, gherkin_ast_location_get_column (self));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
		break;
#line 206 "Location.c"
		default:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
		break;
#line 212 "Location.c"
	}
}


static void _vala_gherkin_ast_location_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GherkinAstLocation * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GHERKIN_AST_TYPE_LOCATION, GherkinAstLocation);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
	switch (property_id) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
		case GHERKIN_AST_LOCATION_LINE:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
		gherkin_ast_location_set_line (self, g_value_get_int (value));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
		break;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
		case GHERKIN_AST_LOCATION_COLUMN:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
		gherkin_ast_location_set_column (self, g_value_get_int (value));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
		break;
#line 234 "Location.c"
		default:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Location.vala"
		break;
#line 240 "Location.c"
	}
}



