/* Node.c generated by valac 0.30.0, the Vala compiler
 * generated from Node.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <json-glib/json-glib.h>
#include <json-glib/json-gobject.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>


#define GHERKIN_AST_TYPE_ABSTRACT_NODE (gherkin_ast_abstract_node_get_type ())
#define GHERKIN_AST_ABSTRACT_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNode))
#define GHERKIN_AST_ABSTRACT_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNodeClass))
#define GHERKIN_AST_IS_ABSTRACT_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_ABSTRACT_NODE))
#define GHERKIN_AST_IS_ABSTRACT_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_ABSTRACT_NODE))
#define GHERKIN_AST_ABSTRACT_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNodeClass))

typedef struct _GherkinAstAbstractNode GherkinAstAbstractNode;
typedef struct _GherkinAstAbstractNodeClass GherkinAstAbstractNodeClass;
typedef struct _GherkinAstAbstractNodePrivate GherkinAstAbstractNodePrivate;

#define GHERKIN_AST_TYPE_LOCATION (gherkin_ast_location_get_type ())
#define GHERKIN_AST_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocation))
#define GHERKIN_AST_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocationClass))
#define GHERKIN_AST_IS_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_LOCATION))
#define GHERKIN_AST_IS_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_LOCATION))
#define GHERKIN_AST_LOCATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocationClass))

typedef struct _GherkinAstLocation GherkinAstLocation;
typedef struct _GherkinAstLocationClass GherkinAstLocationClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define GHERKIN_AST_TYPE_TAG (gherkin_ast_tag_get_type ())
#define GHERKIN_AST_TAG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_TAG, GherkinAstTag))
#define GHERKIN_AST_TAG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_TAG, GherkinAstTagClass))
#define GHERKIN_AST_IS_TAG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_TAG))
#define GHERKIN_AST_IS_TAG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_TAG))
#define GHERKIN_AST_TAG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_TAG, GherkinAstTagClass))

typedef struct _GherkinAstTag GherkinAstTag;
typedef struct _GherkinAstTagClass GherkinAstTagClass;
typedef struct _Block20Data Block20Data;
#define _json_array_unref0(var) ((var == NULL) ? NULL : (var = (json_array_unref (var), NULL)))

#define GHERKIN_AST_TYPE_SCENARIO_DEFINITION (gherkin_ast_scenario_definition_get_type ())
#define GHERKIN_AST_SCENARIO_DEFINITION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_SCENARIO_DEFINITION, GherkinAstScenarioDefinition))
#define GHERKIN_AST_SCENARIO_DEFINITION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_SCENARIO_DEFINITION, GherkinAstScenarioDefinitionClass))
#define GHERKIN_AST_IS_SCENARIO_DEFINITION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_SCENARIO_DEFINITION))
#define GHERKIN_AST_IS_SCENARIO_DEFINITION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_SCENARIO_DEFINITION))
#define GHERKIN_AST_SCENARIO_DEFINITION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_SCENARIO_DEFINITION, GherkinAstScenarioDefinitionClass))

typedef struct _GherkinAstScenarioDefinition GherkinAstScenarioDefinition;
typedef struct _GherkinAstScenarioDefinitionClass GherkinAstScenarioDefinitionClass;
typedef struct _Block21Data Block21Data;

#define GHERKIN_AST_TYPE_SCENARIO (gherkin_ast_scenario_get_type ())
#define GHERKIN_AST_SCENARIO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_SCENARIO, GherkinAstScenario))
#define GHERKIN_AST_SCENARIO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_SCENARIO, GherkinAstScenarioClass))
#define GHERKIN_AST_IS_SCENARIO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_SCENARIO))
#define GHERKIN_AST_IS_SCENARIO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_SCENARIO))
#define GHERKIN_AST_SCENARIO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_SCENARIO, GherkinAstScenarioClass))

typedef struct _GherkinAstScenario GherkinAstScenario;
typedef struct _GherkinAstScenarioClass GherkinAstScenarioClass;

#define GHERKIN_AST_TYPE_COMMENT (gherkin_ast_comment_get_type ())
#define GHERKIN_AST_COMMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_COMMENT, GherkinAstComment))
#define GHERKIN_AST_COMMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_COMMENT, GherkinAstCommentClass))
#define GHERKIN_AST_IS_COMMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_COMMENT))
#define GHERKIN_AST_IS_COMMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_COMMENT))
#define GHERKIN_AST_COMMENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_COMMENT, GherkinAstCommentClass))

typedef struct _GherkinAstComment GherkinAstComment;
typedef struct _GherkinAstCommentClass GherkinAstCommentClass;
typedef struct _Block22Data Block22Data;

#define GHERKIN_AST_TYPE_BACKGROUND (gherkin_ast_background_get_type ())
#define GHERKIN_AST_BACKGROUND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_BACKGROUND, GherkinAstBackground))
#define GHERKIN_AST_BACKGROUND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_BACKGROUND, GherkinAstBackgroundClass))
#define GHERKIN_AST_IS_BACKGROUND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_BACKGROUND))
#define GHERKIN_AST_IS_BACKGROUND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_BACKGROUND))
#define GHERKIN_AST_BACKGROUND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_BACKGROUND, GherkinAstBackgroundClass))

typedef struct _GherkinAstBackground GherkinAstBackground;
typedef struct _GherkinAstBackgroundClass GherkinAstBackgroundClass;
#define _g_type_class_unref0(var) ((var == NULL) ? NULL : (var = (g_type_class_unref (var), NULL)))

struct _GherkinAstAbstractNode {
	GObject parent_instance;
	GherkinAstAbstractNodePrivate * priv;
};

struct _GherkinAstAbstractNodeClass {
	GObjectClass parent_class;
	JsonNode* (*serialize_property) (GherkinAstAbstractNode* self, const gchar* property_name, GValue* value, GParamSpec* pspec);
	gboolean (*deserialize_property) (GherkinAstAbstractNode* self, const gchar* property_name, GValue* value, GParamSpec* pspec, JsonNode* property_node);
};

struct _GherkinAstAbstractNodePrivate {
	gchar* _node_type;
	GherkinAstLocation* _location;
};

struct _Block20Data {
	int _ref_count_;
	GherkinAstAbstractNode* self;
	GeeArrayList* stepvar;
};

struct _Block21Data {
	int _ref_count_;
	GherkinAstAbstractNode* self;
	GeeArrayList* stepvar;
};

struct _Block22Data {
	int _ref_count_;
	GherkinAstAbstractNode* self;
	GeeArrayList* stepvar;
};


static gpointer gherkin_ast_abstract_node_parent_class = NULL;
static JsonSerializableIface* gherkin_ast_abstract_node_json_serializable_parent_iface = NULL;

GType gherkin_ast_abstract_node_get_type (void) G_GNUC_CONST;
GType gherkin_ast_location_get_type (void) G_GNUC_CONST;
#define GHERKIN_AST_ABSTRACT_NODE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNodePrivate))
enum  {
	GHERKIN_AST_ABSTRACT_NODE_DUMMY_PROPERTY,
	GHERKIN_AST_ABSTRACT_NODE_NODE_TYPE,
	GHERKIN_AST_ABSTRACT_NODE_LOCATION
};
GherkinAstAbstractNode* gherkin_ast_abstract_node_construct (GType object_type, GherkinAstLocation* location);
void gherkin_ast_abstract_node_set_location (GherkinAstAbstractNode* self, GherkinAstLocation* value);
void gherkin_ast_abstract_node_set_node_type (GherkinAstAbstractNode* self, const gchar* value);
gchar* gherkin_ast_abstract_node_to_string (GherkinAstAbstractNode* self);
GherkinAstLocation* gherkin_ast_abstract_node_get_location (GherkinAstAbstractNode* self);
gint gherkin_ast_location_get_line (GherkinAstLocation* self);
gint gherkin_ast_location_get_column (GherkinAstLocation* self);
const gchar* gherkin_ast_abstract_node_get_node_type (GherkinAstAbstractNode* self);
JsonNode* gherkin_ast_abstract_node_serialize_property (GherkinAstAbstractNode* self, const gchar* property_name, GValue* value, GParamSpec* pspec);
static JsonNode* gherkin_ast_abstract_node_real_serialize_property (GherkinAstAbstractNode* self, const gchar* property_name, GValue* value, GParamSpec* pspec);
gboolean gherkin_ast_abstract_node_deserialize_property (GherkinAstAbstractNode* self, const gchar* property_name, GValue* value, GParamSpec* pspec, JsonNode* property_node);
static gboolean gherkin_ast_abstract_node_real_deserialize_property (GherkinAstAbstractNode* self, const gchar* property_name, GValue* value, GParamSpec* pspec, JsonNode* property_node);
GType gherkin_ast_tag_get_type (void) G_GNUC_CONST;
static Block20Data* block20_data_ref (Block20Data* _data20_);
static void block20_data_unref (void * _userdata_);
static void ___lambda22_ (Block20Data* _data20_, JsonArray* a, guint i, JsonNode* n);
static void ____lambda22__json_array_foreach (JsonArray* array, guint index_, JsonNode* element_node, gpointer self);
GType gherkin_ast_scenario_definition_get_type (void) G_GNUC_CONST;
static Block21Data* block21_data_ref (Block21Data* _data21_);
static void block21_data_unref (void * _userdata_);
static void ___lambda25_ (Block21Data* _data21_, JsonArray* a, guint i, JsonNode* n);
GType gherkin_ast_scenario_get_type (void) G_GNUC_CONST;
static void ____lambda25__json_array_foreach (JsonArray* array, guint index_, JsonNode* element_node, gpointer self);
GType gherkin_ast_comment_get_type (void) G_GNUC_CONST;
static Block22Data* block22_data_ref (Block22Data* _data22_);
static void block22_data_unref (void * _userdata_);
static void ___lambda26_ (Block22Data* _data22_, JsonArray* a, guint i, JsonNode* n);
static void ____lambda26__json_array_foreach (JsonArray* array, guint index_, JsonNode* element_node, gpointer self);
GType gherkin_ast_background_get_type (void) G_GNUC_CONST;
static GParamSpec* gherkin_ast_abstract_node_real_find_property (JsonSerializable* base, const gchar* name);
static void gherkin_ast_abstract_node_finalize (GObject* obj);
static void _vala_gherkin_ast_abstract_node_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_gherkin_ast_abstract_node_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static gchar* string_replace (const gchar* self, const gchar* old, const gchar* replacement) {
	gchar* result = NULL;
	GError * _inner_error_ = NULL;
#line 1282 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1282 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	g_return_val_if_fail (old != NULL, NULL);
#line 1282 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	g_return_val_if_fail (replacement != NULL, NULL);
#line 185 "Node.c"
	{
		GRegex* regex = NULL;
		const gchar* _tmp0_ = NULL;
		gchar* _tmp1_ = NULL;
		gchar* _tmp2_ = NULL;
		GRegex* _tmp3_ = NULL;
		GRegex* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		GRegex* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
#line 1284 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		_tmp0_ = old;
#line 1284 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		_tmp1_ = g_regex_escape_string (_tmp0_, -1);
#line 1284 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		_tmp2_ = _tmp1_;
#line 1284 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		_tmp3_ = g_regex_new (_tmp2_, 0, 0, &_inner_error_);
#line 1284 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		_tmp4_ = _tmp3_;
#line 1284 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		_g_free0 (_tmp2_);
#line 1284 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		regex = _tmp4_;
#line 1284 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1284 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
			if (_inner_error_->domain == G_REGEX_ERROR) {
#line 216 "Node.c"
				goto __catch5_g_regex_error;
			}
#line 1284 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 1284 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
			g_clear_error (&_inner_error_);
#line 1284 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
			return NULL;
#line 225 "Node.c"
		}
#line 1285 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		_tmp6_ = regex;
#line 1285 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		_tmp7_ = replacement;
#line 1285 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		_tmp8_ = g_regex_replace_literal (_tmp6_, self, (gssize) -1, 0, _tmp7_, 0, &_inner_error_);
#line 1285 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		_tmp5_ = _tmp8_;
#line 1285 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1285 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
			_g_regex_unref0 (regex);
#line 1285 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
			if (_inner_error_->domain == G_REGEX_ERROR) {
#line 241 "Node.c"
				goto __catch5_g_regex_error;
			}
#line 1285 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
			_g_regex_unref0 (regex);
#line 1285 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 1285 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
			g_clear_error (&_inner_error_);
#line 1285 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
			return NULL;
#line 252 "Node.c"
		}
#line 1285 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		_tmp9_ = _tmp5_;
#line 1285 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		_tmp5_ = NULL;
#line 1285 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		result = _tmp9_;
#line 1285 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		_g_free0 (_tmp5_);
#line 1285 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		_g_regex_unref0 (regex);
#line 1285 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		return result;
#line 266 "Node.c"
	}
	goto __finally5;
	__catch5_g_regex_error:
	{
		GError* e = NULL;
#line 1283 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		e = _inner_error_;
#line 1283 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		_inner_error_ = NULL;
#line 1287 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		g_assert_not_reached ();
#line 1283 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		_g_error_free0 (e);
#line 280 "Node.c"
	}
	__finally5:
#line 1283 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1283 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 1283 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		g_clear_error (&_inner_error_);
#line 1283 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		return NULL;
#line 291 "Node.c"
	}
}


GherkinAstAbstractNode* gherkin_ast_abstract_node_construct (GType object_type, GherkinAstLocation* location) {
	GherkinAstAbstractNode * self = NULL;
	GherkinAstLocation* _tmp0_ = NULL;
	GType _tmp1_ = 0UL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_return_val_if_fail (location != NULL, NULL);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	self = (GherkinAstAbstractNode*) g_object_new (object_type, NULL);
#line 10 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp0_ = location;
#line 10 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	gherkin_ast_abstract_node_set_location (self, _tmp0_);
#line 11 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp1_ = G_TYPE_FROM_INSTANCE ((GObject*) self);
#line 11 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp2_ = g_type_name (_tmp1_);
#line 11 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp3_ = string_replace (_tmp2_, "GherkinAst", "");
#line 11 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp4_ = _tmp3_;
#line 11 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	gherkin_ast_abstract_node_set_node_type (self, _tmp4_);
#line 11 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_g_free0 (_tmp4_);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	return self;
#line 325 "Node.c"
}


gchar* gherkin_ast_abstract_node_to_string (GherkinAstAbstractNode* self) {
	gchar* result = NULL;
	GherkinAstLocation* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	GherkinAstLocation* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	const gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp0_ = self->priv->_location;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp1_ = gherkin_ast_location_get_line (_tmp0_);
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp2_ = _tmp1_;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp3_ = self->priv->_location;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp4_ = gherkin_ast_location_get_column (_tmp3_);
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp5_ = _tmp4_;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp6_ = self->priv->_node_type;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp7_ = g_strdup_printf ("(%d:%d) %s", _tmp2_, _tmp5_, _tmp6_);
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	result = _tmp7_;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	return result;
#line 361 "Node.c"
}


/**
 * Json.Serializable interface implementation
 */
static JsonNode* gherkin_ast_abstract_node_real_serialize_property (GherkinAstAbstractNode* self, const gchar* property_name, GValue* value, GParamSpec* pspec) {
	JsonNode* result = NULL;
	const gchar* _tmp0_ = NULL;
	GValue _tmp1_ = {0};
	GParamSpec* _tmp2_ = NULL;
	JsonNode* _tmp3_ = NULL;
#line 22 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_return_val_if_fail (property_name != NULL, NULL);
#line 22 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_return_val_if_fail (value != NULL, NULL);
#line 22 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_return_val_if_fail (pspec != NULL, NULL);
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp0_ = property_name;
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp1_ = *value;
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp2_ = pspec;
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp3_ = json_serializable_default_serialize_property ((JsonSerializable*) self, _tmp0_, &_tmp1_, _tmp2_);
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	result = _tmp3_;
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	return result;
#line 392 "Node.c"
}


JsonNode* gherkin_ast_abstract_node_serialize_property (GherkinAstAbstractNode* self, const gchar* property_name, GValue* value, GParamSpec* pspec) {
#line 22 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 22 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	return GHERKIN_AST_ABSTRACT_NODE_GET_CLASS (self)->serialize_property (self, property_name, value, pspec);
#line 401 "Node.c"
}


static Block20Data* block20_data_ref (Block20Data* _data20_) {
#line 44 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_atomic_int_inc (&_data20_->_ref_count_);
#line 44 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	return _data20_;
#line 410 "Node.c"
}


static void block20_data_unref (void * _userdata_) {
	Block20Data* _data20_;
	_data20_ = (Block20Data*) _userdata_;
#line 44 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	if (g_atomic_int_dec_and_test (&_data20_->_ref_count_)) {
#line 419 "Node.c"
		GherkinAstAbstractNode* self;
#line 44 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		self = _data20_->self;
#line 44 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_g_object_unref0 (_data20_->stepvar);
#line 44 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_g_object_unref0 (self);
#line 44 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		g_slice_free (Block20Data, _data20_);
#line 429 "Node.c"
	}
}


static gpointer _json_array_ref0 (gpointer self) {
#line 46 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	return self ? json_array_ref (self) : NULL;
#line 437 "Node.c"
}


static void ___lambda22_ (Block20Data* _data20_, JsonArray* a, guint i, JsonNode* n) {
	GherkinAstAbstractNode* self;
	GeeArrayList* _tmp0_ = NULL;
	JsonNode* _tmp1_ = NULL;
	GObject* _tmp2_ = NULL;
	GherkinAstTag* _tmp3_ = NULL;
	GherkinAstTag* _tmp4_ = NULL;
#line 47 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	self = _data20_->self;
#line 47 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_return_if_fail (a != NULL);
#line 47 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_return_if_fail (n != NULL);
#line 48 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp0_ = _data20_->stepvar;
#line 48 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp1_ = n;
#line 48 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp2_ = json_gobject_deserialize (GHERKIN_AST_TYPE_TAG, _tmp1_);
#line 48 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp3_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp2_, GHERKIN_AST_TYPE_TAG) ? ((GherkinAstTag*) _tmp2_) : NULL;
#line 48 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	if (_tmp3_ == NULL) {
#line 48 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_g_object_unref0 (_tmp2_);
#line 466 "Node.c"
	}
#line 48 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp4_ = _tmp3_;
#line 48 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp0_, _tmp4_);
#line 48 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_g_object_unref0 (_tmp4_);
#line 474 "Node.c"
}


static void ____lambda22__json_array_foreach (JsonArray* array, guint index_, JsonNode* element_node, gpointer self) {
#line 47 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	___lambda22_ (self, array, index_, element_node);
#line 481 "Node.c"
}


static Block21Data* block21_data_ref (Block21Data* _data21_) {
#line 54 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_atomic_int_inc (&_data21_->_ref_count_);
#line 54 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	return _data21_;
#line 490 "Node.c"
}


static void block21_data_unref (void * _userdata_) {
	Block21Data* _data21_;
	_data21_ = (Block21Data*) _userdata_;
#line 54 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	if (g_atomic_int_dec_and_test (&_data21_->_ref_count_)) {
#line 499 "Node.c"
		GherkinAstAbstractNode* self;
#line 54 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		self = _data21_->self;
#line 54 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_g_object_unref0 (_data21_->stepvar);
#line 54 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_g_object_unref0 (self);
#line 54 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		g_slice_free (Block21Data, _data21_);
#line 509 "Node.c"
	}
}


static void ___lambda25_ (Block21Data* _data21_, JsonArray* a, guint i, JsonNode* n) {
	GherkinAstAbstractNode* self;
	GeeArrayList* _tmp0_ = NULL;
	JsonNode* _tmp1_ = NULL;
	GObject* _tmp2_ = NULL;
	GherkinAstScenarioDefinition* _tmp3_ = NULL;
	GherkinAstScenarioDefinition* _tmp4_ = NULL;
#line 57 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	self = _data21_->self;
#line 57 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_return_if_fail (a != NULL);
#line 57 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_return_if_fail (n != NULL);
#line 58 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp0_ = _data21_->stepvar;
#line 58 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp1_ = n;
#line 58 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp2_ = json_gobject_deserialize (GHERKIN_AST_TYPE_SCENARIO, _tmp1_);
#line 58 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp3_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp2_, GHERKIN_AST_TYPE_SCENARIO_DEFINITION) ? ((GherkinAstScenarioDefinition*) _tmp2_) : NULL;
#line 58 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	if (_tmp3_ == NULL) {
#line 58 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_g_object_unref0 (_tmp2_);
#line 539 "Node.c"
	}
#line 58 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp4_ = _tmp3_;
#line 58 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp0_, _tmp4_);
#line 58 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_g_object_unref0 (_tmp4_);
#line 547 "Node.c"
}


static void ____lambda25__json_array_foreach (JsonArray* array, guint index_, JsonNode* element_node, gpointer self) {
#line 57 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	___lambda25_ (self, array, index_, element_node);
#line 554 "Node.c"
}


static Block22Data* block22_data_ref (Block22Data* _data22_) {
#line 64 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_atomic_int_inc (&_data22_->_ref_count_);
#line 64 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	return _data22_;
#line 563 "Node.c"
}


static void block22_data_unref (void * _userdata_) {
	Block22Data* _data22_;
	_data22_ = (Block22Data*) _userdata_;
#line 64 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	if (g_atomic_int_dec_and_test (&_data22_->_ref_count_)) {
#line 572 "Node.c"
		GherkinAstAbstractNode* self;
#line 64 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		self = _data22_->self;
#line 64 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_g_object_unref0 (_data22_->stepvar);
#line 64 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_g_object_unref0 (self);
#line 64 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		g_slice_free (Block22Data, _data22_);
#line 582 "Node.c"
	}
}


static void ___lambda26_ (Block22Data* _data22_, JsonArray* a, guint i, JsonNode* n) {
	GherkinAstAbstractNode* self;
	GeeArrayList* _tmp0_ = NULL;
	JsonNode* _tmp1_ = NULL;
	GObject* _tmp2_ = NULL;
	GherkinAstComment* _tmp3_ = NULL;
	GherkinAstComment* _tmp4_ = NULL;
#line 67 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	self = _data22_->self;
#line 67 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_return_if_fail (a != NULL);
#line 67 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_return_if_fail (n != NULL);
#line 68 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp0_ = _data22_->stepvar;
#line 68 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp1_ = n;
#line 68 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp2_ = json_gobject_deserialize (GHERKIN_AST_TYPE_COMMENT, _tmp1_);
#line 68 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp3_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp2_, GHERKIN_AST_TYPE_COMMENT) ? ((GherkinAstComment*) _tmp2_) : NULL;
#line 68 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	if (_tmp3_ == NULL) {
#line 68 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_g_object_unref0 (_tmp2_);
#line 612 "Node.c"
	}
#line 68 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp4_ = _tmp3_;
#line 68 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp0_, _tmp4_);
#line 68 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_g_object_unref0 (_tmp4_);
#line 620 "Node.c"
}


static void ____lambda26__json_array_foreach (JsonArray* array, guint index_, JsonNode* element_node, gpointer self) {
#line 67 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	___lambda26_ (self, array, index_, element_node);
#line 627 "Node.c"
}


static gboolean gherkin_ast_abstract_node_real_deserialize_property (GherkinAstAbstractNode* self, const gchar* property_name, GValue* value, GParamSpec* pspec, JsonNode* property_node) {
	GValue _vala_value = {0};
	gboolean result = FALSE;
	GParamSpec* _tmp0_ = NULL;
	GType _tmp1_ = 0UL;
	const gchar* _tmp4_ = NULL;
	const gchar* _tmp8_ = NULL;
	const gchar* _tmp12_ = NULL;
	const gchar* _tmp19_ = NULL;
	const gchar* _tmp26_ = NULL;
	const gchar* _tmp33_ = NULL;
	const gchar* _tmp37_ = NULL;
	const gchar* _tmp47_ = NULL;
	GValue _tmp48_ = {0};
	GParamSpec* _tmp49_ = NULL;
	JsonNode* _tmp50_ = NULL;
	gboolean _tmp51_ = FALSE;
#line 26 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_return_val_if_fail (property_name != NULL, FALSE);
#line 26 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_return_val_if_fail (pspec != NULL, FALSE);
#line 26 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_return_val_if_fail (property_node != NULL, FALSE);
#line 28 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp0_ = pspec;
#line 28 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp1_ = _tmp0_->value_type;
#line 28 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	if (_tmp1_ == G_TYPE_STRING) {
#line 660 "Node.c"
		JsonNode* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
#line 29 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		g_value_init (&_vala_value, G_TYPE_STRING);
#line 30 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp2_ = property_node;
#line 30 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp3_ = json_node_get_string (_tmp2_);
#line 30 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		g_value_set_string (&_vala_value, _tmp3_);
#line 31 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		result = TRUE;
#line 31 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		if (value) {
#line 31 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
			*value = _vala_value;
#line 677 "Node.c"
		} else {
#line 31 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
			G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
#line 681 "Node.c"
		}
#line 31 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		return result;
#line 685 "Node.c"
	}
#line 34 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp4_ = property_name;
#line 34 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	if (g_strcmp0 (_tmp4_, "location") == 0) {
#line 691 "Node.c"
		JsonNode* _tmp5_ = NULL;
		GObject* _tmp6_ = NULL;
		GherkinAstLocation* _tmp7_ = NULL;
#line 35 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp5_ = property_node;
#line 35 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp6_ = json_gobject_deserialize (GHERKIN_AST_TYPE_LOCATION, _tmp5_);
#line 35 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp7_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp6_, GHERKIN_AST_TYPE_LOCATION) ? ((GherkinAstLocation*) _tmp6_) : NULL;
#line 35 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		if (_tmp7_ == NULL) {
#line 35 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
			_g_object_unref0 (_tmp6_);
#line 705 "Node.c"
		}
#line 35 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		g_value_init_from_instance (&_vala_value, _tmp7_);
#line 36 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		result = TRUE;
#line 36 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		if (value) {
#line 36 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
			*value = _vala_value;
#line 715 "Node.c"
		} else {
#line 36 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
			G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
#line 719 "Node.c"
		}
#line 36 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		return result;
#line 723 "Node.c"
	}
#line 39 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp8_ = property_name;
#line 39 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	if (g_strcmp0 (_tmp8_, "node-type") == 0) {
#line 729 "Node.c"
		GType _tmp9_ = 0UL;
		const gchar* _tmp10_ = NULL;
		gchar* _tmp11_ = NULL;
#line 40 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp9_ = G_TYPE_FROM_INSTANCE ((GObject*) self);
#line 40 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp10_ = g_type_name (_tmp9_);
#line 40 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp11_ = string_replace (_tmp10_, "GherkinAst", "");
#line 40 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		g_value_init_from_instance (&_vala_value, _tmp11_);
#line 41 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		result = TRUE;
#line 41 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		if (value) {
#line 41 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
			*value = _vala_value;
#line 747 "Node.c"
		} else {
#line 41 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
			G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
#line 751 "Node.c"
		}
#line 41 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		return result;
#line 755 "Node.c"
	}
#line 44 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp12_ = property_name;
#line 44 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	if (g_strcmp0 (_tmp12_, "tags") == 0) {
#line 761 "Node.c"
		Block20Data* _data20_;
		GeeArrayList* _tmp13_ = NULL;
		JsonArray* array = NULL;
		JsonNode* _tmp14_ = NULL;
		JsonArray* _tmp15_ = NULL;
		JsonArray* _tmp16_ = NULL;
		JsonArray* _tmp17_ = NULL;
		GeeArrayList* _tmp18_ = NULL;
#line 44 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_data20_ = g_slice_new0 (Block20Data);
#line 44 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_data20_->_ref_count_ = 1;
#line 44 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_data20_->self = g_object_ref (self);
#line 45 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp13_ = gee_array_list_new (GHERKIN_AST_TYPE_TAG, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
#line 45 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_data20_->stepvar = _tmp13_;
#line 46 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp14_ = property_node;
#line 46 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp15_ = json_node_get_array (_tmp14_);
#line 46 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp16_ = _json_array_ref0 (_tmp15_);
#line 46 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		array = _tmp16_;
#line 47 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp17_ = array;
#line 47 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		json_array_foreach_element (_tmp17_, ____lambda22__json_array_foreach, _data20_);
#line 50 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp18_ = _data20_->stepvar;
#line 50 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		g_value_init_from_instance (&_vala_value, _tmp18_);
#line 51 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		result = TRUE;
#line 51 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_json_array_unref0 (array);
#line 51 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		block20_data_unref (_data20_);
#line 51 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_data20_ = NULL;
#line 51 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		if (value) {
#line 51 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
			*value = _vala_value;
#line 808 "Node.c"
		} else {
#line 51 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
			G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
#line 812 "Node.c"
		}
#line 51 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		return result;
#line 816 "Node.c"
	}
#line 54 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp19_ = property_name;
#line 54 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	if (g_strcmp0 (_tmp19_, "scenarioDefinitions") == 0) {
#line 822 "Node.c"
		Block21Data* _data21_;
		GeeArrayList* _tmp20_ = NULL;
		JsonArray* array = NULL;
		JsonNode* _tmp21_ = NULL;
		JsonArray* _tmp22_ = NULL;
		JsonArray* _tmp23_ = NULL;
		JsonArray* _tmp24_ = NULL;
		GeeArrayList* _tmp25_ = NULL;
#line 54 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_data21_ = g_slice_new0 (Block21Data);
#line 54 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_data21_->_ref_count_ = 1;
#line 54 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_data21_->self = g_object_ref (self);
#line 55 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp20_ = gee_array_list_new (GHERKIN_AST_TYPE_SCENARIO_DEFINITION, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
#line 55 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_data21_->stepvar = _tmp20_;
#line 56 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp21_ = property_node;
#line 56 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp22_ = json_node_get_array (_tmp21_);
#line 56 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp23_ = _json_array_ref0 (_tmp22_);
#line 56 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		array = _tmp23_;
#line 57 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp24_ = array;
#line 57 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		json_array_foreach_element (_tmp24_, ____lambda25__json_array_foreach, _data21_);
#line 60 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp25_ = _data21_->stepvar;
#line 60 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		g_value_init_from_instance (&_vala_value, _tmp25_);
#line 61 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		result = TRUE;
#line 61 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_json_array_unref0 (array);
#line 61 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		block21_data_unref (_data21_);
#line 61 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_data21_ = NULL;
#line 61 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		if (value) {
#line 61 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
			*value = _vala_value;
#line 869 "Node.c"
		} else {
#line 61 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
			G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
#line 873 "Node.c"
		}
#line 61 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		return result;
#line 877 "Node.c"
	}
#line 64 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp26_ = property_name;
#line 64 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	if (g_strcmp0 (_tmp26_, "comments") == 0) {
#line 883 "Node.c"
		Block22Data* _data22_;
		GeeArrayList* _tmp27_ = NULL;
		JsonArray* array = NULL;
		JsonNode* _tmp28_ = NULL;
		JsonArray* _tmp29_ = NULL;
		JsonArray* _tmp30_ = NULL;
		JsonArray* _tmp31_ = NULL;
		GeeArrayList* _tmp32_ = NULL;
#line 64 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_data22_ = g_slice_new0 (Block22Data);
#line 64 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_data22_->_ref_count_ = 1;
#line 64 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_data22_->self = g_object_ref (self);
#line 65 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp27_ = gee_array_list_new (GHERKIN_AST_TYPE_COMMENT, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
#line 65 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_data22_->stepvar = _tmp27_;
#line 66 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp28_ = property_node;
#line 66 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp29_ = json_node_get_array (_tmp28_);
#line 66 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp30_ = _json_array_ref0 (_tmp29_);
#line 66 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		array = _tmp30_;
#line 67 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp31_ = array;
#line 67 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		json_array_foreach_element (_tmp31_, ____lambda26__json_array_foreach, _data22_);
#line 70 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp32_ = _data22_->stepvar;
#line 70 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		g_value_init_from_instance (&_vala_value, _tmp32_);
#line 71 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		result = TRUE;
#line 71 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_json_array_unref0 (array);
#line 71 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		block22_data_unref (_data22_);
#line 71 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_data22_ = NULL;
#line 71 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		if (value) {
#line 71 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
			*value = _vala_value;
#line 930 "Node.c"
		} else {
#line 71 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
			G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
#line 934 "Node.c"
		}
#line 71 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		return result;
#line 938 "Node.c"
	}
#line 74 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp33_ = property_name;
#line 74 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	if (g_strcmp0 (_tmp33_, "background") == 0) {
#line 944 "Node.c"
		JsonNode* _tmp34_ = NULL;
		GObject* _tmp35_ = NULL;
		GherkinAstBackground* _tmp36_ = NULL;
#line 75 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp34_ = property_node;
#line 75 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp35_ = json_gobject_deserialize (GHERKIN_AST_TYPE_BACKGROUND, _tmp34_);
#line 75 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp36_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp35_, GHERKIN_AST_TYPE_BACKGROUND) ? ((GherkinAstBackground*) _tmp35_) : NULL;
#line 75 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		if (_tmp36_ == NULL) {
#line 75 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
			_g_object_unref0 (_tmp35_);
#line 958 "Node.c"
		}
#line 75 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		g_value_init_from_instance (&_vala_value, _tmp36_);
#line 76 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		result = TRUE;
#line 76 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		if (value) {
#line 76 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
			*value = _vala_value;
#line 968 "Node.c"
		} else {
#line 76 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
			G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
#line 972 "Node.c"
		}
#line 76 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		return result;
#line 976 "Node.c"
	}
#line 79 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp37_ = property_name;
#line 79 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	if (g_strcmp0 (_tmp37_, "argument") == 0) {
#line 982 "Node.c"
		gchar* objtype = NULL;
		JsonNode* _tmp38_ = NULL;
		JsonObject* _tmp39_ = NULL;
		const gchar* _tmp40_ = NULL;
		gchar* _tmp41_ = NULL;
		const gchar* _tmp42_ = NULL;
		GType _tmp43_ = 0UL;
		JsonNode* _tmp44_ = NULL;
		GObject* _tmp45_ = NULL;
		GherkinAstAbstractNode* _tmp46_ = NULL;
#line 80 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp38_ = property_node;
#line 80 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp39_ = json_node_get_object (_tmp38_);
#line 80 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp40_ = json_object_get_string_member (_tmp39_, "node-type");
#line 80 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp41_ = g_strconcat ("GherkinAst", _tmp40_, NULL);
#line 80 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		objtype = _tmp41_;
#line 81 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp42_ = objtype;
#line 81 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp43_ = g_type_from_name (_tmp42_);
#line 81 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp44_ = property_node;
#line 81 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp45_ = json_gobject_deserialize (_tmp43_, _tmp44_);
#line 81 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_tmp46_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp45_, GHERKIN_AST_TYPE_ABSTRACT_NODE) ? ((GherkinAstAbstractNode*) _tmp45_) : NULL;
#line 81 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		if (_tmp46_ == NULL) {
#line 81 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
			_g_object_unref0 (_tmp45_);
#line 1017 "Node.c"
		}
#line 81 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		g_value_init_from_instance (&_vala_value, _tmp46_);
#line 82 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		result = TRUE;
#line 82 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		_g_free0 (objtype);
#line 82 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		if (value) {
#line 82 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
			*value = _vala_value;
#line 1029 "Node.c"
		} else {
#line 82 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
			G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
#line 1033 "Node.c"
		}
#line 82 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		return result;
#line 1037 "Node.c"
	}
#line 85 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp47_ = property_name;
#line 85 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp48_ = _vala_value;
#line 85 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp49_ = pspec;
#line 85 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp50_ = property_node;
#line 85 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp51_ = json_serializable_default_deserialize_property ((JsonSerializable*) self, _tmp47_, &_tmp48_, _tmp49_, _tmp50_);
#line 85 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	result = _tmp51_;
#line 85 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	if (value) {
#line 85 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		*value = _vala_value;
#line 1055 "Node.c"
	} else {
#line 85 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
#line 1059 "Node.c"
	}
#line 85 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	return result;
#line 1063 "Node.c"
}


gboolean gherkin_ast_abstract_node_deserialize_property (GherkinAstAbstractNode* self, const gchar* property_name, GValue* value, GParamSpec* pspec, JsonNode* property_node) {
#line 26 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 26 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	return GHERKIN_AST_ABSTRACT_NODE_GET_CLASS (self)->deserialize_property (self, property_name, value, pspec, property_node);
#line 1072 "Node.c"
}


static GParamSpec* gherkin_ast_abstract_node_real_find_property (JsonSerializable* base, const gchar* name) {
	GherkinAstAbstractNode * self;
	GParamSpec* result = NULL;
	GType type = 0UL;
	GType _tmp0_ = 0UL;
	GObjectClass* ocl = NULL;
	GTypeClass* _tmp1_ = NULL;
	GParamSpec* spec = NULL;
	const gchar* _tmp2_ = NULL;
	GParamSpec* _tmp3_ = NULL;
#line 88 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	self = (GherkinAstAbstractNode*) base;
#line 88 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 89 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp0_ = G_TYPE_FROM_INSTANCE ((GObject*) self);
#line 89 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	type = _tmp0_;
#line 90 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp1_ = g_type_class_ref (type);
#line 90 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	ocl = (GObjectClass*) _tmp1_;
#line 91 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp2_ = name;
#line 91 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp3_ = g_object_class_find_property (ocl, _tmp2_);
#line 91 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	spec = _tmp3_;
#line 92 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	result = spec;
#line 92 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_g_type_class_unref0 (ocl);
#line 92 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	return result;
#line 1110 "Node.c"
}


const gchar* gherkin_ast_abstract_node_get_node_type (GherkinAstAbstractNode* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp0_ = self->priv->_node_type;
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	result = _tmp0_;
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	return result;
#line 1125 "Node.c"
}


void gherkin_ast_abstract_node_set_node_type (GherkinAstAbstractNode* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_return_if_fail (self != NULL);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp0_ = value;
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_g_free0 (self->priv->_node_type);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	self->priv->_node_type = _tmp1_;
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_object_notify ((GObject *) self, "node-type");
#line 1144 "Node.c"
}


GherkinAstLocation* gherkin_ast_abstract_node_get_location (GherkinAstAbstractNode* self) {
	GherkinAstLocation* result;
	GherkinAstLocation* _tmp0_ = NULL;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp0_ = self->priv->_location;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	result = _tmp0_;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	return result;
#line 1159 "Node.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	return self ? g_object_ref (self) : NULL;
#line 1166 "Node.c"
}


void gherkin_ast_abstract_node_set_location (GherkinAstAbstractNode* self, GherkinAstLocation* value) {
	GherkinAstLocation* _tmp0_ = NULL;
	GherkinAstLocation* _tmp1_ = NULL;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_return_if_fail (self != NULL);
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp0_ = value;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_g_object_unref0 (self->priv->_location);
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	self->priv->_location = _tmp1_;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_object_notify ((GObject *) self, "location");
#line 1185 "Node.c"
}


static void gherkin_ast_abstract_node_class_init (GherkinAstAbstractNodeClass * klass) {
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	gherkin_ast_abstract_node_parent_class = g_type_class_peek_parent (klass);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_type_class_add_private (klass, sizeof (GherkinAstAbstractNodePrivate));
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	((GherkinAstAbstractNodeClass *) klass)->serialize_property = gherkin_ast_abstract_node_real_serialize_property;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	((GherkinAstAbstractNodeClass *) klass)->deserialize_property = gherkin_ast_abstract_node_real_deserialize_property;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_gherkin_ast_abstract_node_get_property;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_gherkin_ast_abstract_node_set_property;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	G_OBJECT_CLASS (klass)->finalize = gherkin_ast_abstract_node_finalize;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), GHERKIN_AST_ABSTRACT_NODE_NODE_TYPE, g_param_spec_string ("node-type", "node-type", "node-type", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), GHERKIN_AST_ABSTRACT_NODE_LOCATION, g_param_spec_object ("location", "location", "location", GHERKIN_AST_TYPE_LOCATION, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 1208 "Node.c"
}


static void gherkin_ast_abstract_node_json_serializable_interface_init (JsonSerializableIface * iface) {
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	gherkin_ast_abstract_node_json_serializable_parent_iface = g_type_interface_peek_parent (iface);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	iface->serialize_property = (JsonNode* (*)(JsonSerializable*, const gchar*, GValue*, GParamSpec*)) gherkin_ast_abstract_node_serialize_property;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	iface->deserialize_property = (gboolean (*)(JsonSerializable*, const gchar*, GValue*, GParamSpec*, JsonNode*)) gherkin_ast_abstract_node_deserialize_property;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	iface->find_property = (GParamSpec* (*)(JsonSerializable*, const gchar*)) gherkin_ast_abstract_node_real_find_property;
#line 1221 "Node.c"
}


static void gherkin_ast_abstract_node_instance_init (GherkinAstAbstractNode * self) {
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	self->priv = GHERKIN_AST_ABSTRACT_NODE_GET_PRIVATE (self);
#line 1228 "Node.c"
}


static void gherkin_ast_abstract_node_finalize (GObject* obj) {
	GherkinAstAbstractNode * self;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNode);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_g_free0 (self->priv->_node_type);
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	_g_object_unref0 (self->priv->_location);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	G_OBJECT_CLASS (gherkin_ast_abstract_node_parent_class)->finalize (obj);
#line 1242 "Node.c"
}


GType gherkin_ast_abstract_node_get_type (void) {
	static volatile gsize gherkin_ast_abstract_node_type_id__volatile = 0;
	if (g_once_init_enter (&gherkin_ast_abstract_node_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GherkinAstAbstractNodeClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gherkin_ast_abstract_node_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GherkinAstAbstractNode), 0, (GInstanceInitFunc) gherkin_ast_abstract_node_instance_init, NULL };
		static const GInterfaceInfo json_serializable_info = { (GInterfaceInitFunc) gherkin_ast_abstract_node_json_serializable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType gherkin_ast_abstract_node_type_id;
		gherkin_ast_abstract_node_type_id = g_type_register_static (G_TYPE_OBJECT, "GherkinAstAbstractNode", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_type_add_interface_static (gherkin_ast_abstract_node_type_id, json_serializable_get_type (), &json_serializable_info);
		g_once_init_leave (&gherkin_ast_abstract_node_type_id__volatile, gherkin_ast_abstract_node_type_id);
	}
	return gherkin_ast_abstract_node_type_id__volatile;
}


static void _vala_gherkin_ast_abstract_node_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GherkinAstAbstractNode * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNode);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	switch (property_id) {
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		case GHERKIN_AST_ABSTRACT_NODE_NODE_TYPE:
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		g_value_set_string (value, gherkin_ast_abstract_node_get_node_type (self));
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		break;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		case GHERKIN_AST_ABSTRACT_NODE_LOCATION:
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		g_value_set_object (value, gherkin_ast_abstract_node_get_location (self));
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		break;
#line 1277 "Node.c"
		default:
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		break;
#line 1283 "Node.c"
	}
}


static void _vala_gherkin_ast_abstract_node_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GherkinAstAbstractNode * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNode);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
	switch (property_id) {
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		case GHERKIN_AST_ABSTRACT_NODE_NODE_TYPE:
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		gherkin_ast_abstract_node_set_node_type (self, g_value_get_string (value));
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		break;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		case GHERKIN_AST_ABSTRACT_NODE_LOCATION:
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		gherkin_ast_abstract_node_set_location (self, g_value_get_object (value));
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		break;
#line 1305 "Node.c"
		default:
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Node.vala"
		break;
#line 1311 "Node.c"
	}
}



