/* Scenario.c generated by valac 0.30.0, the Vala compiler
 * generated from Scenario.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <json-glib/json-glib.h>
#include <json-glib/json-gobject.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>


#define GHERKIN_AST_TYPE_ABSTRACT_NODE (gherkin_ast_abstract_node_get_type ())
#define GHERKIN_AST_ABSTRACT_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNode))
#define GHERKIN_AST_ABSTRACT_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNodeClass))
#define GHERKIN_AST_IS_ABSTRACT_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_ABSTRACT_NODE))
#define GHERKIN_AST_IS_ABSTRACT_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_ABSTRACT_NODE))
#define GHERKIN_AST_ABSTRACT_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNodeClass))

typedef struct _GherkinAstAbstractNode GherkinAstAbstractNode;
typedef struct _GherkinAstAbstractNodeClass GherkinAstAbstractNodeClass;
typedef struct _GherkinAstAbstractNodePrivate GherkinAstAbstractNodePrivate;

#define GHERKIN_AST_TYPE_SCENARIO_DEFINITION (gherkin_ast_scenario_definition_get_type ())
#define GHERKIN_AST_SCENARIO_DEFINITION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_SCENARIO_DEFINITION, GherkinAstScenarioDefinition))
#define GHERKIN_AST_SCENARIO_DEFINITION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_SCENARIO_DEFINITION, GherkinAstScenarioDefinitionClass))
#define GHERKIN_AST_IS_SCENARIO_DEFINITION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_SCENARIO_DEFINITION))
#define GHERKIN_AST_IS_SCENARIO_DEFINITION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_SCENARIO_DEFINITION))
#define GHERKIN_AST_SCENARIO_DEFINITION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_SCENARIO_DEFINITION, GherkinAstScenarioDefinitionClass))

typedef struct _GherkinAstScenarioDefinition GherkinAstScenarioDefinition;
typedef struct _GherkinAstScenarioDefinitionClass GherkinAstScenarioDefinitionClass;
typedef struct _GherkinAstScenarioDefinitionPrivate GherkinAstScenarioDefinitionPrivate;

#define GHERKIN_AST_TYPE_SCENARIO (gherkin_ast_scenario_get_type ())
#define GHERKIN_AST_SCENARIO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_SCENARIO, GherkinAstScenario))
#define GHERKIN_AST_SCENARIO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_SCENARIO, GherkinAstScenarioClass))
#define GHERKIN_AST_IS_SCENARIO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_SCENARIO))
#define GHERKIN_AST_IS_SCENARIO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_SCENARIO))
#define GHERKIN_AST_SCENARIO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_SCENARIO, GherkinAstScenarioClass))

typedef struct _GherkinAstScenario GherkinAstScenario;
typedef struct _GherkinAstScenarioClass GherkinAstScenarioClass;
typedef struct _GherkinAstScenarioPrivate GherkinAstScenarioPrivate;

#define GHERKIN_AST_TYPE_TAG (gherkin_ast_tag_get_type ())
#define GHERKIN_AST_TAG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_TAG, GherkinAstTag))
#define GHERKIN_AST_TAG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_TAG, GherkinAstTagClass))
#define GHERKIN_AST_IS_TAG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_TAG))
#define GHERKIN_AST_IS_TAG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_TAG))
#define GHERKIN_AST_TAG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_TAG, GherkinAstTagClass))

typedef struct _GherkinAstTag GherkinAstTag;
typedef struct _GherkinAstTagClass GherkinAstTagClass;

#define GHERKIN_AST_TYPE_LOCATION (gherkin_ast_location_get_type ())
#define GHERKIN_AST_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocation))
#define GHERKIN_AST_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocationClass))
#define GHERKIN_AST_IS_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_LOCATION))
#define GHERKIN_AST_IS_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_LOCATION))
#define GHERKIN_AST_LOCATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocationClass))

typedef struct _GherkinAstLocation GherkinAstLocation;
typedef struct _GherkinAstLocationClass GherkinAstLocationClass;

#define GHERKIN_AST_TYPE_STEP (gherkin_ast_step_get_type ())
#define GHERKIN_AST_STEP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_STEP, GherkinAstStep))
#define GHERKIN_AST_STEP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_STEP, GherkinAstStepClass))
#define GHERKIN_AST_IS_STEP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_STEP))
#define GHERKIN_AST_IS_STEP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_STEP))
#define GHERKIN_AST_STEP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_STEP, GherkinAstStepClass))

typedef struct _GherkinAstStep GherkinAstStep;
typedef struct _GherkinAstStepClass GherkinAstStepClass;

struct _GherkinAstAbstractNode {
	GObject parent_instance;
	GherkinAstAbstractNodePrivate * priv;
};

struct _GherkinAstAbstractNodeClass {
	GObjectClass parent_class;
	JsonNode* (*serialize_property) (GherkinAstAbstractNode* self, const gchar* property_name, GValue* value, GParamSpec* pspec);
	gboolean (*deserialize_property) (GherkinAstAbstractNode* self, const gchar* property_name, GValue* value, GParamSpec* pspec, JsonNode* property_node);
};

struct _GherkinAstScenarioDefinition {
	GherkinAstAbstractNode parent_instance;
	GherkinAstScenarioDefinitionPrivate * priv;
};

struct _GherkinAstScenarioDefinitionClass {
	GherkinAstAbstractNodeClass parent_class;
};

struct _GherkinAstScenario {
	GherkinAstScenarioDefinition parent_instance;
	GherkinAstScenarioPrivate * priv;
};

struct _GherkinAstScenarioClass {
	GherkinAstScenarioDefinitionClass parent_class;
};


static gpointer gherkin_ast_scenario_parent_class = NULL;

GType gherkin_ast_abstract_node_get_type (void) G_GNUC_CONST;
GType gherkin_ast_scenario_definition_get_type (void) G_GNUC_CONST;
GType gherkin_ast_scenario_get_type (void) G_GNUC_CONST;
enum  {
	GHERKIN_AST_SCENARIO_DUMMY_PROPERTY
};
GType gherkin_ast_tag_get_type (void) G_GNUC_CONST;
GType gherkin_ast_location_get_type (void) G_GNUC_CONST;
GType gherkin_ast_step_get_type (void) G_GNUC_CONST;
GherkinAstScenario* gherkin_ast_scenario_new (GeeArrayList* tags, GherkinAstLocation* location, const gchar* keyword, const gchar* name, const gchar* description, GeeArrayList* steps);
GherkinAstScenario* gherkin_ast_scenario_construct (GType object_type, GeeArrayList* tags, GherkinAstLocation* location, const gchar* keyword, const gchar* name, const gchar* description, GeeArrayList* steps);
GherkinAstScenarioDefinition* gherkin_ast_scenario_definition_construct (GType object_type, GeeArrayList* tags, GherkinAstLocation* location, const gchar* keyword, const gchar* name, const gchar* description, GeeArrayList* steps);


GherkinAstScenario* gherkin_ast_scenario_construct (GType object_type, GeeArrayList* tags, GherkinAstLocation* location, const gchar* keyword, const gchar* name, const gchar* description, GeeArrayList* steps) {
	GherkinAstScenario * self = NULL;
	GeeArrayList* _tmp0_ = NULL;
	GherkinAstLocation* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	GeeArrayList* _tmp5_ = NULL;
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Scenario.vala"
	g_return_val_if_fail (tags != NULL, NULL);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Scenario.vala"
	g_return_val_if_fail (location != NULL, NULL);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Scenario.vala"
	g_return_val_if_fail (keyword != NULL, NULL);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Scenario.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Scenario.vala"
	g_return_val_if_fail (steps != NULL, NULL);
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Scenario.vala"
	_tmp0_ = tags;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Scenario.vala"
	_tmp1_ = location;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Scenario.vala"
	_tmp2_ = keyword;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Scenario.vala"
	_tmp3_ = name;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Scenario.vala"
	_tmp4_ = description;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Scenario.vala"
	_tmp5_ = steps;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Scenario.vala"
	self = (GherkinAstScenario*) gherkin_ast_scenario_definition_construct (object_type, _tmp0_, _tmp1_, _tmp2_, _tmp3_, _tmp4_, _tmp5_);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Scenario.vala"
	return self;
#line 158 "Scenario.c"
}


GherkinAstScenario* gherkin_ast_scenario_new (GeeArrayList* tags, GherkinAstLocation* location, const gchar* keyword, const gchar* name, const gchar* description, GeeArrayList* steps) {
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Scenario.vala"
	return gherkin_ast_scenario_construct (GHERKIN_AST_TYPE_SCENARIO, tags, location, keyword, name, description, steps);
#line 165 "Scenario.c"
}


static void gherkin_ast_scenario_class_init (GherkinAstScenarioClass * klass) {
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Scenario.vala"
	gherkin_ast_scenario_parent_class = g_type_class_peek_parent (klass);
#line 172 "Scenario.c"
}


static void gherkin_ast_scenario_instance_init (GherkinAstScenario * self) {
}


GType gherkin_ast_scenario_get_type (void) {
	static volatile gsize gherkin_ast_scenario_type_id__volatile = 0;
	if (g_once_init_enter (&gherkin_ast_scenario_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GherkinAstScenarioClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gherkin_ast_scenario_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GherkinAstScenario), 0, (GInstanceInitFunc) gherkin_ast_scenario_instance_init, NULL };
		GType gherkin_ast_scenario_type_id;
		gherkin_ast_scenario_type_id = g_type_register_static (GHERKIN_AST_TYPE_SCENARIO_DEFINITION, "GherkinAstScenario", &g_define_type_info, 0);
		g_once_init_leave (&gherkin_ast_scenario_type_id__volatile, gherkin_ast_scenario_type_id);
	}
	return gherkin_ast_scenario_type_id__volatile;
}



