/* Tag.c generated by valac 0.30.0, the Vala compiler
 * generated from Tag.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <json-glib/json-glib.h>
#include <json-glib/json-gobject.h>
#include <stdlib.h>
#include <string.h>


#define GHERKIN_AST_TYPE_ABSTRACT_NODE (gherkin_ast_abstract_node_get_type ())
#define GHERKIN_AST_ABSTRACT_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNode))
#define GHERKIN_AST_ABSTRACT_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNodeClass))
#define GHERKIN_AST_IS_ABSTRACT_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_ABSTRACT_NODE))
#define GHERKIN_AST_IS_ABSTRACT_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_ABSTRACT_NODE))
#define GHERKIN_AST_ABSTRACT_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_ABSTRACT_NODE, GherkinAstAbstractNodeClass))

typedef struct _GherkinAstAbstractNode GherkinAstAbstractNode;
typedef struct _GherkinAstAbstractNodeClass GherkinAstAbstractNodeClass;
typedef struct _GherkinAstAbstractNodePrivate GherkinAstAbstractNodePrivate;

#define GHERKIN_AST_TYPE_TAG (gherkin_ast_tag_get_type ())
#define GHERKIN_AST_TAG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_TAG, GherkinAstTag))
#define GHERKIN_AST_TAG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_TAG, GherkinAstTagClass))
#define GHERKIN_AST_IS_TAG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_TAG))
#define GHERKIN_AST_IS_TAG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_TAG))
#define GHERKIN_AST_TAG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_TAG, GherkinAstTagClass))

typedef struct _GherkinAstTag GherkinAstTag;
typedef struct _GherkinAstTagClass GherkinAstTagClass;
typedef struct _GherkinAstTagPrivate GherkinAstTagPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

#define GHERKIN_AST_TYPE_LOCATION (gherkin_ast_location_get_type ())
#define GHERKIN_AST_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocation))
#define GHERKIN_AST_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocationClass))
#define GHERKIN_AST_IS_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_LOCATION))
#define GHERKIN_AST_IS_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_LOCATION))
#define GHERKIN_AST_LOCATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocationClass))

typedef struct _GherkinAstLocation GherkinAstLocation;
typedef struct _GherkinAstLocationClass GherkinAstLocationClass;

struct _GherkinAstAbstractNode {
	GObject parent_instance;
	GherkinAstAbstractNodePrivate * priv;
};

struct _GherkinAstAbstractNodeClass {
	GObjectClass parent_class;
	JsonNode* (*serialize_property) (GherkinAstAbstractNode* self, const gchar* property_name, GValue* value, GParamSpec* pspec);
	gboolean (*deserialize_property) (GherkinAstAbstractNode* self, const gchar* property_name, GValue* value, GParamSpec* pspec, JsonNode* property_node);
};

struct _GherkinAstTag {
	GherkinAstAbstractNode parent_instance;
	GherkinAstTagPrivate * priv;
};

struct _GherkinAstTagClass {
	GherkinAstAbstractNodeClass parent_class;
};

struct _GherkinAstTagPrivate {
	gchar* _name;
};


static gpointer gherkin_ast_tag_parent_class = NULL;

GType gherkin_ast_abstract_node_get_type (void) G_GNUC_CONST;
GType gherkin_ast_tag_get_type (void) G_GNUC_CONST;
#define GHERKIN_AST_TAG_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GHERKIN_AST_TYPE_TAG, GherkinAstTagPrivate))
enum  {
	GHERKIN_AST_TAG_DUMMY_PROPERTY,
	GHERKIN_AST_TAG_NAME
};
GType gherkin_ast_location_get_type (void) G_GNUC_CONST;
GherkinAstTag* gherkin_ast_tag_new (GherkinAstLocation* location, const gchar* name);
GherkinAstTag* gherkin_ast_tag_construct (GType object_type, GherkinAstLocation* location, const gchar* name);
GherkinAstAbstractNode* gherkin_ast_abstract_node_construct (GType object_type, GherkinAstLocation* location);
void gherkin_ast_tag_set_name (GherkinAstTag* self, const gchar* value);
const gchar* gherkin_ast_tag_get_name (GherkinAstTag* self);
static void gherkin_ast_tag_finalize (GObject* obj);
static void _vala_gherkin_ast_tag_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_gherkin_ast_tag_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


GherkinAstTag* gherkin_ast_tag_construct (GType object_type, GherkinAstLocation* location, const gchar* name) {
	GherkinAstTag * self = NULL;
	GherkinAstLocation* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	g_return_val_if_fail (location != NULL, NULL);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	_tmp0_ = location;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	self = (GherkinAstTag*) gherkin_ast_abstract_node_construct (object_type, _tmp0_);
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	_tmp1_ = name;
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	gherkin_ast_tag_set_name (self, _tmp1_);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	return self;
#line 110 "Tag.c"
}


GherkinAstTag* gherkin_ast_tag_new (GherkinAstLocation* location, const gchar* name) {
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	return gherkin_ast_tag_construct (GHERKIN_AST_TYPE_TAG, location, name);
#line 117 "Tag.c"
}


const gchar* gherkin_ast_tag_get_name (GherkinAstTag* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	_tmp0_ = self->priv->_name;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	result = _tmp0_;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	return result;
#line 132 "Tag.c"
}


void gherkin_ast_tag_set_name (GherkinAstTag* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	g_return_if_fail (self != NULL);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	_tmp0_ = value;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	_g_free0 (self->priv->_name);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	self->priv->_name = _tmp1_;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	g_object_notify ((GObject *) self, "name");
#line 151 "Tag.c"
}


static void gherkin_ast_tag_class_init (GherkinAstTagClass * klass) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	gherkin_ast_tag_parent_class = g_type_class_peek_parent (klass);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	g_type_class_add_private (klass, sizeof (GherkinAstTagPrivate));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_gherkin_ast_tag_get_property;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_gherkin_ast_tag_set_property;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	G_OBJECT_CLASS (klass)->finalize = gherkin_ast_tag_finalize;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), GHERKIN_AST_TAG_NAME, g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 168 "Tag.c"
}


static void gherkin_ast_tag_instance_init (GherkinAstTag * self) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	self->priv = GHERKIN_AST_TAG_GET_PRIVATE (self);
#line 175 "Tag.c"
}


static void gherkin_ast_tag_finalize (GObject* obj) {
	GherkinAstTag * self;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GHERKIN_AST_TYPE_TAG, GherkinAstTag);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	_g_free0 (self->priv->_name);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	G_OBJECT_CLASS (gherkin_ast_tag_parent_class)->finalize (obj);
#line 187 "Tag.c"
}


GType gherkin_ast_tag_get_type (void) {
	static volatile gsize gherkin_ast_tag_type_id__volatile = 0;
	if (g_once_init_enter (&gherkin_ast_tag_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GherkinAstTagClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gherkin_ast_tag_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GherkinAstTag), 0, (GInstanceInitFunc) gherkin_ast_tag_instance_init, NULL };
		GType gherkin_ast_tag_type_id;
		gherkin_ast_tag_type_id = g_type_register_static (GHERKIN_AST_TYPE_ABSTRACT_NODE, "GherkinAstTag", &g_define_type_info, 0);
		g_once_init_leave (&gherkin_ast_tag_type_id__volatile, gherkin_ast_tag_type_id);
	}
	return gherkin_ast_tag_type_id__volatile;
}


static void _vala_gherkin_ast_tag_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GherkinAstTag * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GHERKIN_AST_TYPE_TAG, GherkinAstTag);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	switch (property_id) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
		case GHERKIN_AST_TAG_NAME:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
		g_value_set_string (value, gherkin_ast_tag_get_name (self));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
		break;
#line 214 "Tag.c"
		default:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
		break;
#line 220 "Tag.c"
	}
}


static void _vala_gherkin_ast_tag_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GherkinAstTag * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GHERKIN_AST_TYPE_TAG, GherkinAstTag);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
	switch (property_id) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
		case GHERKIN_AST_TAG_NAME:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
		gherkin_ast_tag_set_name (self, g_value_get_string (value));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
		break;
#line 236 "Tag.c"
		default:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/ast/Tag.vala"
		break;
#line 242 "Tag.c"
	}
}



