/* AstNode.c generated by valac 0.30.0, the Vala compiler
 * generated from AstNode.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>


#define GHERKIN_TYPE_AST_NODE (gherkin_ast_node_get_type ())
#define GHERKIN_AST_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_TYPE_AST_NODE, GherkinAstNode))
#define GHERKIN_AST_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_TYPE_AST_NODE, GherkinAstNodeClass))
#define GHERKIN_IS_AST_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_TYPE_AST_NODE))
#define GHERKIN_IS_AST_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_TYPE_AST_NODE))
#define GHERKIN_AST_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_TYPE_AST_NODE, GherkinAstNodeClass))

typedef struct _GherkinAstNode GherkinAstNode;
typedef struct _GherkinAstNodeClass GherkinAstNodeClass;
typedef struct _GherkinAstNodePrivate GherkinAstNodePrivate;

#define GHERKIN_PARSER_TYPE_RULE_TYPE (gherkin_parser_rule_type_get_type ())
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _t_destroy_func0(var) (((var == NULL) || (t_destroy_func == NULL)) ? NULL : (var = (t_destroy_func (var), NULL)))

#define GHERKIN_PARSER_TYPE_TOKEN_TYPE (gherkin_parser_token_type_get_type ())

#define GHERKIN_TYPE_TOKEN (gherkin_token_get_type ())
#define GHERKIN_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_TYPE_TOKEN, GherkinToken))
#define GHERKIN_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_TYPE_TOKEN, GherkinTokenClass))
#define GHERKIN_IS_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_TYPE_TOKEN))
#define GHERKIN_IS_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_TYPE_TOKEN))
#define GHERKIN_TOKEN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_TYPE_TOKEN, GherkinTokenClass))

typedef struct _GherkinToken GherkinToken;
typedef struct _GherkinTokenClass GherkinTokenClass;

#define GHERKIN_TYPE_IGHERKIN_LINE (gherkin_igherkin_line_get_type ())
#define GHERKIN_IGHERKIN_LINE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_TYPE_IGHERKIN_LINE, GherkinIGherkinLine))
#define GHERKIN_IS_IGHERKIN_LINE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_TYPE_IGHERKIN_LINE))
#define GHERKIN_IGHERKIN_LINE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), GHERKIN_TYPE_IGHERKIN_LINE, GherkinIGherkinLineIface))

typedef struct _GherkinIGherkinLine GherkinIGherkinLine;
typedef struct _GherkinIGherkinLineIface GherkinIGherkinLineIface;

#define GHERKIN_TYPE_GHERKIN_LINE_SPAN (gherkin_gherkin_line_span_get_type ())
#define GHERKIN_GHERKIN_LINE_SPAN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_TYPE_GHERKIN_LINE_SPAN, GherkinGherkinLineSpan))
#define GHERKIN_GHERKIN_LINE_SPAN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_TYPE_GHERKIN_LINE_SPAN, GherkinGherkinLineSpanClass))
#define GHERKIN_IS_GHERKIN_LINE_SPAN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_TYPE_GHERKIN_LINE_SPAN))
#define GHERKIN_IS_GHERKIN_LINE_SPAN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_TYPE_GHERKIN_LINE_SPAN))
#define GHERKIN_GHERKIN_LINE_SPAN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_TYPE_GHERKIN_LINE_SPAN, GherkinGherkinLineSpanClass))

typedef struct _GherkinGherkinLineSpan GherkinGherkinLineSpan;
typedef struct _GherkinGherkinLineSpanClass GherkinGherkinLineSpanClass;

#define GHERKIN_AST_TYPE_LOCATION (gherkin_ast_location_get_type ())
#define GHERKIN_AST_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocation))
#define GHERKIN_AST_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocationClass))
#define GHERKIN_AST_IS_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_LOCATION))
#define GHERKIN_AST_IS_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_LOCATION))
#define GHERKIN_AST_LOCATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocationClass))

typedef struct _GherkinAstLocation GherkinAstLocation;
typedef struct _GherkinAstLocationClass GherkinAstLocationClass;

typedef enum  {
	GHERKIN_PARSER_RULE_TYPE_None,
	GHERKIN_PARSER_RULE_TYPE__EOF,
	GHERKIN_PARSER_RULE_TYPE__Empty,
	GHERKIN_PARSER_RULE_TYPE__Comment,
	GHERKIN_PARSER_RULE_TYPE__TagLine,
	GHERKIN_PARSER_RULE_TYPE__FeatureLine,
	GHERKIN_PARSER_RULE_TYPE__BackgroundLine,
	GHERKIN_PARSER_RULE_TYPE__ScenarioLine,
	GHERKIN_PARSER_RULE_TYPE__ScenarioOutlineLine,
	GHERKIN_PARSER_RULE_TYPE__ExamplesLine,
	GHERKIN_PARSER_RULE_TYPE__StepLine,
	GHERKIN_PARSER_RULE_TYPE__DocStringSeparator,
	GHERKIN_PARSER_RULE_TYPE__TableRow,
	GHERKIN_PARSER_RULE_TYPE__Language,
	GHERKIN_PARSER_RULE_TYPE__Other,
	GHERKIN_PARSER_RULE_TYPE_Feature,
	GHERKIN_PARSER_RULE_TYPE_Feature_Header,
	GHERKIN_PARSER_RULE_TYPE_Background,
	GHERKIN_PARSER_RULE_TYPE_Scenario_Definition,
	GHERKIN_PARSER_RULE_TYPE_Scenario,
	GHERKIN_PARSER_RULE_TYPE_ScenarioOutline,
	GHERKIN_PARSER_RULE_TYPE_Examples_Definition,
	GHERKIN_PARSER_RULE_TYPE_Examples,
	GHERKIN_PARSER_RULE_TYPE_Scenario_Step,
	GHERKIN_PARSER_RULE_TYPE_ScenarioOutline_Step,
	GHERKIN_PARSER_RULE_TYPE_Step,
	GHERKIN_PARSER_RULE_TYPE_Step_Arg,
	GHERKIN_PARSER_RULE_TYPE_DataTable,
	GHERKIN_PARSER_RULE_TYPE_DocString,
	GHERKIN_PARSER_RULE_TYPE_Tags,
	GHERKIN_PARSER_RULE_TYPE_Feature_Description,
	GHERKIN_PARSER_RULE_TYPE_Background_Description,
	GHERKIN_PARSER_RULE_TYPE_Scenario_Description,
	GHERKIN_PARSER_RULE_TYPE_ScenarioOutline_Description,
	GHERKIN_PARSER_RULE_TYPE_Examples_Description,
	GHERKIN_PARSER_RULE_TYPE_Description_Helper,
	GHERKIN_PARSER_RULE_TYPE_Description
} GherkinParserRuleType;

struct _GherkinAstNode {
	GObject parent_instance;
	GherkinAstNodePrivate * priv;
	GherkinParserRuleType ruleType;
};

struct _GherkinAstNodeClass {
	GObjectClass parent_class;
};

struct _GherkinAstNodePrivate {
	GeeHashMap* subItems;
};

typedef enum  {
	GHERKIN_PARSER_TOKEN_TYPE_None,
	GHERKIN_PARSER_TOKEN_TYPE_EOF,
	GHERKIN_PARSER_TOKEN_TYPE_Empty,
	GHERKIN_PARSER_TOKEN_TYPE_Comment,
	GHERKIN_PARSER_TOKEN_TYPE_TagLine,
	GHERKIN_PARSER_TOKEN_TYPE_FeatureLine,
	GHERKIN_PARSER_TOKEN_TYPE_BackgroundLine,
	GHERKIN_PARSER_TOKEN_TYPE_ScenarioLine,
	GHERKIN_PARSER_TOKEN_TYPE_ScenarioOutlineLine,
	GHERKIN_PARSER_TOKEN_TYPE_ExamplesLine,
	GHERKIN_PARSER_TOKEN_TYPE_StepLine,
	GHERKIN_PARSER_TOKEN_TYPE_DocStringSeparator,
	GHERKIN_PARSER_TOKEN_TYPE_TableRow,
	GHERKIN_PARSER_TOKEN_TYPE_Language,
	GHERKIN_PARSER_TOKEN_TYPE_Other
} GherkinParserTokenType;

struct _GherkinIGherkinLineIface {
	GTypeInterface parent_iface;
	gint (*indent) (GherkinIGherkinLine* self);
	void (*detach) (GherkinIGherkinLine* self);
	gchar* (*get_line_text) (GherkinIGherkinLine* self, gint indentToRemove);
	gboolean (*is_empty) (GherkinIGherkinLine* self);
	gboolean (*starts_with) (GherkinIGherkinLine* self, const gchar* prefix);
	gchar* (*get_rest_trimmed) (GherkinIGherkinLine* self, gint length);
	GeeArrayList* (*get_tags) (GherkinIGherkinLine* self);
	gboolean (*starts_with_title_keyword) (GherkinIGherkinLine* self, const gchar* keyword);
	GeeArrayList* (*get_table_cells) (GherkinIGherkinLine* self);
};


static gpointer gherkin_ast_node_parent_class = NULL;

GType gherkin_ast_node_get_type (void) G_GNUC_CONST;
GType gherkin_parser_rule_type_get_type (void) G_GNUC_CONST;
#define GHERKIN_AST_NODE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GHERKIN_TYPE_AST_NODE, GherkinAstNodePrivate))
enum  {
	GHERKIN_AST_NODE_DUMMY_PROPERTY
};
GherkinAstNode* gherkin_ast_node_new (GherkinParserRuleType ruleType);
GherkinAstNode* gherkin_ast_node_construct (GType object_type, GherkinParserRuleType ruleType);
void gherkin_ast_node_add (GherkinAstNode* self, GherkinParserRuleType ruleType, GObject* obj);
gpointer gherkin_ast_node_get_single (GherkinAstNode* self, GType t_type, GBoxedCopyFunc t_dup_func, GDestroyNotify t_destroy_func, GherkinParserRuleType ruleType, gconstpointer defaultResult);
GeeArrayList* gherkin_ast_node_get_items (GherkinAstNode* self, GType t_type, GBoxedCopyFunc t_dup_func, GDestroyNotify t_destroy_func, GherkinParserRuleType ruleType);
GType gherkin_parser_token_type_get_type (void) G_GNUC_CONST;
GType gherkin_token_get_type (void) G_GNUC_CONST;
GherkinToken* gherkin_ast_node_get_token (GherkinAstNode* self, GherkinParserTokenType tokenType);
GType gherkin_gherkin_line_span_get_type (void) G_GNUC_CONST;
GType gherkin_igherkin_line_get_type (void) G_GNUC_CONST;
GType gherkin_ast_location_get_type (void) G_GNUC_CONST;
GherkinToken* gherkin_token_new (GherkinIGherkinLine* line, GherkinAstLocation* location);
GherkinToken* gherkin_token_construct (GType object_type, GherkinIGherkinLine* line, GherkinAstLocation* location);
GeeArrayList* gherkin_ast_node_get_tokens (GherkinAstNode* self, GherkinParserTokenType tokenType);
static void gherkin_ast_node_finalize (GObject* obj);


GherkinAstNode* gherkin_ast_node_construct (GType object_type, GherkinParserRuleType ruleType) {
	GherkinAstNode * self = NULL;
	GherkinParserRuleType _tmp0_ = 0;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	self = (GherkinAstNode*) g_object_new (object_type, NULL);
#line 10 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp0_ = ruleType;
#line 10 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	self->ruleType = _tmp0_;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	return self;
#line 190 "AstNode.c"
}


GherkinAstNode* gherkin_ast_node_new (GherkinParserRuleType ruleType) {
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	return gherkin_ast_node_construct (GHERKIN_TYPE_AST_NODE, ruleType);
#line 197 "AstNode.c"
}


void gherkin_ast_node_add (GherkinAstNode* self, GherkinParserRuleType ruleType, GObject* obj) {
	GeeArrayList* items = NULL;
	GeeHashMap* _tmp0_ = NULL;
	GherkinParserRuleType _tmp1_ = 0;
	gpointer _tmp2_ = NULL;
	GeeArrayList* _tmp3_ = NULL;
	GeeArrayList* _tmp8_ = NULL;
	GObject* _tmp9_ = NULL;
#line 13 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	g_return_if_fail (self != NULL);
#line 13 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	g_return_if_fail (obj != NULL);
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp0_ = self->priv->subItems;
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp1_ = ruleType;
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp2_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp0_, (gpointer) ((gintptr) _tmp1_));
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	items = (GeeArrayList*) _tmp2_;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp3_ = items;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	if (_tmp3_ == NULL) {
#line 225 "AstNode.c"
		GeeArrayList* _tmp4_ = NULL;
		GeeHashMap* _tmp5_ = NULL;
		GherkinParserRuleType _tmp6_ = 0;
		GeeArrayList* _tmp7_ = NULL;
#line 16 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
		_tmp4_ = gee_array_list_new (G_TYPE_OBJECT, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
#line 16 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
		_g_object_unref0 (items);
#line 16 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
		items = _tmp4_;
#line 17 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
		_tmp5_ = self->priv->subItems;
#line 17 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
		_tmp6_ = ruleType;
#line 17 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
		_tmp7_ = items;
#line 17 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
		gee_abstract_map_set ((GeeAbstractMap*) _tmp5_, (gpointer) ((gintptr) _tmp6_), _tmp7_);
#line 244 "AstNode.c"
	}
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp8_ = items;
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp9_ = obj;
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp8_, _tmp9_);
#line 13 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_g_object_unref0 (items);
#line 254 "AstNode.c"
}


gpointer gherkin_ast_node_get_single (GherkinAstNode* self, GType t_type, GBoxedCopyFunc t_dup_func, GDestroyNotify t_destroy_func, GherkinParserRuleType ruleType, gconstpointer defaultResult) {
	gpointer result = NULL;
	GeeArrayList* items = NULL;
	GherkinParserRuleType _tmp0_ = 0;
	GeeArrayList* _tmp1_ = NULL;
	gpointer _tmp2_ = NULL;
	GeeArrayList* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	gboolean _tmp5_ = FALSE;
	gpointer _tmp10_ = NULL;
#line 22 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp0_ = ruleType;
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp1_ = gherkin_ast_node_get_items (self, G_TYPE_OBJECT, (GBoxedCopyFunc) g_object_ref, g_object_unref, _tmp0_);
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	items = _tmp1_;
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp3_ = items;
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp4_ = gee_collection_get_is_empty ((GeeCollection*) _tmp3_);
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp5_ = _tmp4_;
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	if (_tmp5_) {
#line 284 "AstNode.c"
		gconstpointer _tmp6_ = NULL;
		gpointer _tmp7_ = NULL;
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
		_tmp6_ = defaultResult;
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
		_tmp7_ = ((_tmp6_ != NULL) && (t_dup_func != NULL)) ? t_dup_func ((gpointer) _tmp6_) : ((gpointer) _tmp6_);
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
		_t_destroy_func0 (_tmp2_);
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
		_tmp2_ = _tmp7_;
#line 295 "AstNode.c"
	} else {
		GeeArrayList* _tmp8_ = NULL;
		gpointer _tmp9_ = NULL;
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
		_tmp8_ = items;
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
		_tmp9_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, 0);
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
		_t_destroy_func0 (_tmp2_);
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
		_tmp2_ = (GObject*) _tmp9_;
#line 307 "AstNode.c"
	}
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp10_ = ((((gconstpointer) _tmp2_) != NULL) && (t_dup_func != NULL)) ? t_dup_func ((gpointer) ((gconstpointer) _tmp2_)) : ((gpointer) ((gconstpointer) _tmp2_));
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	result = _tmp10_;
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_t_destroy_func0 (_tmp2_);
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_g_object_unref0 (items);
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	return result;
#line 319 "AstNode.c"
}


GeeArrayList* gherkin_ast_node_get_items (GherkinAstNode* self, GType t_type, GBoxedCopyFunc t_dup_func, GDestroyNotify t_destroy_func, GherkinParserRuleType ruleType) {
	GeeArrayList* result = NULL;
	GeeArrayList* items = NULL;
	GeeHashMap* _tmp0_ = NULL;
	GherkinParserRuleType _tmp1_ = 0;
	gpointer _tmp2_ = NULL;
	GeeArrayList* _tmp3_ = NULL;
#line 27 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 28 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp0_ = self->priv->subItems;
#line 28 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp1_ = ruleType;
#line 28 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp2_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp0_, (gpointer) ((gintptr) _tmp1_));
#line 28 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	items = G_TYPE_CHECK_INSTANCE_CAST ((GeeArrayList*) _tmp2_, GEE_TYPE_ARRAY_LIST, GeeArrayList);
#line 29 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp3_ = items;
#line 29 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	if (_tmp3_ == NULL) {
#line 344 "AstNode.c"
		GeeArrayList* _tmp4_ = NULL;
#line 30 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
		_tmp4_ = gee_array_list_new (t_type, (GBoxedCopyFunc) t_dup_func, t_destroy_func, NULL, NULL, NULL);
#line 30 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
		result = _tmp4_;
#line 30 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
		_g_object_unref0 (items);
#line 30 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
		return result;
#line 354 "AstNode.c"
	}
#line 32 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	result = items;
#line 32 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	return result;
#line 360 "AstNode.c"
}


GherkinToken* gherkin_ast_node_get_token (GherkinAstNode* self, GherkinParserTokenType tokenType) {
	GherkinToken* result = NULL;
	GherkinParserRuleType ruleType = 0;
	GherkinParserTokenType _tmp0_ = 0;
	GherkinToken* _tmp1_ = NULL;
	GherkinToken* _tmp2_ = NULL;
	gpointer _tmp3_ = NULL;
	GherkinToken* _tmp4_ = NULL;
#line 35 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 36 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp0_ = tokenType;
#line 36 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	ruleType = (GherkinParserRuleType) _tmp0_;
#line 37 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp1_ = gherkin_token_new (NULL, NULL);
#line 37 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp2_ = _tmp1_;
#line 37 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp3_ = gherkin_ast_node_get_single (self, GHERKIN_TYPE_TOKEN, (GBoxedCopyFunc) g_object_ref, g_object_unref, ruleType, _tmp2_);
#line 37 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp4_ = (GherkinToken*) _tmp3_;
#line 37 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_g_object_unref0 (_tmp2_);
#line 37 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	result = _tmp4_;
#line 37 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	return result;
#line 392 "AstNode.c"
}


GeeArrayList* gherkin_ast_node_get_tokens (GherkinAstNode* self, GherkinParserTokenType tokenType) {
	GeeArrayList* result = NULL;
	GherkinParserTokenType _tmp0_ = 0;
	GeeArrayList* _tmp1_ = NULL;
#line 40 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 41 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp0_ = tokenType;
#line 41 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp1_ = gherkin_ast_node_get_items (self, GHERKIN_TYPE_TOKEN, (GBoxedCopyFunc) g_object_ref, g_object_unref, (GherkinParserRuleType) _tmp0_);
#line 41 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	result = _tmp1_;
#line 41 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	return result;
#line 410 "AstNode.c"
}


static void gherkin_ast_node_class_init (GherkinAstNodeClass * klass) {
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	gherkin_ast_node_parent_class = g_type_class_peek_parent (klass);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	g_type_class_add_private (klass, sizeof (GherkinAstNodePrivate));
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	G_OBJECT_CLASS (klass)->finalize = gherkin_ast_node_finalize;
#line 421 "AstNode.c"
}


static void gherkin_ast_node_instance_init (GherkinAstNode * self) {
	GeeHashMap* _tmp0_ = NULL;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	self->priv = GHERKIN_AST_NODE_GET_PRIVATE (self);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_tmp0_ = gee_hash_map_new (GHERKIN_PARSER_TYPE_RULE_TYPE, NULL, NULL, GEE_TYPE_ARRAY_LIST, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	self->priv->subItems = _tmp0_;
#line 433 "AstNode.c"
}


static void gherkin_ast_node_finalize (GObject* obj) {
	GherkinAstNode * self;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GHERKIN_TYPE_AST_NODE, GherkinAstNode);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	_g_object_unref0 (self->priv->subItems);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/AstNode.vala"
	G_OBJECT_CLASS (gherkin_ast_node_parent_class)->finalize (obj);
#line 445 "AstNode.c"
}


GType gherkin_ast_node_get_type (void) {
	static volatile gsize gherkin_ast_node_type_id__volatile = 0;
	if (g_once_init_enter (&gherkin_ast_node_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GherkinAstNodeClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gherkin_ast_node_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GherkinAstNode), 0, (GInstanceInitFunc) gherkin_ast_node_instance_init, NULL };
		GType gherkin_ast_node_type_id;
		gherkin_ast_node_type_id = g_type_register_static (G_TYPE_OBJECT, "GherkinAstNode", &g_define_type_info, 0);
		g_once_init_leave (&gherkin_ast_node_type_id__volatile, gherkin_ast_node_type_id);
	}
	return gherkin_ast_node_type_id__volatile;
}



