/* Func.c generated by valac 0.30.0, the Vala compiler
 * generated from Func.vala, do not modify */


#include <glib.h>
#include <glib-object.h>


typedef gpointer (*GherkinFunc) (void* user_data);





