/* IGherkinLine.c generated by valac 0.30.0, the Vala compiler
 * generated from IGherkinLine.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>


#define GHERKIN_TYPE_IGHERKIN_LINE (gherkin_igherkin_line_get_type ())
#define GHERKIN_IGHERKIN_LINE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_TYPE_IGHERKIN_LINE, GherkinIGherkinLine))
#define GHERKIN_IS_IGHERKIN_LINE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_TYPE_IGHERKIN_LINE))
#define GHERKIN_IGHERKIN_LINE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), GHERKIN_TYPE_IGHERKIN_LINE, GherkinIGherkinLineIface))

typedef struct _GherkinIGherkinLine GherkinIGherkinLine;
typedef struct _GherkinIGherkinLineIface GherkinIGherkinLineIface;

#define GHERKIN_TYPE_GHERKIN_LINE_SPAN (gherkin_gherkin_line_span_get_type ())
#define GHERKIN_GHERKIN_LINE_SPAN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_TYPE_GHERKIN_LINE_SPAN, GherkinGherkinLineSpan))
#define GHERKIN_GHERKIN_LINE_SPAN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_TYPE_GHERKIN_LINE_SPAN, GherkinGherkinLineSpanClass))
#define GHERKIN_IS_GHERKIN_LINE_SPAN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_TYPE_GHERKIN_LINE_SPAN))
#define GHERKIN_IS_GHERKIN_LINE_SPAN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_TYPE_GHERKIN_LINE_SPAN))
#define GHERKIN_GHERKIN_LINE_SPAN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_TYPE_GHERKIN_LINE_SPAN, GherkinGherkinLineSpanClass))

typedef struct _GherkinGherkinLineSpan GherkinGherkinLineSpan;
typedef struct _GherkinGherkinLineSpanClass GherkinGherkinLineSpanClass;

struct _GherkinIGherkinLineIface {
	GTypeInterface parent_iface;
	gint (*indent) (GherkinIGherkinLine* self);
	void (*detach) (GherkinIGherkinLine* self);
	gchar* (*get_line_text) (GherkinIGherkinLine* self, gint indentToRemove);
	gboolean (*is_empty) (GherkinIGherkinLine* self);
	gboolean (*starts_with) (GherkinIGherkinLine* self, const gchar* prefix);
	gchar* (*get_rest_trimmed) (GherkinIGherkinLine* self, gint length);
	GeeArrayList* (*get_tags) (GherkinIGherkinLine* self);
	gboolean (*starts_with_title_keyword) (GherkinIGherkinLine* self, const gchar* keyword);
	GeeArrayList* (*get_table_cells) (GherkinIGherkinLine* self);
};



GType gherkin_gherkin_line_span_get_type (void) G_GNUC_CONST;
GType gherkin_igherkin_line_get_type (void) G_GNUC_CONST;
gint gherkin_igherkin_line_indent (GherkinIGherkinLine* self);
void gherkin_igherkin_line_detach (GherkinIGherkinLine* self);
gchar* gherkin_igherkin_line_get_line_text (GherkinIGherkinLine* self, gint indentToRemove);
gboolean gherkin_igherkin_line_is_empty (GherkinIGherkinLine* self);
gboolean gherkin_igherkin_line_starts_with (GherkinIGherkinLine* self, const gchar* prefix);
gchar* gherkin_igherkin_line_get_rest_trimmed (GherkinIGherkinLine* self, gint length);
GeeArrayList* gherkin_igherkin_line_get_tags (GherkinIGherkinLine* self);
gboolean gherkin_igherkin_line_starts_with_title_keyword (GherkinIGherkinLine* self, const gchar* keyword);
GeeArrayList* gherkin_igherkin_line_get_table_cells (GherkinIGherkinLine* self);


gint gherkin_igherkin_line_indent (GherkinIGherkinLine* self) {
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/IGherkinLine.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/IGherkinLine.vala"
	return GHERKIN_IGHERKIN_LINE_GET_INTERFACE (self)->indent (self);
#line 64 "IGherkinLine.c"
}


void gherkin_igherkin_line_detach (GherkinIGherkinLine* self) {
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/IGherkinLine.vala"
	g_return_if_fail (self != NULL);
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/IGherkinLine.vala"
	GHERKIN_IGHERKIN_LINE_GET_INTERFACE (self)->detach (self);
#line 73 "IGherkinLine.c"
}


gchar* gherkin_igherkin_line_get_line_text (GherkinIGherkinLine* self, gint indentToRemove) {
#line 10 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/IGherkinLine.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 10 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/IGherkinLine.vala"
	return GHERKIN_IGHERKIN_LINE_GET_INTERFACE (self)->get_line_text (self, indentToRemove);
#line 82 "IGherkinLine.c"
}


gboolean gherkin_igherkin_line_is_empty (GherkinIGherkinLine* self) {
#line 12 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/IGherkinLine.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 12 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/IGherkinLine.vala"
	return GHERKIN_IGHERKIN_LINE_GET_INTERFACE (self)->is_empty (self);
#line 91 "IGherkinLine.c"
}


gboolean gherkin_igherkin_line_starts_with (GherkinIGherkinLine* self, const gchar* prefix) {
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/IGherkinLine.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/IGherkinLine.vala"
	return GHERKIN_IGHERKIN_LINE_GET_INTERFACE (self)->starts_with (self, prefix);
#line 100 "IGherkinLine.c"
}


gchar* gherkin_igherkin_line_get_rest_trimmed (GherkinIGherkinLine* self, gint length) {
#line 16 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/IGherkinLine.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 16 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/IGherkinLine.vala"
	return GHERKIN_IGHERKIN_LINE_GET_INTERFACE (self)->get_rest_trimmed (self, length);
#line 109 "IGherkinLine.c"
}


GeeArrayList* gherkin_igherkin_line_get_tags (GherkinIGherkinLine* self) {
#line 18 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/IGherkinLine.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 18 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/IGherkinLine.vala"
	return GHERKIN_IGHERKIN_LINE_GET_INTERFACE (self)->get_tags (self);
#line 118 "IGherkinLine.c"
}


gboolean gherkin_igherkin_line_starts_with_title_keyword (GherkinIGherkinLine* self, const gchar* keyword) {
#line 20 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/IGherkinLine.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 20 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/IGherkinLine.vala"
	return GHERKIN_IGHERKIN_LINE_GET_INTERFACE (self)->starts_with_title_keyword (self, keyword);
#line 127 "IGherkinLine.c"
}


GeeArrayList* gherkin_igherkin_line_get_table_cells (GherkinIGherkinLine* self) {
#line 22 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/IGherkinLine.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 22 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/IGherkinLine.vala"
	return GHERKIN_IGHERKIN_LINE_GET_INTERFACE (self)->get_table_cells (self);
#line 136 "IGherkinLine.c"
}


static void gherkin_igherkin_line_base_init (GherkinIGherkinLineIface * iface) {
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/IGherkinLine.vala"
	static gboolean initialized = FALSE;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/IGherkinLine.vala"
	if (!initialized) {
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/IGherkinLine.vala"
		initialized = TRUE;
#line 147 "IGherkinLine.c"
	}
}


GType gherkin_igherkin_line_get_type (void) {
	static volatile gsize gherkin_igherkin_line_type_id__volatile = 0;
	if (g_once_init_enter (&gherkin_igherkin_line_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GherkinIGherkinLineIface), (GBaseInitFunc) gherkin_igherkin_line_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType gherkin_igherkin_line_type_id;
		gherkin_igherkin_line_type_id = g_type_register_static (G_TYPE_INTERFACE, "GherkinIGherkinLine", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (gherkin_igherkin_line_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&gherkin_igherkin_line_type_id__volatile, gherkin_igherkin_line_type_id);
	}
	return gherkin_igherkin_line_type_id__volatile;
}



