/* TokenScanner.c generated by valac 0.30.0, the Vala compiler
 * generated from TokenScanner.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>


#define GHERKIN_TYPE_ITOKEN_SCANNER (gherkin_itoken_scanner_get_type ())
#define GHERKIN_ITOKEN_SCANNER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_TYPE_ITOKEN_SCANNER, GherkinITokenScanner))
#define GHERKIN_IS_ITOKEN_SCANNER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_TYPE_ITOKEN_SCANNER))
#define GHERKIN_ITOKEN_SCANNER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), GHERKIN_TYPE_ITOKEN_SCANNER, GherkinITokenScannerIface))

typedef struct _GherkinITokenScanner GherkinITokenScanner;
typedef struct _GherkinITokenScannerIface GherkinITokenScannerIface;

#define GHERKIN_TYPE_TOKEN (gherkin_token_get_type ())
#define GHERKIN_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_TYPE_TOKEN, GherkinToken))
#define GHERKIN_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_TYPE_TOKEN, GherkinTokenClass))
#define GHERKIN_IS_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_TYPE_TOKEN))
#define GHERKIN_IS_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_TYPE_TOKEN))
#define GHERKIN_TOKEN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_TYPE_TOKEN, GherkinTokenClass))

typedef struct _GherkinToken GherkinToken;
typedef struct _GherkinTokenClass GherkinTokenClass;

#define GHERKIN_TYPE_TOKEN_SCANNER (gherkin_token_scanner_get_type ())
#define GHERKIN_TOKEN_SCANNER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_TYPE_TOKEN_SCANNER, GherkinTokenScanner))
#define GHERKIN_TOKEN_SCANNER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_TYPE_TOKEN_SCANNER, GherkinTokenScannerClass))
#define GHERKIN_IS_TOKEN_SCANNER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_TYPE_TOKEN_SCANNER))
#define GHERKIN_IS_TOKEN_SCANNER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_TYPE_TOKEN_SCANNER))
#define GHERKIN_TOKEN_SCANNER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_TYPE_TOKEN_SCANNER, GherkinTokenScannerClass))

typedef struct _GherkinTokenScanner GherkinTokenScanner;
typedef struct _GherkinTokenScannerClass GherkinTokenScannerClass;
typedef struct _GherkinTokenScannerPrivate GherkinTokenScannerPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define GHERKIN_AST_TYPE_LOCATION (gherkin_ast_location_get_type ())
#define GHERKIN_AST_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocation))
#define GHERKIN_AST_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocationClass))
#define GHERKIN_AST_IS_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_LOCATION))
#define GHERKIN_AST_IS_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_LOCATION))
#define GHERKIN_AST_LOCATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocationClass))

typedef struct _GherkinAstLocation GherkinAstLocation;
typedef struct _GherkinAstLocationClass GherkinAstLocationClass;

#define GHERKIN_TYPE_IGHERKIN_LINE (gherkin_igherkin_line_get_type ())
#define GHERKIN_IGHERKIN_LINE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_TYPE_IGHERKIN_LINE, GherkinIGherkinLine))
#define GHERKIN_IS_IGHERKIN_LINE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_TYPE_IGHERKIN_LINE))
#define GHERKIN_IGHERKIN_LINE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), GHERKIN_TYPE_IGHERKIN_LINE, GherkinIGherkinLineIface))

typedef struct _GherkinIGherkinLine GherkinIGherkinLine;
typedef struct _GherkinIGherkinLineIface GherkinIGherkinLineIface;

#define GHERKIN_TYPE_GHERKIN_LINE_SPAN (gherkin_gherkin_line_span_get_type ())
#define GHERKIN_GHERKIN_LINE_SPAN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_TYPE_GHERKIN_LINE_SPAN, GherkinGherkinLineSpan))
#define GHERKIN_GHERKIN_LINE_SPAN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_TYPE_GHERKIN_LINE_SPAN, GherkinGherkinLineSpanClass))
#define GHERKIN_IS_GHERKIN_LINE_SPAN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_TYPE_GHERKIN_LINE_SPAN))
#define GHERKIN_IS_GHERKIN_LINE_SPAN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_TYPE_GHERKIN_LINE_SPAN))
#define GHERKIN_GHERKIN_LINE_SPAN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_TYPE_GHERKIN_LINE_SPAN, GherkinGherkinLineSpanClass))

typedef struct _GherkinGherkinLineSpan GherkinGherkinLineSpan;
typedef struct _GherkinGherkinLineSpanClass GherkinGherkinLineSpanClass;

#define GHERKIN_TYPE_GHERKIN_LINE (gherkin_gherkin_line_get_type ())
#define GHERKIN_GHERKIN_LINE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_TYPE_GHERKIN_LINE, GherkinGherkinLine))
#define GHERKIN_GHERKIN_LINE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_TYPE_GHERKIN_LINE, GherkinGherkinLineClass))
#define GHERKIN_IS_GHERKIN_LINE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_TYPE_GHERKIN_LINE))
#define GHERKIN_IS_GHERKIN_LINE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_TYPE_GHERKIN_LINE))
#define GHERKIN_GHERKIN_LINE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_TYPE_GHERKIN_LINE, GherkinGherkinLineClass))

typedef struct _GherkinGherkinLine GherkinGherkinLine;
typedef struct _GherkinGherkinLineClass GherkinGherkinLineClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _GherkinITokenScannerIface {
	GTypeInterface parent_iface;
	GherkinToken* (*read) (GherkinITokenScanner* self);
};

struct _GherkinTokenScanner {
	GObject parent_instance;
	GherkinTokenScannerPrivate * priv;
};

struct _GherkinTokenScannerClass {
	GObjectClass parent_class;
};

struct _GherkinTokenScannerPrivate {
	GDataInputStream* reader;
	gint lineNumber;
};

struct _GherkinIGherkinLineIface {
	GTypeInterface parent_iface;
	gint (*indent) (GherkinIGherkinLine* self);
	void (*detach) (GherkinIGherkinLine* self);
	gchar* (*get_line_text) (GherkinIGherkinLine* self, gint indentToRemove);
	gboolean (*is_empty) (GherkinIGherkinLine* self);
	gboolean (*starts_with) (GherkinIGherkinLine* self, const gchar* prefix);
	gchar* (*get_rest_trimmed) (GherkinIGherkinLine* self, gint length);
	GeeArrayList* (*get_tags) (GherkinIGherkinLine* self);
	gboolean (*starts_with_title_keyword) (GherkinIGherkinLine* self, const gchar* keyword);
	GeeArrayList* (*get_table_cells) (GherkinIGherkinLine* self);
};


static gpointer gherkin_token_scanner_parent_class = NULL;
static GherkinITokenScannerIface* gherkin_token_scanner_gherkin_itoken_scanner_parent_iface = NULL;

GType gherkin_token_get_type (void) G_GNUC_CONST;
GType gherkin_itoken_scanner_get_type (void) G_GNUC_CONST;
GType gherkin_token_scanner_get_type (void) G_GNUC_CONST;
#define GHERKIN_TOKEN_SCANNER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GHERKIN_TYPE_TOKEN_SCANNER, GherkinTokenScannerPrivate))
enum  {
	GHERKIN_TOKEN_SCANNER_DUMMY_PROPERTY
};
GherkinTokenScanner* gherkin_token_scanner_new (GInputStream* source);
GherkinTokenScanner* gherkin_token_scanner_construct (GType object_type, GInputStream* source);
static GherkinToken* gherkin_token_scanner_real_read (GherkinITokenScanner* base);
GType gherkin_ast_location_get_type (void) G_GNUC_CONST;
GherkinAstLocation* gherkin_ast_location_new (gint line, gint column);
GherkinAstLocation* gherkin_ast_location_construct (GType object_type, gint line, gint column);
GType gherkin_gherkin_line_span_get_type (void) G_GNUC_CONST;
GType gherkin_igherkin_line_get_type (void) G_GNUC_CONST;
GherkinToken* gherkin_token_new (GherkinIGherkinLine* line, GherkinAstLocation* location);
GherkinToken* gherkin_token_construct (GType object_type, GherkinIGherkinLine* line, GherkinAstLocation* location);
GherkinGherkinLine* gherkin_gherkin_line_new (const gchar* lineText);
GherkinGherkinLine* gherkin_gherkin_line_construct (GType object_type, const gchar* lineText);
GType gherkin_gherkin_line_get_type (void) G_GNUC_CONST;
static void gherkin_token_scanner_finalize (GObject* obj);


GherkinTokenScanner* gherkin_token_scanner_construct (GType object_type, GInputStream* source) {
	GherkinTokenScanner * self = NULL;
	GInputStream* _tmp0_ = NULL;
	GDataInputStream* _tmp1_ = NULL;
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
	g_return_val_if_fail (source != NULL, NULL);
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
	self = (GherkinTokenScanner*) g_object_new (object_type, NULL);
#line 20 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
	_tmp0_ = source;
#line 20 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
	_tmp1_ = g_data_input_stream_new (_tmp0_);
#line 20 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
	_g_object_unref0 (self->priv->reader);
#line 20 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
	self->priv->reader = _tmp1_;
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
	return self;
#line 161 "TokenScanner.c"
}


GherkinTokenScanner* gherkin_token_scanner_new (GInputStream* source) {
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
	return gherkin_token_scanner_construct (GHERKIN_TYPE_TOKEN_SCANNER, source);
#line 168 "TokenScanner.c"
}


static gpointer _g_error_copy0 (gpointer self) {
#line 29 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
	return self ? g_error_copy (self) : NULL;
#line 175 "TokenScanner.c"
}


static GherkinToken* gherkin_token_scanner_real_read (GherkinITokenScanner* base) {
	GherkinTokenScanner * self;
	GherkinToken* result = NULL;
	GError * _inner_error_ = NULL;
#line 23 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
	self = (GherkinTokenScanner*) base;
#line 185 "TokenScanner.c"
	{
		gchar* line = NULL;
		GDataInputStream* _tmp0_ = NULL;
		gchar* _tmp1_ = NULL;
		GherkinAstLocation* location = NULL;
		gint _tmp2_ = 0;
		gint _tmp3_ = 0;
		GherkinAstLocation* _tmp4_ = NULL;
		GherkinToken* _tmp5_ = NULL;
		const gchar* _tmp6_ = NULL;
#line 25 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
		_tmp0_ = self->priv->reader;
#line 25 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
		_tmp1_ = g_data_input_stream_read_line (_tmp0_, NULL, NULL, &_inner_error_);
#line 25 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
		line = _tmp1_;
#line 25 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 204 "TokenScanner.c"
			goto __catch0_g_error;
		}
#line 26 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
		_tmp2_ = self->priv->lineNumber;
#line 26 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
		self->priv->lineNumber = _tmp2_ + 1;
#line 26 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
		_tmp3_ = self->priv->lineNumber;
#line 26 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
		_tmp4_ = gherkin_ast_location_new (_tmp3_, 0);
#line 26 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
		location = _tmp4_;
#line 27 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
		_tmp6_ = line;
#line 27 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
		if (_tmp6_ == NULL) {
#line 221 "TokenScanner.c"
			GherkinAstLocation* _tmp7_ = NULL;
			GherkinToken* _tmp8_ = NULL;
#line 27 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
			_tmp7_ = location;
#line 27 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
			_tmp8_ = gherkin_token_new (NULL, _tmp7_);
#line 27 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
			_g_object_unref0 (_tmp5_);
#line 27 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
			_tmp5_ = _tmp8_;
#line 232 "TokenScanner.c"
		} else {
			const gchar* _tmp9_ = NULL;
			GherkinGherkinLine* _tmp10_ = NULL;
			GherkinGherkinLine* _tmp11_ = NULL;
			GherkinAstLocation* _tmp12_ = NULL;
			GherkinToken* _tmp13_ = NULL;
#line 27 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
			_tmp9_ = line;
#line 27 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
			_tmp10_ = gherkin_gherkin_line_new (_tmp9_);
#line 27 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
			_tmp11_ = _tmp10_;
#line 27 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
			_tmp12_ = location;
#line 27 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
			_tmp13_ = gherkin_token_new ((GherkinIGherkinLine*) _tmp11_, _tmp12_);
#line 27 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
			_g_object_unref0 (_tmp5_);
#line 27 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
			_tmp5_ = _tmp13_;
#line 27 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
			_g_object_unref0 (_tmp11_);
#line 255 "TokenScanner.c"
		}
#line 27 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
		result = _tmp5_;
#line 27 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
		_g_object_unref0 (location);
#line 27 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
		_g_free0 (line);
#line 27 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
		return result;
#line 265 "TokenScanner.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp14_ = NULL;
		GError* _tmp15_ = NULL;
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
		e = _inner_error_;
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
		_inner_error_ = NULL;
#line 29 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
		_tmp14_ = e;
#line 29 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
		_tmp15_ = _g_error_copy0 (_tmp14_);
#line 29 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
		_inner_error_ = _tmp15_;
#line 29 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
		_g_error_free0 (e);
#line 285 "TokenScanner.c"
		goto __finally0;
	}
	__finally0:
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
	g_clear_error (&_inner_error_);
#line 24 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
	return NULL;
#line 295 "TokenScanner.c"
}


static void gherkin_token_scanner_class_init (GherkinTokenScannerClass * klass) {
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
	gherkin_token_scanner_parent_class = g_type_class_peek_parent (klass);
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
	g_type_class_add_private (klass, sizeof (GherkinTokenScannerPrivate));
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
	G_OBJECT_CLASS (klass)->finalize = gherkin_token_scanner_finalize;
#line 306 "TokenScanner.c"
}


static void gherkin_token_scanner_gherkin_itoken_scanner_interface_init (GherkinITokenScannerIface * iface) {
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
	gherkin_token_scanner_gherkin_itoken_scanner_parent_iface = g_type_interface_peek_parent (iface);
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
	iface->read = (GherkinToken* (*)(GherkinITokenScanner*)) gherkin_token_scanner_real_read;
#line 315 "TokenScanner.c"
}


static void gherkin_token_scanner_instance_init (GherkinTokenScanner * self) {
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
	self->priv = GHERKIN_TOKEN_SCANNER_GET_PRIVATE (self);
#line 322 "TokenScanner.c"
}


static void gherkin_token_scanner_finalize (GObject* obj) {
	GherkinTokenScanner * self;
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GHERKIN_TYPE_TOKEN_SCANNER, GherkinTokenScanner);
#line 16 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
	_g_object_unref0 (self->priv->reader);
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenScanner.vala"
	G_OBJECT_CLASS (gherkin_token_scanner_parent_class)->finalize (obj);
#line 334 "TokenScanner.c"
}


/**
 * <p>
 * The scanner reads a gherkin doc (typically read from a .feature file) and creates a token 
 * for each line. The tokens are passed to the parser, which outputs an AST (Abstract Syntax Tree).</p>
 *
 * <p>
 * If the scanner sees a # language header, it will reconfigure itself dynamically to look for 
 * Gherkin keywords for the associated language. The keywords are defined in gherkin-languages.json.</p>
 */
GType gherkin_token_scanner_get_type (void) {
	static volatile gsize gherkin_token_scanner_type_id__volatile = 0;
	if (g_once_init_enter (&gherkin_token_scanner_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GherkinTokenScannerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gherkin_token_scanner_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GherkinTokenScanner), 0, (GInstanceInitFunc) gherkin_token_scanner_instance_init, NULL };
		static const GInterfaceInfo gherkin_itoken_scanner_info = { (GInterfaceInitFunc) gherkin_token_scanner_gherkin_itoken_scanner_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType gherkin_token_scanner_type_id;
		gherkin_token_scanner_type_id = g_type_register_static (G_TYPE_OBJECT, "GherkinTokenScanner", &g_define_type_info, 0);
		g_type_add_interface_static (gherkin_token_scanner_type_id, GHERKIN_TYPE_ITOKEN_SCANNER, &gherkin_itoken_scanner_info);
		g_once_init_leave (&gherkin_token_scanner_type_id__volatile, gherkin_token_scanner_type_id);
	}
	return gherkin_token_scanner_type_id__volatile;
}



