/* TokenFormatter.c generated by valac 0.30.0, the Vala compiler
 * generated from TokenFormatter.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <gobject/gvaluecollector.h>


#define GHERKIN_TYPE_TOKEN_FORMATTER (gherkin_token_formatter_get_type ())
#define GHERKIN_TOKEN_FORMATTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_TYPE_TOKEN_FORMATTER, GherkinTokenFormatter))
#define GHERKIN_TOKEN_FORMATTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_TYPE_TOKEN_FORMATTER, GherkinTokenFormatterClass))
#define GHERKIN_IS_TOKEN_FORMATTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_TYPE_TOKEN_FORMATTER))
#define GHERKIN_IS_TOKEN_FORMATTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_TYPE_TOKEN_FORMATTER))
#define GHERKIN_TOKEN_FORMATTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_TYPE_TOKEN_FORMATTER, GherkinTokenFormatterClass))

typedef struct _GherkinTokenFormatter GherkinTokenFormatter;
typedef struct _GherkinTokenFormatterClass GherkinTokenFormatterClass;
typedef struct _GherkinTokenFormatterPrivate GherkinTokenFormatterPrivate;

#define GHERKIN_TYPE_TOKEN (gherkin_token_get_type ())
#define GHERKIN_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_TYPE_TOKEN, GherkinToken))
#define GHERKIN_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_TYPE_TOKEN, GherkinTokenClass))
#define GHERKIN_IS_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_TYPE_TOKEN))
#define GHERKIN_IS_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_TYPE_TOKEN))
#define GHERKIN_TOKEN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_TYPE_TOKEN, GherkinTokenClass))

typedef struct _GherkinToken GherkinToken;
typedef struct _GherkinTokenClass GherkinTokenClass;

#define GHERKIN_TYPE_GHERKIN_LINE_SPAN (gherkin_gherkin_line_span_get_type ())
#define GHERKIN_GHERKIN_LINE_SPAN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_TYPE_GHERKIN_LINE_SPAN, GherkinGherkinLineSpan))
#define GHERKIN_GHERKIN_LINE_SPAN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_TYPE_GHERKIN_LINE_SPAN, GherkinGherkinLineSpanClass))
#define GHERKIN_IS_GHERKIN_LINE_SPAN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_TYPE_GHERKIN_LINE_SPAN))
#define GHERKIN_IS_GHERKIN_LINE_SPAN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_TYPE_GHERKIN_LINE_SPAN))
#define GHERKIN_GHERKIN_LINE_SPAN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_TYPE_GHERKIN_LINE_SPAN, GherkinGherkinLineSpanClass))

typedef struct _GherkinGherkinLineSpan GherkinGherkinLineSpan;
typedef struct _GherkinGherkinLineSpanClass GherkinGherkinLineSpanClass;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _GherkinGherkinLineSpanPrivate GherkinGherkinLineSpanPrivate;

#define GHERKIN_AST_TYPE_LOCATION (gherkin_ast_location_get_type ())
#define GHERKIN_AST_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocation))
#define GHERKIN_AST_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocationClass))
#define GHERKIN_AST_IS_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_AST_TYPE_LOCATION))
#define GHERKIN_AST_IS_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_AST_TYPE_LOCATION))
#define GHERKIN_AST_LOCATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_AST_TYPE_LOCATION, GherkinAstLocationClass))

typedef struct _GherkinAstLocation GherkinAstLocation;
typedef struct _GherkinAstLocationClass GherkinAstLocationClass;

#define GHERKIN_PARSER_TYPE_TOKEN_TYPE (gherkin_parser_token_type_get_type ())
typedef struct _GherkinParamSpecTokenFormatter GherkinParamSpecTokenFormatter;

struct _GherkinTokenFormatter {
	GTypeInstance parent_instance;
	volatile int ref_count;
	GherkinTokenFormatterPrivate * priv;
};

struct _GherkinTokenFormatterClass {
	GTypeClass parent_class;
	void (*finalize) (GherkinTokenFormatter *self);
};

typedef gchar* (*GherkinToString) (gconstpointer t, void* user_data);
struct _GherkinGherkinLineSpan {
	GObject parent_instance;
	GherkinGherkinLineSpanPrivate * priv;
	gint column;
	gchar* text;
};

struct _GherkinGherkinLineSpanClass {
	GObjectClass parent_class;
};

typedef enum  {
	GHERKIN_PARSER_TOKEN_TYPE_None,
	GHERKIN_PARSER_TOKEN_TYPE_EOF,
	GHERKIN_PARSER_TOKEN_TYPE_Empty,
	GHERKIN_PARSER_TOKEN_TYPE_Comment,
	GHERKIN_PARSER_TOKEN_TYPE_TagLine,
	GHERKIN_PARSER_TOKEN_TYPE_FeatureLine,
	GHERKIN_PARSER_TOKEN_TYPE_BackgroundLine,
	GHERKIN_PARSER_TOKEN_TYPE_ScenarioLine,
	GHERKIN_PARSER_TOKEN_TYPE_ScenarioOutlineLine,
	GHERKIN_PARSER_TOKEN_TYPE_ExamplesLine,
	GHERKIN_PARSER_TOKEN_TYPE_StepLine,
	GHERKIN_PARSER_TOKEN_TYPE_DocStringSeparator,
	GHERKIN_PARSER_TOKEN_TYPE_TableRow,
	GHERKIN_PARSER_TOKEN_TYPE_Language,
	GHERKIN_PARSER_TOKEN_TYPE_Other
} GherkinParserTokenType;

struct _GherkinParamSpecTokenFormatter {
	GParamSpec parent_instance;
};


static gpointer gherkin_token_formatter_parent_class = NULL;

gpointer gherkin_token_formatter_ref (gpointer instance);
void gherkin_token_formatter_unref (gpointer instance);
GParamSpec* gherkin_param_spec_token_formatter (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void gherkin_value_set_token_formatter (GValue* value, gpointer v_object);
void gherkin_value_take_token_formatter (GValue* value, gpointer v_object);
gpointer gherkin_value_get_token_formatter (const GValue* value);
GType gherkin_token_formatter_get_type (void) G_GNUC_CONST;
enum  {
	GHERKIN_TOKEN_FORMATTER_DUMMY_PROPERTY
};
GType gherkin_token_get_type (void) G_GNUC_CONST;
gchar* gherkin_token_formatter_format_token (GherkinTokenFormatter* self, GherkinToken* token);
gboolean gherkin_token_is_EOF (GherkinToken* self);
GType gherkin_gherkin_line_span_get_type (void) G_GNUC_CONST;
GeeArrayList* gherkin_token_get_matched_items (GherkinToken* self);
gchar* gherkin_string_utils_join (GType t_type, GBoxedCopyFunc t_dup_func, GDestroyNotify t_destroy_func, GherkinToString toString, void* toString_target, const gchar* separator, GeeIterable* items);
static gchar* ___lambda34_ (GherkinTokenFormatter* self, GherkinGherkinLineSpan* o);
static gchar* ____lambda34__gherkin_to_string (gconstpointer t, gpointer self);
GType gherkin_ast_location_get_type (void) G_GNUC_CONST;
GherkinAstLocation* gherkin_token_get_location (GherkinToken* self);
gint gherkin_ast_location_get_line (GherkinAstLocation* self);
gint gherkin_ast_location_get_column (GherkinAstLocation* self);
GType gherkin_parser_token_type_get_type (void) G_GNUC_CONST;
GherkinParserTokenType gherkin_token_get_matched_type (GherkinToken* self);
gchar* gherkin_parser_token_type_to_string (GherkinParserTokenType self);
const gchar* gherkin_token_get_matched_keyword (GherkinToken* self);
const gchar* gherkin_token_get_matched_text (GherkinToken* self);
static gchar* gherkin_token_formatter_to_string (GherkinTokenFormatter* self, GherkinToken* o);
gchar* gherkin_token_to_string (GherkinToken* self);
GherkinTokenFormatter* gherkin_token_formatter_new (void);
GherkinTokenFormatter* gherkin_token_formatter_construct (GType object_type);
static void gherkin_token_formatter_finalize (GherkinTokenFormatter* obj);


static gchar* ___lambda34_ (GherkinTokenFormatter* self, GherkinGherkinLineSpan* o) {
	gchar* result = NULL;
	GherkinGherkinLineSpan* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	GherkinGherkinLineSpan* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	g_return_val_if_fail (o != NULL, NULL);
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp0_ = o;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp1_ = _tmp0_->column;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp2_ = g_strdup_printf ("%i", _tmp1_);
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp3_ = _tmp2_;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp4_ = g_strconcat (_tmp3_, ":", NULL);
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp5_ = _tmp4_;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp6_ = o;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp7_ = _tmp6_->text;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp8_ = g_strconcat (_tmp5_, _tmp7_, NULL);
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp9_ = _tmp8_;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_g_free0 (_tmp5_);
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_g_free0 (_tmp3_);
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	result = _tmp9_;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	return result;
#line 184 "TokenFormatter.c"
}


static gchar* ____lambda34__gherkin_to_string (gconstpointer t, gpointer self) {
	gchar* result;
	result = ___lambda34_ ((GherkinTokenFormatter*) self, (GherkinGherkinLineSpan*) t);
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	return result;
#line 193 "TokenFormatter.c"
}


gchar* gherkin_token_formatter_format_token (GherkinTokenFormatter* self, GherkinToken* token) {
	gchar* result = NULL;
	GherkinToken* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gchar* _tmp3_ = NULL;
	GherkinToken* _tmp4_ = NULL;
	GeeArrayList* _tmp5_ = NULL;
	GeeArrayList* _tmp6_ = NULL;
	GherkinToken* _tmp12_ = NULL;
	GherkinAstLocation* _tmp13_ = NULL;
	GherkinAstLocation* _tmp14_ = NULL;
	gint _tmp15_ = 0;
	gint _tmp16_ = 0;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	GherkinToken* _tmp19_ = NULL;
	GherkinAstLocation* _tmp20_ = NULL;
	GherkinAstLocation* _tmp21_ = NULL;
	gint _tmp22_ = 0;
	gint _tmp23_ = 0;
	gchar* _tmp24_ = NULL;
	gchar* _tmp25_ = NULL;
	GherkinToken* _tmp26_ = NULL;
	GherkinParserTokenType _tmp27_ = 0;
	GherkinParserTokenType _tmp28_ = 0;
	gchar* _tmp29_ = NULL;
	gchar* _tmp30_ = NULL;
	GherkinToken* _tmp31_ = NULL;
	const gchar* _tmp32_ = NULL;
	const gchar* _tmp33_ = NULL;
	GherkinToken* _tmp34_ = NULL;
	const gchar* _tmp35_ = NULL;
	const gchar* _tmp36_ = NULL;
	gchar* _tmp37_ = NULL;
	gchar* _tmp38_ = NULL;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	g_return_val_if_fail (token != NULL, NULL);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp0_ = token;
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp1_ = gherkin_token_is_EOF (_tmp0_);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	if (_tmp1_) {
#line 242 "TokenFormatter.c"
		gchar* _tmp2_ = NULL;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		_tmp2_ = g_strdup ("EOF");
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		result = _tmp2_;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		return result;
#line 250 "TokenFormatter.c"
	}
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp4_ = token;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp5_ = gherkin_token_get_matched_items (_tmp4_);
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp6_ = _tmp5_;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	if (_tmp6_ == NULL) {
#line 260 "TokenFormatter.c"
		gchar* _tmp7_ = NULL;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		_tmp7_ = g_strdup ("");
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		_g_free0 (_tmp3_);
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		_tmp3_ = _tmp7_;
#line 268 "TokenFormatter.c"
	} else {
		GherkinToken* _tmp8_ = NULL;
		GeeArrayList* _tmp9_ = NULL;
		GeeArrayList* _tmp10_ = NULL;
		gchar* _tmp11_ = NULL;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		_tmp8_ = token;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		_tmp9_ = gherkin_token_get_matched_items (_tmp8_);
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		_tmp10_ = _tmp9_;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		_tmp11_ = gherkin_string_utils_join (GHERKIN_TYPE_GHERKIN_LINE_SPAN, (GBoxedCopyFunc) g_object_ref, g_object_unref, ____lambda34__gherkin_to_string, self, ",", (GeeIterable*) _tmp10_);
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		_g_free0 (_tmp3_);
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		_tmp3_ = _tmp11_;
#line 286 "TokenFormatter.c"
	}
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp12_ = token;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp13_ = gherkin_token_get_location (_tmp12_);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp14_ = _tmp13_;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp15_ = gherkin_ast_location_get_line (_tmp14_);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp16_ = _tmp15_;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp17_ = g_strdup_printf ("%i", _tmp16_);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp18_ = _tmp17_;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp19_ = token;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp20_ = gherkin_token_get_location (_tmp19_);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp21_ = _tmp20_;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp22_ = gherkin_ast_location_get_column (_tmp21_);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp23_ = _tmp22_;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp24_ = g_strdup_printf ("%i", _tmp23_);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp25_ = _tmp24_;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp26_ = token;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp27_ = gherkin_token_get_matched_type (_tmp26_);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp28_ = _tmp27_;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp29_ = gherkin_parser_token_type_to_string (_tmp28_);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp30_ = _tmp29_;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp31_ = token;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp32_ = gherkin_token_get_matched_keyword (_tmp31_);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp33_ = _tmp32_;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp34_ = token;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp35_ = gherkin_token_get_matched_text (_tmp34_);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp36_ = _tmp35_;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp37_ = g_strdup_printf ("(%s:%s)%s:%s/%s/%s", _tmp18_, _tmp25_, _tmp30_, _tmp33_, _tmp36_, _tmp3_);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp38_ = _tmp37_;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_g_free0 (_tmp30_);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_g_free0 (_tmp25_);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_g_free0 (_tmp18_);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	result = _tmp38_;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_g_free0 (_tmp3_);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	return result;
#line 354 "TokenFormatter.c"
}


static gchar* gherkin_token_formatter_to_string (GherkinTokenFormatter* self, GherkinToken* o) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	GherkinToken* _tmp1_ = NULL;
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	g_return_val_if_fail (o != NULL, NULL);
#line 20 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	_tmp1_ = o;
#line 20 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	if (_tmp1_ == NULL) {
#line 370 "TokenFormatter.c"
		gchar* _tmp2_ = NULL;
#line 20 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		_tmp2_ = g_strdup ("");
#line 20 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		_g_free0 (_tmp0_);
#line 20 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		_tmp0_ = _tmp2_;
#line 378 "TokenFormatter.c"
	} else {
		GherkinToken* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
#line 20 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		_tmp3_ = o;
#line 20 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		_tmp4_ = gherkin_token_to_string (_tmp3_);
#line 20 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		_g_free0 (_tmp0_);
#line 20 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		_tmp0_ = _tmp4_;
#line 390 "TokenFormatter.c"
	}
#line 20 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	result = _tmp0_;
#line 20 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	return result;
#line 396 "TokenFormatter.c"
}


GherkinTokenFormatter* gherkin_token_formatter_construct (GType object_type) {
	GherkinTokenFormatter* self = NULL;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	self = (GherkinTokenFormatter*) g_type_create_instance (object_type);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	return self;
#line 406 "TokenFormatter.c"
}


GherkinTokenFormatter* gherkin_token_formatter_new (void) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	return gherkin_token_formatter_construct (GHERKIN_TYPE_TOKEN_FORMATTER);
#line 413 "TokenFormatter.c"
}


static void gherkin_value_token_formatter_init (GValue* value) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	value->data[0].v_pointer = NULL;
#line 420 "TokenFormatter.c"
}


static void gherkin_value_token_formatter_free_value (GValue* value) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	if (value->data[0].v_pointer) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		gherkin_token_formatter_unref (value->data[0].v_pointer);
#line 429 "TokenFormatter.c"
	}
}


static void gherkin_value_token_formatter_copy_value (const GValue* src_value, GValue* dest_value) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	if (src_value->data[0].v_pointer) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		dest_value->data[0].v_pointer = gherkin_token_formatter_ref (src_value->data[0].v_pointer);
#line 439 "TokenFormatter.c"
	} else {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		dest_value->data[0].v_pointer = NULL;
#line 443 "TokenFormatter.c"
	}
}


static gpointer gherkin_value_token_formatter_peek_pointer (const GValue* value) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	return value->data[0].v_pointer;
#line 451 "TokenFormatter.c"
}


static gchar* gherkin_value_token_formatter_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	if (collect_values[0].v_pointer) {
#line 458 "TokenFormatter.c"
		GherkinTokenFormatter* object;
		object = collect_values[0].v_pointer;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		if (object->parent_instance.g_class == NULL) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 465 "TokenFormatter.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 469 "TokenFormatter.c"
		}
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		value->data[0].v_pointer = gherkin_token_formatter_ref (object);
#line 473 "TokenFormatter.c"
	} else {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		value->data[0].v_pointer = NULL;
#line 477 "TokenFormatter.c"
	}
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	return NULL;
#line 481 "TokenFormatter.c"
}


static gchar* gherkin_value_token_formatter_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	GherkinTokenFormatter** object_p;
	object_p = collect_values[0].v_pointer;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	if (!object_p) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 492 "TokenFormatter.c"
	}
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	if (!value->data[0].v_pointer) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		*object_p = NULL;
#line 498 "TokenFormatter.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		*object_p = value->data[0].v_pointer;
#line 502 "TokenFormatter.c"
	} else {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		*object_p = gherkin_token_formatter_ref (value->data[0].v_pointer);
#line 506 "TokenFormatter.c"
	}
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	return NULL;
#line 510 "TokenFormatter.c"
}


GParamSpec* gherkin_param_spec_token_formatter (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	GherkinParamSpecTokenFormatter* spec;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	g_return_val_if_fail (g_type_is_a (object_type, GHERKIN_TYPE_TOKEN_FORMATTER), NULL);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	return G_PARAM_SPEC (spec);
#line 524 "TokenFormatter.c"
}


gpointer gherkin_value_get_token_formatter (const GValue* value) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GHERKIN_TYPE_TOKEN_FORMATTER), NULL);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	return value->data[0].v_pointer;
#line 533 "TokenFormatter.c"
}


void gherkin_value_set_token_formatter (GValue* value, gpointer v_object) {
	GherkinTokenFormatter* old;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GHERKIN_TYPE_TOKEN_FORMATTER));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	old = value->data[0].v_pointer;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	if (v_object) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GHERKIN_TYPE_TOKEN_FORMATTER));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		value->data[0].v_pointer = v_object;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		gherkin_token_formatter_ref (value->data[0].v_pointer);
#line 553 "TokenFormatter.c"
	} else {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		value->data[0].v_pointer = NULL;
#line 557 "TokenFormatter.c"
	}
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	if (old) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		gherkin_token_formatter_unref (old);
#line 563 "TokenFormatter.c"
	}
}


void gherkin_value_take_token_formatter (GValue* value, gpointer v_object) {
	GherkinTokenFormatter* old;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GHERKIN_TYPE_TOKEN_FORMATTER));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	old = value->data[0].v_pointer;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	if (v_object) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GHERKIN_TYPE_TOKEN_FORMATTER));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		value->data[0].v_pointer = v_object;
#line 582 "TokenFormatter.c"
	} else {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		value->data[0].v_pointer = NULL;
#line 586 "TokenFormatter.c"
	}
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	if (old) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		gherkin_token_formatter_unref (old);
#line 592 "TokenFormatter.c"
	}
}


static void gherkin_token_formatter_class_init (GherkinTokenFormatterClass * klass) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	gherkin_token_formatter_parent_class = g_type_class_peek_parent (klass);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	((GherkinTokenFormatterClass *) klass)->finalize = gherkin_token_formatter_finalize;
#line 602 "TokenFormatter.c"
}


static void gherkin_token_formatter_instance_init (GherkinTokenFormatter * self) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	self->ref_count = 1;
#line 609 "TokenFormatter.c"
}


static void gherkin_token_formatter_finalize (GherkinTokenFormatter* obj) {
	GherkinTokenFormatter * self;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GHERKIN_TYPE_TOKEN_FORMATTER, GherkinTokenFormatter);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	g_signal_handlers_destroy (self);
#line 619 "TokenFormatter.c"
}


GType gherkin_token_formatter_get_type (void) {
	static volatile gsize gherkin_token_formatter_type_id__volatile = 0;
	if (g_once_init_enter (&gherkin_token_formatter_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { gherkin_value_token_formatter_init, gherkin_value_token_formatter_free_value, gherkin_value_token_formatter_copy_value, gherkin_value_token_formatter_peek_pointer, "p", gherkin_value_token_formatter_collect_value, "p", gherkin_value_token_formatter_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (GherkinTokenFormatterClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gherkin_token_formatter_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GherkinTokenFormatter), 0, (GInstanceInitFunc) gherkin_token_formatter_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType gherkin_token_formatter_type_id;
		gherkin_token_formatter_type_id = g_type_register_fundamental (g_type_fundamental_next (), "GherkinTokenFormatter", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&gherkin_token_formatter_type_id__volatile, gherkin_token_formatter_type_id);
	}
	return gherkin_token_formatter_type_id__volatile;
}


gpointer gherkin_token_formatter_ref (gpointer instance) {
	GherkinTokenFormatter* self;
	self = instance;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	g_atomic_int_inc (&self->ref_count);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	return instance;
#line 644 "TokenFormatter.c"
}


void gherkin_token_formatter_unref (gpointer instance) {
	GherkinTokenFormatter* self;
	self = instance;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		GHERKIN_TOKEN_FORMATTER_GET_CLASS (self)->finalize (self);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/TokenFormatter.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 657 "TokenFormatter.c"
	}
}



