/* Argument.c generated by valac 0.30.0, the Vala compiler
 * generated from Argument.vala, do not modify */


#include <glib.h>
#include <glib-object.h>


#define GHERKIN_PICKLES_TYPE_ARGUMENT (gherkin_pickles_argument_get_type ())
#define GHERKIN_PICKLES_ARGUMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_PICKLES_TYPE_ARGUMENT, GherkinPicklesArgument))
#define GHERKIN_PICKLES_IS_ARGUMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_PICKLES_TYPE_ARGUMENT))
#define GHERKIN_PICKLES_ARGUMENT_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), GHERKIN_PICKLES_TYPE_ARGUMENT, GherkinPicklesArgumentIface))

typedef struct _GherkinPicklesArgument GherkinPicklesArgument;
typedef struct _GherkinPicklesArgumentIface GherkinPicklesArgumentIface;

#define GHERKIN_PICKLES_TYPE_PICKLE_LOCATION (gherkin_pickles_pickle_location_get_type ())
#define GHERKIN_PICKLES_PICKLE_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_PICKLES_TYPE_PICKLE_LOCATION, GherkinPicklesPickleLocation))
#define GHERKIN_PICKLES_PICKLE_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_PICKLES_TYPE_PICKLE_LOCATION, GherkinPicklesPickleLocationClass))
#define GHERKIN_PICKLES_IS_PICKLE_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_PICKLES_TYPE_PICKLE_LOCATION))
#define GHERKIN_PICKLES_IS_PICKLE_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_PICKLES_TYPE_PICKLE_LOCATION))
#define GHERKIN_PICKLES_PICKLE_LOCATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_PICKLES_TYPE_PICKLE_LOCATION, GherkinPicklesPickleLocationClass))

typedef struct _GherkinPicklesPickleLocation GherkinPicklesPickleLocation;
typedef struct _GherkinPicklesPickleLocationClass GherkinPicklesPickleLocationClass;

struct _GherkinPicklesArgumentIface {
	GTypeInterface parent_iface;
	GherkinPicklesPickleLocation* (*get_location) (GherkinPicklesArgument* self);
	void (*set_location) (GherkinPicklesArgument* self, GherkinPicklesPickleLocation* value);
};



GType gherkin_pickles_pickle_location_get_type (void) G_GNUC_CONST;
GType gherkin_pickles_argument_get_type (void) G_GNUC_CONST;
GherkinPicklesPickleLocation* gherkin_pickles_argument_get_location (GherkinPicklesArgument* self);
void gherkin_pickles_argument_set_location (GherkinPicklesArgument* self, GherkinPicklesPickleLocation* value);


GherkinPicklesPickleLocation* gherkin_pickles_argument_get_location (GherkinPicklesArgument* self) {
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/Argument.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/Argument.vala"
	return GHERKIN_PICKLES_ARGUMENT_GET_INTERFACE (self)->get_location (self);
#line 47 "Argument.c"
}


void gherkin_pickles_argument_set_location (GherkinPicklesArgument* self, GherkinPicklesPickleLocation* value) {
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/Argument.vala"
	g_return_if_fail (self != NULL);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/Argument.vala"
	GHERKIN_PICKLES_ARGUMENT_GET_INTERFACE (self)->set_location (self, value);
#line 56 "Argument.c"
}


static void gherkin_pickles_argument_base_init (GherkinPicklesArgumentIface * iface) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/Argument.vala"
	static gboolean initialized = FALSE;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/Argument.vala"
	if (!initialized) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/Argument.vala"
		initialized = TRUE;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/Argument.vala"
		g_object_interface_install_property (iface, g_param_spec_object ("location", "location", "location", GHERKIN_PICKLES_TYPE_PICKLE_LOCATION, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 69 "Argument.c"
	}
}


GType gherkin_pickles_argument_get_type (void) {
	static volatile gsize gherkin_pickles_argument_type_id__volatile = 0;
	if (g_once_init_enter (&gherkin_pickles_argument_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GherkinPicklesArgumentIface), (GBaseInitFunc) gherkin_pickles_argument_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType gherkin_pickles_argument_type_id;
		gherkin_pickles_argument_type_id = g_type_register_static (G_TYPE_INTERFACE, "GherkinPicklesArgument", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (gherkin_pickles_argument_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&gherkin_pickles_argument_type_id__volatile, gherkin_pickles_argument_type_id);
	}
	return gherkin_pickles_argument_type_id__volatile;
}



