/* PickleRow.c generated by valac 0.30.0, the Vala compiler
 * generated from PickleRow.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gee.h>


#define GHERKIN_PICKLES_TYPE_PICKLE_ROW (gherkin_pickles_pickle_row_get_type ())
#define GHERKIN_PICKLES_PICKLE_ROW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_PICKLES_TYPE_PICKLE_ROW, GherkinPicklesPickleRow))
#define GHERKIN_PICKLES_PICKLE_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_PICKLES_TYPE_PICKLE_ROW, GherkinPicklesPickleRowClass))
#define GHERKIN_PICKLES_IS_PICKLE_ROW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_PICKLES_TYPE_PICKLE_ROW))
#define GHERKIN_PICKLES_IS_PICKLE_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_PICKLES_TYPE_PICKLE_ROW))
#define GHERKIN_PICKLES_PICKLE_ROW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_PICKLES_TYPE_PICKLE_ROW, GherkinPicklesPickleRowClass))

typedef struct _GherkinPicklesPickleRow GherkinPicklesPickleRow;
typedef struct _GherkinPicklesPickleRowClass GherkinPicklesPickleRowClass;
typedef struct _GherkinPicklesPickleRowPrivate GherkinPicklesPickleRowPrivate;

#define GHERKIN_PICKLES_TYPE_PICKLE_CELL (gherkin_pickles_pickle_cell_get_type ())
#define GHERKIN_PICKLES_PICKLE_CELL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_PICKLES_TYPE_PICKLE_CELL, GherkinPicklesPickleCell))
#define GHERKIN_PICKLES_PICKLE_CELL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_PICKLES_TYPE_PICKLE_CELL, GherkinPicklesPickleCellClass))
#define GHERKIN_PICKLES_IS_PICKLE_CELL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_PICKLES_TYPE_PICKLE_CELL))
#define GHERKIN_PICKLES_IS_PICKLE_CELL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_PICKLES_TYPE_PICKLE_CELL))
#define GHERKIN_PICKLES_PICKLE_CELL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_PICKLES_TYPE_PICKLE_CELL, GherkinPicklesPickleCellClass))

typedef struct _GherkinPicklesPickleCell GherkinPicklesPickleCell;
typedef struct _GherkinPicklesPickleCellClass GherkinPicklesPickleCellClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _GherkinPicklesPickleRow {
	GObject parent_instance;
	GherkinPicklesPickleRowPrivate * priv;
};

struct _GherkinPicklesPickleRowClass {
	GObjectClass parent_class;
};

struct _GherkinPicklesPickleRowPrivate {
	GeeArrayList* _cells;
};


static gpointer gherkin_pickles_pickle_row_parent_class = NULL;

GType gherkin_pickles_pickle_row_get_type (void) G_GNUC_CONST;
GType gherkin_pickles_pickle_cell_get_type (void) G_GNUC_CONST;
#define GHERKIN_PICKLES_PICKLE_ROW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GHERKIN_PICKLES_TYPE_PICKLE_ROW, GherkinPicklesPickleRowPrivate))
enum  {
	GHERKIN_PICKLES_PICKLE_ROW_DUMMY_PROPERTY,
	GHERKIN_PICKLES_PICKLE_ROW_CELLS
};
GherkinPicklesPickleRow* gherkin_pickles_pickle_row_new (GeeArrayList* cells);
GherkinPicklesPickleRow* gherkin_pickles_pickle_row_construct (GType object_type, GeeArrayList* cells);
void gherkin_pickles_pickle_row_set_cells (GherkinPicklesPickleRow* self, GeeArrayList* value);
GeeArrayList* gherkin_pickles_pickle_row_get_cells (GherkinPicklesPickleRow* self);
static void gherkin_pickles_pickle_row_finalize (GObject* obj);
static void _vala_gherkin_pickles_pickle_row_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_gherkin_pickles_pickle_row_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


GherkinPicklesPickleRow* gherkin_pickles_pickle_row_construct (GType object_type, GeeArrayList* cells) {
	GherkinPicklesPickleRow * self = NULL;
	GeeArrayList* _tmp0_ = NULL;
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	g_return_val_if_fail (cells != NULL, NULL);
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	self = (GherkinPicklesPickleRow*) g_object_new (object_type, NULL);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	_tmp0_ = cells;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	gherkin_pickles_pickle_row_set_cells (self, _tmp0_);
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	return self;
#line 78 "PickleRow.c"
}


GherkinPicklesPickleRow* gherkin_pickles_pickle_row_new (GeeArrayList* cells) {
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	return gherkin_pickles_pickle_row_construct (GHERKIN_PICKLES_TYPE_PICKLE_ROW, cells);
#line 85 "PickleRow.c"
}


GeeArrayList* gherkin_pickles_pickle_row_get_cells (GherkinPicklesPickleRow* self) {
	GeeArrayList* result;
	GeeArrayList* _tmp0_ = NULL;
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	_tmp0_ = self->priv->_cells;
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	result = _tmp0_;
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	return result;
#line 100 "PickleRow.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	return self ? g_object_ref (self) : NULL;
#line 107 "PickleRow.c"
}


void gherkin_pickles_pickle_row_set_cells (GherkinPicklesPickleRow* self, GeeArrayList* value) {
	GeeArrayList* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	g_return_if_fail (self != NULL);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	_tmp0_ = value;
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	_g_object_unref0 (self->priv->_cells);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	self->priv->_cells = _tmp1_;
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	g_object_notify ((GObject *) self, "cells");
#line 126 "PickleRow.c"
}


static void gherkin_pickles_pickle_row_class_init (GherkinPicklesPickleRowClass * klass) {
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	gherkin_pickles_pickle_row_parent_class = g_type_class_peek_parent (klass);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	g_type_class_add_private (klass, sizeof (GherkinPicklesPickleRowPrivate));
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_gherkin_pickles_pickle_row_get_property;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_gherkin_pickles_pickle_row_set_property;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	G_OBJECT_CLASS (klass)->finalize = gherkin_pickles_pickle_row_finalize;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), GHERKIN_PICKLES_PICKLE_ROW_CELLS, g_param_spec_object ("cells", "cells", "cells", GEE_TYPE_ARRAY_LIST, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 143 "PickleRow.c"
}


static void gherkin_pickles_pickle_row_instance_init (GherkinPicklesPickleRow * self) {
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	self->priv = GHERKIN_PICKLES_PICKLE_ROW_GET_PRIVATE (self);
#line 150 "PickleRow.c"
}


static void gherkin_pickles_pickle_row_finalize (GObject* obj) {
	GherkinPicklesPickleRow * self;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GHERKIN_PICKLES_TYPE_PICKLE_ROW, GherkinPicklesPickleRow);
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	_g_object_unref0 (self->priv->_cells);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	G_OBJECT_CLASS (gherkin_pickles_pickle_row_parent_class)->finalize (obj);
#line 162 "PickleRow.c"
}


GType gherkin_pickles_pickle_row_get_type (void) {
	static volatile gsize gherkin_pickles_pickle_row_type_id__volatile = 0;
	if (g_once_init_enter (&gherkin_pickles_pickle_row_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GherkinPicklesPickleRowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gherkin_pickles_pickle_row_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GherkinPicklesPickleRow), 0, (GInstanceInitFunc) gherkin_pickles_pickle_row_instance_init, NULL };
		GType gherkin_pickles_pickle_row_type_id;
		gherkin_pickles_pickle_row_type_id = g_type_register_static (G_TYPE_OBJECT, "GherkinPicklesPickleRow", &g_define_type_info, 0);
		g_once_init_leave (&gherkin_pickles_pickle_row_type_id__volatile, gherkin_pickles_pickle_row_type_id);
	}
	return gherkin_pickles_pickle_row_type_id__volatile;
}


static void _vala_gherkin_pickles_pickle_row_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GherkinPicklesPickleRow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GHERKIN_PICKLES_TYPE_PICKLE_ROW, GherkinPicklesPickleRow);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	switch (property_id) {
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
		case GHERKIN_PICKLES_PICKLE_ROW_CELLS:
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
		g_value_set_object (value, gherkin_pickles_pickle_row_get_cells (self));
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
		break;
#line 189 "PickleRow.c"
		default:
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
		break;
#line 195 "PickleRow.c"
	}
}


static void _vala_gherkin_pickles_pickle_row_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GherkinPicklesPickleRow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GHERKIN_PICKLES_TYPE_PICKLE_ROW, GherkinPicklesPickleRow);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
	switch (property_id) {
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
		case GHERKIN_PICKLES_PICKLE_ROW_CELLS:
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
		gherkin_pickles_pickle_row_set_cells (self, g_value_get_object (value));
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
		break;
#line 211 "PickleRow.c"
		default:
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleRow.vala"
		break;
#line 217 "PickleRow.c"
	}
}



