/* PickleCell.c generated by valac 0.30.0, the Vala compiler
 * generated from PickleCell.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define GHERKIN_PICKLES_TYPE_PICKLE_CELL (gherkin_pickles_pickle_cell_get_type ())
#define GHERKIN_PICKLES_PICKLE_CELL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_PICKLES_TYPE_PICKLE_CELL, GherkinPicklesPickleCell))
#define GHERKIN_PICKLES_PICKLE_CELL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_PICKLES_TYPE_PICKLE_CELL, GherkinPicklesPickleCellClass))
#define GHERKIN_PICKLES_IS_PICKLE_CELL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_PICKLES_TYPE_PICKLE_CELL))
#define GHERKIN_PICKLES_IS_PICKLE_CELL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_PICKLES_TYPE_PICKLE_CELL))
#define GHERKIN_PICKLES_PICKLE_CELL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_PICKLES_TYPE_PICKLE_CELL, GherkinPicklesPickleCellClass))

typedef struct _GherkinPicklesPickleCell GherkinPicklesPickleCell;
typedef struct _GherkinPicklesPickleCellClass GherkinPicklesPickleCellClass;
typedef struct _GherkinPicklesPickleCellPrivate GherkinPicklesPickleCellPrivate;

#define GHERKIN_PICKLES_TYPE_PICKLE_LOCATION (gherkin_pickles_pickle_location_get_type ())
#define GHERKIN_PICKLES_PICKLE_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_PICKLES_TYPE_PICKLE_LOCATION, GherkinPicklesPickleLocation))
#define GHERKIN_PICKLES_PICKLE_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_PICKLES_TYPE_PICKLE_LOCATION, GherkinPicklesPickleLocationClass))
#define GHERKIN_PICKLES_IS_PICKLE_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_PICKLES_TYPE_PICKLE_LOCATION))
#define GHERKIN_PICKLES_IS_PICKLE_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_PICKLES_TYPE_PICKLE_LOCATION))
#define GHERKIN_PICKLES_PICKLE_LOCATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_PICKLES_TYPE_PICKLE_LOCATION, GherkinPicklesPickleLocationClass))

typedef struct _GherkinPicklesPickleLocation GherkinPicklesPickleLocation;
typedef struct _GherkinPicklesPickleLocationClass GherkinPicklesPickleLocationClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _GherkinPicklesPickleCell {
	GObject parent_instance;
	GherkinPicklesPickleCellPrivate * priv;
};

struct _GherkinPicklesPickleCellClass {
	GObjectClass parent_class;
};

struct _GherkinPicklesPickleCellPrivate {
	GherkinPicklesPickleLocation* _location;
	gchar* _value;
};


static gpointer gherkin_pickles_pickle_cell_parent_class = NULL;

GType gherkin_pickles_pickle_cell_get_type (void) G_GNUC_CONST;
GType gherkin_pickles_pickle_location_get_type (void) G_GNUC_CONST;
#define GHERKIN_PICKLES_PICKLE_CELL_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GHERKIN_PICKLES_TYPE_PICKLE_CELL, GherkinPicklesPickleCellPrivate))
enum  {
	GHERKIN_PICKLES_PICKLE_CELL_DUMMY_PROPERTY,
	GHERKIN_PICKLES_PICKLE_CELL_LOCATION,
	GHERKIN_PICKLES_PICKLE_CELL_VALUE
};
GherkinPicklesPickleCell* gherkin_pickles_pickle_cell_new (GherkinPicklesPickleLocation* location, const gchar* value);
GherkinPicklesPickleCell* gherkin_pickles_pickle_cell_construct (GType object_type, GherkinPicklesPickleLocation* location, const gchar* value);
void gherkin_pickles_pickle_cell_set_location (GherkinPicklesPickleCell* self, GherkinPicklesPickleLocation* value);
void gherkin_pickles_pickle_cell_set_value (GherkinPicklesPickleCell* self, const gchar* value);
GherkinPicklesPickleLocation* gherkin_pickles_pickle_cell_get_location (GherkinPicklesPickleCell* self);
const gchar* gherkin_pickles_pickle_cell_get_value (GherkinPicklesPickleCell* self);
static void gherkin_pickles_pickle_cell_finalize (GObject* obj);
static void _vala_gherkin_pickles_pickle_cell_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_gherkin_pickles_pickle_cell_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


GherkinPicklesPickleCell* gherkin_pickles_pickle_cell_construct (GType object_type, GherkinPicklesPickleLocation* location, const gchar* value) {
	GherkinPicklesPickleCell * self = NULL;
	GherkinPicklesPickleLocation* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	g_return_val_if_fail (location != NULL, NULL);
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	g_return_val_if_fail (value != NULL, NULL);
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	self = (GherkinPicklesPickleCell*) g_object_new (object_type, NULL);
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	_tmp0_ = location;
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	gherkin_pickles_pickle_cell_set_location (self, _tmp0_);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	_tmp1_ = value;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	gherkin_pickles_pickle_cell_set_value (self, _tmp1_);
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	return self;
#line 91 "PickleCell.c"
}


GherkinPicklesPickleCell* gherkin_pickles_pickle_cell_new (GherkinPicklesPickleLocation* location, const gchar* value) {
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	return gherkin_pickles_pickle_cell_construct (GHERKIN_PICKLES_TYPE_PICKLE_CELL, location, value);
#line 98 "PickleCell.c"
}


GherkinPicklesPickleLocation* gherkin_pickles_pickle_cell_get_location (GherkinPicklesPickleCell* self) {
	GherkinPicklesPickleLocation* result;
	GherkinPicklesPickleLocation* _tmp0_ = NULL;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	_tmp0_ = self->priv->_location;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	result = _tmp0_;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	return result;
#line 113 "PickleCell.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	return self ? g_object_ref (self) : NULL;
#line 120 "PickleCell.c"
}


void gherkin_pickles_pickle_cell_set_location (GherkinPicklesPickleCell* self, GherkinPicklesPickleLocation* value) {
	GherkinPicklesPickleLocation* _tmp0_ = NULL;
	GherkinPicklesPickleLocation* _tmp1_ = NULL;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	g_return_if_fail (self != NULL);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	_tmp0_ = value;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	_g_object_unref0 (self->priv->_location);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	self->priv->_location = _tmp1_;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	g_object_notify ((GObject *) self, "location");
#line 139 "PickleCell.c"
}


const gchar* gherkin_pickles_pickle_cell_get_value (GherkinPicklesPickleCell* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	_tmp0_ = self->priv->_value;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	result = _tmp0_;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	return result;
#line 154 "PickleCell.c"
}


void gherkin_pickles_pickle_cell_set_value (GherkinPicklesPickleCell* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	g_return_if_fail (self != NULL);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	_tmp0_ = value;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	_g_free0 (self->priv->_value);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	self->priv->_value = _tmp1_;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	g_object_notify ((GObject *) self, "value");
#line 173 "PickleCell.c"
}


static void gherkin_pickles_pickle_cell_class_init (GherkinPicklesPickleCellClass * klass) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	gherkin_pickles_pickle_cell_parent_class = g_type_class_peek_parent (klass);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	g_type_class_add_private (klass, sizeof (GherkinPicklesPickleCellPrivate));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_gherkin_pickles_pickle_cell_get_property;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_gherkin_pickles_pickle_cell_set_property;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	G_OBJECT_CLASS (klass)->finalize = gherkin_pickles_pickle_cell_finalize;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), GHERKIN_PICKLES_PICKLE_CELL_LOCATION, g_param_spec_object ("location", "location", "location", GHERKIN_PICKLES_TYPE_PICKLE_LOCATION, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), GHERKIN_PICKLES_PICKLE_CELL_VALUE, g_param_spec_string ("value", "value", "value", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 192 "PickleCell.c"
}


static void gherkin_pickles_pickle_cell_instance_init (GherkinPicklesPickleCell * self) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	self->priv = GHERKIN_PICKLES_PICKLE_CELL_GET_PRIVATE (self);
#line 199 "PickleCell.c"
}


static void gherkin_pickles_pickle_cell_finalize (GObject* obj) {
	GherkinPicklesPickleCell * self;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GHERKIN_PICKLES_TYPE_PICKLE_CELL, GherkinPicklesPickleCell);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	_g_object_unref0 (self->priv->_location);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	_g_free0 (self->priv->_value);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	G_OBJECT_CLASS (gherkin_pickles_pickle_cell_parent_class)->finalize (obj);
#line 213 "PickleCell.c"
}


GType gherkin_pickles_pickle_cell_get_type (void) {
	static volatile gsize gherkin_pickles_pickle_cell_type_id__volatile = 0;
	if (g_once_init_enter (&gherkin_pickles_pickle_cell_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GherkinPicklesPickleCellClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gherkin_pickles_pickle_cell_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GherkinPicklesPickleCell), 0, (GInstanceInitFunc) gherkin_pickles_pickle_cell_instance_init, NULL };
		GType gherkin_pickles_pickle_cell_type_id;
		gherkin_pickles_pickle_cell_type_id = g_type_register_static (G_TYPE_OBJECT, "GherkinPicklesPickleCell", &g_define_type_info, 0);
		g_once_init_leave (&gherkin_pickles_pickle_cell_type_id__volatile, gherkin_pickles_pickle_cell_type_id);
	}
	return gherkin_pickles_pickle_cell_type_id__volatile;
}


static void _vala_gherkin_pickles_pickle_cell_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GherkinPicklesPickleCell * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GHERKIN_PICKLES_TYPE_PICKLE_CELL, GherkinPicklesPickleCell);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	switch (property_id) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
		case GHERKIN_PICKLES_PICKLE_CELL_LOCATION:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
		g_value_set_object (value, gherkin_pickles_pickle_cell_get_location (self));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
		break;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
		case GHERKIN_PICKLES_PICKLE_CELL_VALUE:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
		g_value_set_string (value, gherkin_pickles_pickle_cell_get_value (self));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
		break;
#line 246 "PickleCell.c"
		default:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
		break;
#line 252 "PickleCell.c"
	}
}


static void _vala_gherkin_pickles_pickle_cell_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GherkinPicklesPickleCell * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GHERKIN_PICKLES_TYPE_PICKLE_CELL, GherkinPicklesPickleCell);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
	switch (property_id) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
		case GHERKIN_PICKLES_PICKLE_CELL_LOCATION:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
		gherkin_pickles_pickle_cell_set_location (self, g_value_get_object (value));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
		break;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
		case GHERKIN_PICKLES_PICKLE_CELL_VALUE:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
		gherkin_pickles_pickle_cell_set_value (self, g_value_get_string (value));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
		break;
#line 274 "PickleCell.c"
		default:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleCell.vala"
		break;
#line 280 "PickleCell.c"
	}
}



