/* PickleTag.c generated by valac 0.30.0, the Vala compiler
 * generated from PickleTag.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define GHERKIN_PICKLES_TYPE_PICKLE_TAG (gherkin_pickles_pickle_tag_get_type ())
#define GHERKIN_PICKLES_PICKLE_TAG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_PICKLES_TYPE_PICKLE_TAG, GherkinPicklesPickleTag))
#define GHERKIN_PICKLES_PICKLE_TAG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_PICKLES_TYPE_PICKLE_TAG, GherkinPicklesPickleTagClass))
#define GHERKIN_PICKLES_IS_PICKLE_TAG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_PICKLES_TYPE_PICKLE_TAG))
#define GHERKIN_PICKLES_IS_PICKLE_TAG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_PICKLES_TYPE_PICKLE_TAG))
#define GHERKIN_PICKLES_PICKLE_TAG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_PICKLES_TYPE_PICKLE_TAG, GherkinPicklesPickleTagClass))

typedef struct _GherkinPicklesPickleTag GherkinPicklesPickleTag;
typedef struct _GherkinPicklesPickleTagClass GherkinPicklesPickleTagClass;
typedef struct _GherkinPicklesPickleTagPrivate GherkinPicklesPickleTagPrivate;

#define GHERKIN_PICKLES_TYPE_PICKLE_LOCATION (gherkin_pickles_pickle_location_get_type ())
#define GHERKIN_PICKLES_PICKLE_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_PICKLES_TYPE_PICKLE_LOCATION, GherkinPicklesPickleLocation))
#define GHERKIN_PICKLES_PICKLE_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_PICKLES_TYPE_PICKLE_LOCATION, GherkinPicklesPickleLocationClass))
#define GHERKIN_PICKLES_IS_PICKLE_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_PICKLES_TYPE_PICKLE_LOCATION))
#define GHERKIN_PICKLES_IS_PICKLE_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_PICKLES_TYPE_PICKLE_LOCATION))
#define GHERKIN_PICKLES_PICKLE_LOCATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_PICKLES_TYPE_PICKLE_LOCATION, GherkinPicklesPickleLocationClass))

typedef struct _GherkinPicklesPickleLocation GherkinPicklesPickleLocation;
typedef struct _GherkinPicklesPickleLocationClass GherkinPicklesPickleLocationClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _GherkinPicklesPickleTag {
	GObject parent_instance;
	GherkinPicklesPickleTagPrivate * priv;
};

struct _GherkinPicklesPickleTagClass {
	GObjectClass parent_class;
};

struct _GherkinPicklesPickleTagPrivate {
	GherkinPicklesPickleLocation* _location;
	gchar* _name;
};


static gpointer gherkin_pickles_pickle_tag_parent_class = NULL;

GType gherkin_pickles_pickle_tag_get_type (void) G_GNUC_CONST;
GType gherkin_pickles_pickle_location_get_type (void) G_GNUC_CONST;
#define GHERKIN_PICKLES_PICKLE_TAG_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GHERKIN_PICKLES_TYPE_PICKLE_TAG, GherkinPicklesPickleTagPrivate))
enum  {
	GHERKIN_PICKLES_PICKLE_TAG_DUMMY_PROPERTY
};
GherkinPicklesPickleTag* gherkin_pickles_pickle_tag_new (GherkinPicklesPickleLocation* location, const gchar* name);
GherkinPicklesPickleTag* gherkin_pickles_pickle_tag_construct (GType object_type, GherkinPicklesPickleLocation* location, const gchar* name);
static void gherkin_pickles_pickle_tag_set_location (GherkinPicklesPickleTag* self, GherkinPicklesPickleLocation* value);
static void gherkin_pickles_pickle_tag_set_name (GherkinPicklesPickleTag* self, const gchar* value);
static GherkinPicklesPickleLocation* gherkin_pickles_pickle_tag_get_location (GherkinPicklesPickleTag* self);
static const gchar* gherkin_pickles_pickle_tag_get_name (GherkinPicklesPickleTag* self);
static void gherkin_pickles_pickle_tag_finalize (GObject* obj);
static void _vala_gherkin_pickles_pickle_tag_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_gherkin_pickles_pickle_tag_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


GherkinPicklesPickleTag* gherkin_pickles_pickle_tag_construct (GType object_type, GherkinPicklesPickleLocation* location, const gchar* name) {
	GherkinPicklesPickleTag * self = NULL;
	GherkinPicklesPickleLocation* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	g_return_val_if_fail (location != NULL, NULL);
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	self = (GherkinPicklesPickleTag*) g_object_new (object_type, NULL);
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	_tmp0_ = location;
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	gherkin_pickles_pickle_tag_set_location (self, _tmp0_);
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	_tmp1_ = name;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	gherkin_pickles_pickle_tag_set_name (self, _tmp1_);
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	return self;
#line 89 "PickleTag.c"
}


GherkinPicklesPickleTag* gherkin_pickles_pickle_tag_new (GherkinPicklesPickleLocation* location, const gchar* name) {
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	return gherkin_pickles_pickle_tag_construct (GHERKIN_PICKLES_TYPE_PICKLE_TAG, location, name);
#line 96 "PickleTag.c"
}


static GherkinPicklesPickleLocation* gherkin_pickles_pickle_tag_get_location (GherkinPicklesPickleTag* self) {
	GherkinPicklesPickleLocation* result;
	GherkinPicklesPickleLocation* _tmp0_ = NULL;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	_tmp0_ = self->priv->_location;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	result = _tmp0_;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	return result;
#line 111 "PickleTag.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	return self ? g_object_ref (self) : NULL;
#line 118 "PickleTag.c"
}


static void gherkin_pickles_pickle_tag_set_location (GherkinPicklesPickleTag* self, GherkinPicklesPickleLocation* value) {
	GherkinPicklesPickleLocation* _tmp0_ = NULL;
	GherkinPicklesPickleLocation* _tmp1_ = NULL;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	g_return_if_fail (self != NULL);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	_tmp0_ = value;
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	_g_object_unref0 (self->priv->_location);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	self->priv->_location = _tmp1_;
#line 135 "PickleTag.c"
}


static const gchar* gherkin_pickles_pickle_tag_get_name (GherkinPicklesPickleTag* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	_tmp0_ = self->priv->_name;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	result = _tmp0_;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	return result;
#line 150 "PickleTag.c"
}


static void gherkin_pickles_pickle_tag_set_name (GherkinPicklesPickleTag* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	g_return_if_fail (self != NULL);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	_tmp0_ = value;
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	_g_free0 (self->priv->_name);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	self->priv->_name = _tmp1_;
#line 167 "PickleTag.c"
}


static void gherkin_pickles_pickle_tag_class_init (GherkinPicklesPickleTagClass * klass) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	gherkin_pickles_pickle_tag_parent_class = g_type_class_peek_parent (klass);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	g_type_class_add_private (klass, sizeof (GherkinPicklesPickleTagPrivate));
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_gherkin_pickles_pickle_tag_get_property;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_gherkin_pickles_pickle_tag_set_property;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	G_OBJECT_CLASS (klass)->finalize = gherkin_pickles_pickle_tag_finalize;
#line 182 "PickleTag.c"
}


static void gherkin_pickles_pickle_tag_instance_init (GherkinPicklesPickleTag * self) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	self->priv = GHERKIN_PICKLES_PICKLE_TAG_GET_PRIVATE (self);
#line 189 "PickleTag.c"
}


static void gherkin_pickles_pickle_tag_finalize (GObject* obj) {
	GherkinPicklesPickleTag * self;
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GHERKIN_PICKLES_TYPE_PICKLE_TAG, GherkinPicklesPickleTag);
#line 4 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	_g_object_unref0 (self->priv->_location);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	_g_free0 (self->priv->_name);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	G_OBJECT_CLASS (gherkin_pickles_pickle_tag_parent_class)->finalize (obj);
#line 203 "PickleTag.c"
}


GType gherkin_pickles_pickle_tag_get_type (void) {
	static volatile gsize gherkin_pickles_pickle_tag_type_id__volatile = 0;
	if (g_once_init_enter (&gherkin_pickles_pickle_tag_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GherkinPicklesPickleTagClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gherkin_pickles_pickle_tag_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GherkinPicklesPickleTag), 0, (GInstanceInitFunc) gherkin_pickles_pickle_tag_instance_init, NULL };
		GType gherkin_pickles_pickle_tag_type_id;
		gherkin_pickles_pickle_tag_type_id = g_type_register_static (G_TYPE_OBJECT, "GherkinPicklesPickleTag", &g_define_type_info, 0);
		g_once_init_leave (&gherkin_pickles_pickle_tag_type_id__volatile, gherkin_pickles_pickle_tag_type_id);
	}
	return gherkin_pickles_pickle_tag_type_id__volatile;
}


static void _vala_gherkin_pickles_pickle_tag_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GherkinPicklesPickleTag * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GHERKIN_PICKLES_TYPE_PICKLE_TAG, GherkinPicklesPickleTag);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	switch (property_id) {
#line 224 "PickleTag.c"
		default:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
		break;
#line 230 "PickleTag.c"
	}
}


static void _vala_gherkin_pickles_pickle_tag_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GherkinPicklesPickleTag * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GHERKIN_PICKLES_TYPE_PICKLE_TAG, GherkinPicklesPickleTag);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
	switch (property_id) {
#line 240 "PickleTag.c"
		default:
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/gherkin/pickles/PickleTag.vala"
		break;
#line 246 "PickleTag.c"
	}
}



