/* AstBuilderTest.c generated by valac 0.30.0, the Vala compiler
 * generated from AstBuilderTest.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <libgherkin3.h>
#include <gio/gio.h>
#include <json-glib/json-glib.h>


#define GHERKIN_TYPE_TEST_CASE (gherkin_test_case_get_type ())
#define GHERKIN_TEST_CASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_TYPE_TEST_CASE, GherkinTestCase))
#define GHERKIN_TEST_CASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_TYPE_TEST_CASE, GherkinTestCaseClass))
#define GHERKIN_IS_TEST_CASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_TYPE_TEST_CASE))
#define GHERKIN_IS_TEST_CASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_TYPE_TEST_CASE))
#define GHERKIN_TEST_CASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_TYPE_TEST_CASE, GherkinTestCaseClass))

typedef struct _GherkinTestCase GherkinTestCase;
typedef struct _GherkinTestCaseClass GherkinTestCaseClass;
typedef struct _GherkinTestCasePrivate GherkinTestCasePrivate;

#define GHERKIN_TYPE_AST_BUILDER_TEST (gherkin_ast_builder_test_get_type ())
#define GHERKIN_AST_BUILDER_TEST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_TYPE_AST_BUILDER_TEST, GherkinAstBuilderTest))
#define GHERKIN_AST_BUILDER_TEST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_TYPE_AST_BUILDER_TEST, GherkinAstBuilderTestClass))
#define GHERKIN_IS_AST_BUILDER_TEST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_TYPE_AST_BUILDER_TEST))
#define GHERKIN_IS_AST_BUILDER_TEST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_TYPE_AST_BUILDER_TEST))
#define GHERKIN_AST_BUILDER_TEST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_TYPE_AST_BUILDER_TEST, GherkinAstBuilderTestClass))

typedef struct _GherkinAstBuilderTest GherkinAstBuilderTest;
typedef struct _GherkinAstBuilderTestClass GherkinAstBuilderTestClass;
typedef struct _GherkinAstBuilderTestPrivate GherkinAstBuilderTestPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _gherkin_parser_unref0(var) ((var == NULL) ? NULL : (var = (gherkin_parser_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define __vala_JsonNode_free0(var) ((var == NULL) ? NULL : (var = (_vala_JsonNode_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _GherkinTestCase {
	GObject parent_instance;
	GherkinTestCasePrivate * priv;
};

struct _GherkinTestCaseClass {
	GObjectClass parent_class;
	void (*set_up) (GherkinTestCase* self);
	void (*tear_down) (GherkinTestCase* self);
};

struct _GherkinAstBuilderTest {
	GherkinTestCase parent_instance;
	GherkinAstBuilderTestPrivate * priv;
};

struct _GherkinAstBuilderTestClass {
	GherkinTestCaseClass parent_class;
};

typedef void (*GherkinTestCaseTestMethod) (void* user_data);

static gpointer gherkin_ast_builder_test_parent_class = NULL;

GType gherkin_test_case_get_type (void) G_GNUC_CONST;
GType gherkin_ast_builder_test_get_type (void) G_GNUC_CONST;
enum  {
	GHERKIN_AST_BUILDER_TEST_DUMMY_PROPERTY
};
GherkinAstBuilderTest* gherkin_ast_builder_test_new (void);
GherkinAstBuilderTest* gherkin_ast_builder_test_construct (GType object_type);
GherkinTestCase* gherkin_test_case_construct (GType object_type, const gchar* name);
void gherkin_test_case_add_test (GherkinTestCase* self, const gchar* name, GherkinTestCaseTestMethod test, void* test_target, GDestroyNotify test_target_destroy_notify);
void gherkin_ast_builder_test_is_reusable (GherkinAstBuilderTest* self);
static void _gherkin_ast_builder_test_is_reusable_gherkin_test_case_test_method (gpointer self);
void gherkin_ast_builder_test_build_ast (GherkinAstBuilderTest* self);
static void _gherkin_ast_builder_test_build_ast_gherkin_test_case_test_method (gpointer self);
static void _vala_JsonNode_free (JsonNode* self);


static void _gherkin_ast_builder_test_is_reusable_gherkin_test_case_test_method (gpointer self) {
#line 10 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	gherkin_ast_builder_test_is_reusable ((GherkinAstBuilderTest*) self);
#line 89 "AstBuilderTest.c"
}


static void _gherkin_ast_builder_test_build_ast_gherkin_test_case_test_method (gpointer self) {
#line 11 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	gherkin_ast_builder_test_build_ast ((GherkinAstBuilderTest*) self);
#line 96 "AstBuilderTest.c"
}


GherkinAstBuilderTest* gherkin_ast_builder_test_construct (GType object_type) {
	GherkinAstBuilderTest * self = NULL;
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	self = (GherkinAstBuilderTest*) gherkin_test_case_construct (object_type, "AstBuilderTest");
#line 10 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	gherkin_test_case_add_test ((GherkinTestCase*) self, "is_reusable", _gherkin_ast_builder_test_is_reusable_gherkin_test_case_test_method, g_object_ref (self), g_object_unref);
#line 11 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	gherkin_test_case_add_test ((GherkinTestCase*) self, "build_ast", _gherkin_ast_builder_test_build_ast_gherkin_test_case_test_method, g_object_ref (self), g_object_unref);
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	return self;
#line 110 "AstBuilderTest.c"
}


GherkinAstBuilderTest* gherkin_ast_builder_test_new (void) {
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	return gherkin_ast_builder_test_construct (GHERKIN_TYPE_AST_BUILDER_TEST);
#line 117 "AstBuilderTest.c"
}


void gherkin_ast_builder_test_is_reusable (GherkinAstBuilderTest* self) {
	GherkinParser* parser = NULL;
	GherkinAstBuilder* _tmp0_ = NULL;
	GherkinAstBuilder* _tmp1_ = NULL;
	GherkinParser* _tmp2_ = NULL;
	GherkinParser* _tmp3_ = NULL;
	GherkinTokenMatcher* matcher = NULL;
	GherkinTokenMatcher* _tmp4_ = NULL;
	GherkinAstFeature* f1 = NULL;
	GherkinParser* _tmp5_ = NULL;
	GherkinTokenMatcher* _tmp6_ = NULL;
	gpointer _tmp7_ = NULL;
	GherkinAstFeature* f2 = NULL;
	GherkinParser* _tmp8_ = NULL;
	GherkinTokenMatcher* _tmp9_ = NULL;
	gpointer _tmp10_ = NULL;
	GherkinAstFeature* _tmp11_ = NULL;
	const gchar* _tmp12_ = NULL;
	const gchar* _tmp13_ = NULL;
	GherkinAstFeature* _tmp14_ = NULL;
	const gchar* _tmp15_ = NULL;
	const gchar* _tmp16_ = NULL;
	GError * _inner_error_ = NULL;
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	g_return_if_fail (self != NULL);
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp0_ = gherkin_ast_builder_new ();
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp1_ = _tmp0_;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp2_ = gherkin_parser_new (GHERKIN_AST_TYPE_FEATURE, (GBoxedCopyFunc) g_object_ref, g_object_unref, (GherkinBuilder*) _tmp1_);
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp3_ = _tmp2_;
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_g_object_unref0 (_tmp1_);
#line 15 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	parser = _tmp3_;
#line 16 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp4_ = gherkin_token_matcher_new ("en");
#line 16 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	matcher = _tmp4_;
#line 18 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp5_ = parser;
#line 18 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp6_ = matcher;
#line 18 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp7_ = gherkin_parser_parse_string (_tmp5_, "Feature: 1", (GherkinITokenMatcher*) _tmp6_, &_inner_error_);
#line 18 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	f1 = (GherkinAstFeature*) _tmp7_;
#line 18 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 18 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_g_object_unref0 (matcher);
#line 18 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_gherkin_parser_unref0 (parser);
#line 18 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 18 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		g_clear_error (&_inner_error_);
#line 18 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		return;
#line 182 "AstBuilderTest.c"
	}
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp8_ = parser;
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp9_ = matcher;
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp10_ = gherkin_parser_parse_string (_tmp8_, "Feature: 2", (GherkinITokenMatcher*) _tmp9_, &_inner_error_);
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	f2 = (GherkinAstFeature*) _tmp10_;
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_g_object_unref0 (f1);
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_g_object_unref0 (matcher);
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_gherkin_parser_unref0 (parser);
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		g_clear_error (&_inner_error_);
#line 19 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		return;
#line 206 "AstBuilderTest.c"
	}
#line 21 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp11_ = f1;
#line 21 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp12_ = gherkin_ast_feature_get_name (_tmp11_);
#line 21 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp13_ = _tmp12_;
#line 21 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_vala_assert (g_strcmp0 ("1", _tmp13_) == 0, "\"1\" == f1.name");
#line 22 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp14_ = f2;
#line 22 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp15_ = gherkin_ast_feature_get_name (_tmp14_);
#line 22 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp16_ = _tmp15_;
#line 22 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_vala_assert (g_strcmp0 ("2", _tmp16_) == 0, "\"2\" == f2.name");
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_g_object_unref0 (f2);
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_g_object_unref0 (f1);
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_g_object_unref0 (matcher);
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_gherkin_parser_unref0 (parser);
#line 232 "AstBuilderTest.c"
}


static void _vala_JsonNode_free (JsonNode* self) {
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	g_boxed_free (json_node_get_type (), self);
#line 239 "AstBuilderTest.c"
}


void gherkin_ast_builder_test_build_ast (GherkinAstBuilderTest* self) {
	GherkinParser* parser = NULL;
	GherkinAstBuilder* _tmp0_ = NULL;
	GherkinAstBuilder* _tmp1_ = NULL;
	GherkinParser* _tmp2_ = NULL;
	GherkinParser* _tmp3_ = NULL;
	GherkinTokenMatcher* matcher = NULL;
	GherkinTokenMatcher* _tmp4_ = NULL;
	GTimeVal time = {0};
	glong startTime = 0L;
	GTimeVal _tmp5_ = {0};
	glong _tmp6_ = 0L;
	GFile* file = NULL;
	GFile* _tmp7_ = NULL;
	glong endTime = 0L;
	GTimeVal _tmp27_ = {0};
	glong _tmp28_ = 0L;
	const gchar* _tmp29_ = NULL;
	GError * _inner_error_ = NULL;
#line 25 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	g_return_if_fail (self != NULL);
#line 26 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp0_ = gherkin_ast_builder_new ();
#line 26 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp1_ = _tmp0_;
#line 26 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp2_ = gherkin_parser_new (GHERKIN_AST_TYPE_FEATURE, (GBoxedCopyFunc) g_object_ref, g_object_unref, (GherkinBuilder*) _tmp1_);
#line 26 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp3_ = _tmp2_;
#line 26 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_g_object_unref0 (_tmp1_);
#line 26 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	parser = _tmp3_;
#line 27 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp4_ = gherkin_token_matcher_new ("en");
#line 27 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	matcher = _tmp4_;
#line 29 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	g_get_current_time (&time);
#line 30 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	g_get_current_time (&time);
#line 31 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp5_ = time;
#line 31 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp6_ = _tmp5_.tv_usec;
#line 31 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	startTime = _tmp6_;
#line 32 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp7_ = g_file_new_for_path ("/home/bizarro/Documents/projects/gherkin-vala/tests/testdata/good/seve" \
"ral_examples.feature");
#line 32 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	file = _tmp7_;
#line 294 "AstBuilderTest.c"
	{
		GFileInputStream* input = NULL;
		GFile* _tmp8_ = NULL;
		GFileInputStream* _tmp9_ = NULL;
		GherkinAstFeature* feature = NULL;
		GherkinParser* _tmp10_ = NULL;
		GFileInputStream* _tmp11_ = NULL;
		GherkinTokenMatcher* _tmp12_ = NULL;
		gpointer _tmp13_ = NULL;
		JsonNode* root = NULL;
		GherkinAstFeature* _tmp14_ = NULL;
		JsonNode* _tmp15_ = NULL;
		JsonGenerator* generator = NULL;
		JsonGenerator* _tmp16_ = NULL;
		JsonGenerator* _tmp17_ = NULL;
		JsonGenerator* _tmp18_ = NULL;
		JsonNode* _tmp19_ = NULL;
		JsonGenerator* _tmp20_ = NULL;
		gchar* _tmp21_ = NULL;
		gchar* _tmp22_ = NULL;
#line 34 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_tmp8_ = file;
#line 34 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_tmp9_ = g_file_read (_tmp8_, NULL, &_inner_error_);
#line 34 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		input = _tmp9_;
#line 34 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 323 "AstBuilderTest.c"
			goto __catch0_g_error;
		}
#line 35 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_tmp10_ = parser;
#line 35 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_tmp11_ = input;
#line 35 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_tmp12_ = matcher;
#line 35 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_tmp13_ = gherkin_parser_parse_reader (_tmp10_, (GInputStream*) _tmp11_, (GherkinITokenMatcher*) _tmp12_, &_inner_error_);
#line 35 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		feature = (GherkinAstFeature*) _tmp13_;
#line 35 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 35 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
			_g_object_unref0 (input);
#line 340 "AstBuilderTest.c"
			goto __catch0_g_error;
		}
#line 37 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_tmp14_ = feature;
#line 37 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_tmp15_ = json_gobject_serialize ((GObject*) _tmp14_);
#line 37 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		root = _tmp15_;
#line 38 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_tmp16_ = json_generator_new ();
#line 38 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		generator = _tmp16_;
#line 39 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_tmp17_ = generator;
#line 39 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		json_generator_set_pretty (_tmp17_, TRUE);
#line 40 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_tmp18_ = generator;
#line 40 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_tmp19_ = root;
#line 40 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		json_generator_set_root (_tmp18_, _tmp19_);
#line 41 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_tmp20_ = generator;
#line 41 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_tmp21_ = json_generator_to_data (_tmp20_, NULL);
#line 41 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_tmp22_ = _tmp21_;
#line 41 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		g_message ("AstBuilderTest.vala:41: %s", _tmp22_);
#line 41 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_g_free0 (_tmp22_);
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_g_object_unref0 (generator);
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		__vala_JsonNode_free0 (root);
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_g_object_unref0 (feature);
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_g_object_unref0 (input);
#line 381 "AstBuilderTest.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp23_ = NULL;
		const gchar* _tmp24_ = NULL;
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		e = _inner_error_;
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_inner_error_ = NULL;
#line 43 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_tmp23_ = e;
#line 43 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_tmp24_ = _tmp23_->message;
#line 43 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		g_warning ("AstBuilderTest.vala:43: %s", _tmp24_);
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_g_error_free0 (e);
#line 401 "AstBuilderTest.c"
	}
	goto __finally0;
	__catch0_gherkin_parser_exception:
	{
		GError* e = NULL;
		GError* _tmp25_ = NULL;
		const gchar* _tmp26_ = NULL;
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		e = _inner_error_;
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_inner_error_ = NULL;
#line 45 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_tmp25_ = e;
#line 45 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_tmp26_ = _tmp25_->message;
#line 45 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		g_warning ("AstBuilderTest.vala:45: %s", _tmp26_);
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_g_error_free0 (e);
#line 421 "AstBuilderTest.c"
	}
	__finally0:
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_g_object_unref0 (file);
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_g_object_unref0 (matcher);
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_gherkin_parser_unref0 (parser);
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		g_clear_error (&_inner_error_);
#line 33 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		return;
#line 438 "AstBuilderTest.c"
	}
#line 47 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	g_get_current_time (&time);
#line 48 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp27_ = time;
#line 48 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp28_ = _tmp27_.tv_usec;
#line 48 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	endTime = _tmp28_;
#line 49 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_tmp29_ = g_getenv ("GHERKIN_PERF");
#line 49 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	if (_tmp29_ != NULL) {
#line 452 "AstBuilderTest.c"
		glong _tmp30_ = 0L;
		glong _tmp31_ = 0L;
		gchar* _tmp32_ = NULL;
		gchar* _tmp33_ = NULL;
#line 50 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_tmp30_ = endTime;
#line 50 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_tmp31_ = startTime;
#line 50 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_tmp32_ = g_strdup_printf ("%li", _tmp30_ - _tmp31_);
#line 50 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_tmp33_ = _tmp32_;
#line 50 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		g_warning ("AstBuilderTest.vala:50: %s", _tmp33_);
#line 50 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
		_g_free0 (_tmp33_);
#line 469 "AstBuilderTest.c"
	}
#line 25 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_g_object_unref0 (file);
#line 25 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_g_object_unref0 (matcher);
#line 25 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	_gherkin_parser_unref0 (parser);
#line 477 "AstBuilderTest.c"
}


static void gherkin_ast_builder_test_class_init (GherkinAstBuilderTestClass * klass) {
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/AstBuilderTest.vala"
	gherkin_ast_builder_test_parent_class = g_type_class_peek_parent (klass);
#line 484 "AstBuilderTest.c"
}


static void gherkin_ast_builder_test_instance_init (GherkinAstBuilderTest * self) {
}


GType gherkin_ast_builder_test_get_type (void) {
	static volatile gsize gherkin_ast_builder_test_type_id__volatile = 0;
	if (g_once_init_enter (&gherkin_ast_builder_test_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GherkinAstBuilderTestClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gherkin_ast_builder_test_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GherkinAstBuilderTest), 0, (GInstanceInitFunc) gherkin_ast_builder_test_instance_init, NULL };
		GType gherkin_ast_builder_test_type_id;
		gherkin_ast_builder_test_type_id = g_type_register_static (GHERKIN_TYPE_TEST_CASE, "GherkinAstBuilderTest", &g_define_type_info, 0);
		g_once_init_leave (&gherkin_ast_builder_test_type_id__volatile, gherkin_ast_builder_test_type_id);
	}
	return gherkin_ast_builder_test_type_id__volatile;
}



