/* GherkinLineTest.c generated by valac 0.30.0, the Vala compiler
 * generated from GherkinLineTest.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <libgherkin3.h>
#include <gee.h>


#define GHERKIN_TYPE_TEST_CASE (gherkin_test_case_get_type ())
#define GHERKIN_TEST_CASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_TYPE_TEST_CASE, GherkinTestCase))
#define GHERKIN_TEST_CASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_TYPE_TEST_CASE, GherkinTestCaseClass))
#define GHERKIN_IS_TEST_CASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_TYPE_TEST_CASE))
#define GHERKIN_IS_TEST_CASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_TYPE_TEST_CASE))
#define GHERKIN_TEST_CASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_TYPE_TEST_CASE, GherkinTestCaseClass))

typedef struct _GherkinTestCase GherkinTestCase;
typedef struct _GherkinTestCaseClass GherkinTestCaseClass;
typedef struct _GherkinTestCasePrivate GherkinTestCasePrivate;

#define GHERKIN_TYPE_GHERKIN_LINE_TEST (gherkin_gherkin_line_test_get_type ())
#define GHERKIN_GHERKIN_LINE_TEST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_TYPE_GHERKIN_LINE_TEST, GherkinGherkinLineTest))
#define GHERKIN_GHERKIN_LINE_TEST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_TYPE_GHERKIN_LINE_TEST, GherkinGherkinLineTestClass))
#define GHERKIN_IS_GHERKIN_LINE_TEST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_TYPE_GHERKIN_LINE_TEST))
#define GHERKIN_IS_GHERKIN_LINE_TEST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_TYPE_GHERKIN_LINE_TEST))
#define GHERKIN_GHERKIN_LINE_TEST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_TYPE_GHERKIN_LINE_TEST, GherkinGherkinLineTestClass))

typedef struct _GherkinGherkinLineTest GherkinGherkinLineTest;
typedef struct _GherkinGherkinLineTestClass GherkinGherkinLineTestClass;
typedef struct _GherkinGherkinLineTestPrivate GherkinGherkinLineTestPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _GherkinTestCase {
	GObject parent_instance;
	GherkinTestCasePrivate * priv;
};

struct _GherkinTestCaseClass {
	GObjectClass parent_class;
	void (*set_up) (GherkinTestCase* self);
	void (*tear_down) (GherkinTestCase* self);
};

struct _GherkinGherkinLineTest {
	GherkinTestCase parent_instance;
	GherkinGherkinLineTestPrivate * priv;
};

struct _GherkinGherkinLineTestClass {
	GherkinTestCaseClass parent_class;
};

typedef void (*GherkinTestCaseTestMethod) (void* user_data);

static gpointer gherkin_gherkin_line_test_parent_class = NULL;

GType gherkin_test_case_get_type (void) G_GNUC_CONST;
GType gherkin_gherkin_line_test_get_type (void) G_GNUC_CONST;
enum  {
	GHERKIN_GHERKIN_LINE_TEST_DUMMY_PROPERTY
};
GherkinGherkinLineTest* gherkin_gherkin_line_test_new (void);
GherkinGherkinLineTest* gherkin_gherkin_line_test_construct (GType object_type);
GherkinTestCase* gherkin_test_case_construct (GType object_type, const gchar* name);
void gherkin_test_case_add_test (GherkinTestCase* self, const gchar* name, GherkinTestCaseTestMethod test, void* test_target, GDestroyNotify test_target_destroy_notify);
void gherkin_gherkin_line_test_finds_tags (GherkinGherkinLineTest* self);
static void _gherkin_gherkin_line_test_finds_tags_gherkin_test_case_test_method (gpointer self);


static void _gherkin_gherkin_line_test_finds_tags_gherkin_test_case_test_method (gpointer self) {
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	gherkin_gherkin_line_test_finds_tags ((GherkinGherkinLineTest*) self);
#line 81 "GherkinLineTest.c"
}


GherkinGherkinLineTest* gherkin_gherkin_line_test_construct (GType object_type) {
	GherkinGherkinLineTest * self = NULL;
#line 8 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	self = (GherkinGherkinLineTest*) gherkin_test_case_construct (object_type, "GherkinLineTest");
#line 9 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	gherkin_test_case_add_test ((GherkinTestCase*) self, "finds_tags", _gherkin_gherkin_line_test_finds_tags_gherkin_test_case_test_method, g_object_ref (self), g_object_unref);
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	return self;
#line 93 "GherkinLineTest.c"
}


GherkinGherkinLineTest* gherkin_gherkin_line_test_new (void) {
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	return gherkin_gherkin_line_test_construct (GHERKIN_TYPE_GHERKIN_LINE_TEST);
#line 100 "GherkinLineTest.c"
}


void gherkin_gherkin_line_test_finds_tags (GherkinGherkinLineTest* self) {
	GherkinGherkinLine* gherkinLine = NULL;
	GherkinGherkinLine* _tmp0_ = NULL;
	GeeArrayList* gherkinLineSpans = NULL;
	GeeArrayList* _tmp1_ = NULL;
	gpointer _tmp2_ = NULL;
	GherkinGherkinLineSpan* _tmp3_ = NULL;
	GherkinGherkinLineSpan* _tmp4_ = NULL;
	GherkinGherkinLineSpan* _tmp5_ = NULL;
	gboolean _tmp6_ = FALSE;
	gpointer _tmp7_ = NULL;
	GherkinGherkinLineSpan* _tmp8_ = NULL;
	GherkinGherkinLineSpan* _tmp9_ = NULL;
	GherkinGherkinLineSpan* _tmp10_ = NULL;
	gboolean _tmp11_ = FALSE;
	gpointer _tmp12_ = NULL;
	GherkinGherkinLineSpan* _tmp13_ = NULL;
	GherkinGherkinLineSpan* _tmp14_ = NULL;
	GherkinGherkinLineSpan* _tmp15_ = NULL;
	gboolean _tmp16_ = FALSE;
#line 12 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	g_return_if_fail (self != NULL);
#line 13 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_tmp0_ = gherkin_gherkin_line_new ("    @this @is  @atag  ");
#line 13 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	gherkinLine = _tmp0_;
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_tmp1_ = gherkin_igherkin_line_get_tags ((GherkinIGherkinLine*) gherkinLine);
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	gherkinLineSpans = _tmp1_;
#line 16 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_tmp2_ = gee_abstract_list_get ((GeeAbstractList*) gherkinLineSpans, 0);
#line 16 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_tmp3_ = (GherkinGherkinLineSpan*) _tmp2_;
#line 16 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_tmp4_ = gherkin_gherkin_line_span_new (5, "@this");
#line 16 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_tmp5_ = _tmp4_;
#line 16 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_tmp6_ = gherkin_gherkin_line_span_equals (_tmp3_, _tmp5_);
#line 16 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_vala_assert (_tmp6_, "gherkinLineSpans[0].equals(new GherkinLineSpan(5, \"@this\"))");
#line 16 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_g_object_unref0 (_tmp5_);
#line 16 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_g_object_unref0 (_tmp3_);
#line 17 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_tmp7_ = gee_abstract_list_get ((GeeAbstractList*) gherkinLineSpans, 1);
#line 17 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_tmp8_ = (GherkinGherkinLineSpan*) _tmp7_;
#line 17 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_tmp9_ = gherkin_gherkin_line_span_new (11, "@is");
#line 17 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_tmp10_ = _tmp9_;
#line 17 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_tmp11_ = gherkin_gherkin_line_span_equals (_tmp8_, _tmp10_);
#line 17 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_vala_assert (_tmp11_, "gherkinLineSpans[1].equals(new GherkinLineSpan(11, \"@is\"))");
#line 17 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_g_object_unref0 (_tmp10_);
#line 17 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_g_object_unref0 (_tmp8_);
#line 18 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_tmp12_ = gee_abstract_list_get ((GeeAbstractList*) gherkinLineSpans, 2);
#line 18 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_tmp13_ = (GherkinGherkinLineSpan*) _tmp12_;
#line 18 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_tmp14_ = gherkin_gherkin_line_span_new (16, "@atag");
#line 18 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_tmp15_ = _tmp14_;
#line 18 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_tmp16_ = gherkin_gherkin_line_span_equals (_tmp13_, _tmp15_);
#line 18 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_vala_assert (_tmp16_, "gherkinLineSpans[2].equals(new GherkinLineSpan(16, \"@atag\"))");
#line 18 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_g_object_unref0 (_tmp15_);
#line 18 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_g_object_unref0 (_tmp13_);
#line 12 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_g_object_unref0 (gherkinLineSpans);
#line 12 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	_g_object_unref0 (gherkinLine);
#line 186 "GherkinLineTest.c"
}


static void gherkin_gherkin_line_test_class_init (GherkinGherkinLineTestClass * klass) {
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinLineTest.vala"
	gherkin_gherkin_line_test_parent_class = g_type_class_peek_parent (klass);
#line 193 "GherkinLineTest.c"
}


static void gherkin_gherkin_line_test_instance_init (GherkinGherkinLineTest * self) {
}


GType gherkin_gherkin_line_test_get_type (void) {
	static volatile gsize gherkin_gherkin_line_test_type_id__volatile = 0;
	if (g_once_init_enter (&gherkin_gherkin_line_test_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GherkinGherkinLineTestClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gherkin_gherkin_line_test_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GherkinGherkinLineTest), 0, (GInstanceInitFunc) gherkin_gherkin_line_test_instance_init, NULL };
		GType gherkin_gherkin_line_test_type_id;
		gherkin_gherkin_line_test_type_id = g_type_register_static (GHERKIN_TYPE_TEST_CASE, "GherkinGherkinLineTest", &g_define_type_info, 0);
		g_once_init_leave (&gherkin_gherkin_line_test_type_id__volatile, gherkin_gherkin_line_test_type_id);
	}
	return gherkin_gherkin_line_test_type_id__volatile;
}



