/* GherkinDialectProviderTest.c generated by valac 0.30.0, the Vala compiler
 * generated from GherkinDialectProviderTest.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <libgherkin3.h>
#include <gee.h>


#define GHERKIN_TYPE_TEST_CASE (gherkin_test_case_get_type ())
#define GHERKIN_TEST_CASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_TYPE_TEST_CASE, GherkinTestCase))
#define GHERKIN_TEST_CASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_TYPE_TEST_CASE, GherkinTestCaseClass))
#define GHERKIN_IS_TEST_CASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_TYPE_TEST_CASE))
#define GHERKIN_IS_TEST_CASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_TYPE_TEST_CASE))
#define GHERKIN_TEST_CASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_TYPE_TEST_CASE, GherkinTestCaseClass))

typedef struct _GherkinTestCase GherkinTestCase;
typedef struct _GherkinTestCaseClass GherkinTestCaseClass;
typedef struct _GherkinTestCasePrivate GherkinTestCasePrivate;

#define GHERKIN_TYPE_GHERKIN_DIALECT_PROVIDER_TEST (gherkin_gherkin_dialect_provider_test_get_type ())
#define GHERKIN_GHERKIN_DIALECT_PROVIDER_TEST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GHERKIN_TYPE_GHERKIN_DIALECT_PROVIDER_TEST, GherkinGherkinDialectProviderTest))
#define GHERKIN_GHERKIN_DIALECT_PROVIDER_TEST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GHERKIN_TYPE_GHERKIN_DIALECT_PROVIDER_TEST, GherkinGherkinDialectProviderTestClass))
#define GHERKIN_IS_GHERKIN_DIALECT_PROVIDER_TEST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GHERKIN_TYPE_GHERKIN_DIALECT_PROVIDER_TEST))
#define GHERKIN_IS_GHERKIN_DIALECT_PROVIDER_TEST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GHERKIN_TYPE_GHERKIN_DIALECT_PROVIDER_TEST))
#define GHERKIN_GHERKIN_DIALECT_PROVIDER_TEST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GHERKIN_TYPE_GHERKIN_DIALECT_PROVIDER_TEST, GherkinGherkinDialectProviderTestClass))

typedef struct _GherkinGherkinDialectProviderTest GherkinGherkinDialectProviderTest;
typedef struct _GherkinGherkinDialectProviderTestClass GherkinGherkinDialectProviderTestClass;
typedef struct _GherkinGherkinDialectProviderTestPrivate GherkinGherkinDialectProviderTestPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _GherkinTestCase {
	GObject parent_instance;
	GherkinTestCasePrivate * priv;
};

struct _GherkinTestCaseClass {
	GObjectClass parent_class;
	void (*set_up) (GherkinTestCase* self);
	void (*tear_down) (GherkinTestCase* self);
};

struct _GherkinGherkinDialectProviderTest {
	GherkinTestCase parent_instance;
	GherkinGherkinDialectProviderTestPrivate * priv;
};

struct _GherkinGherkinDialectProviderTestClass {
	GherkinTestCaseClass parent_class;
};

typedef void (*GherkinTestCaseTestMethod) (void* user_data);

static gpointer gherkin_gherkin_dialect_provider_test_parent_class = NULL;

GType gherkin_test_case_get_type (void) G_GNUC_CONST;
GType gherkin_gherkin_dialect_provider_test_get_type (void) G_GNUC_CONST;
enum  {
	GHERKIN_GHERKIN_DIALECT_PROVIDER_TEST_DUMMY_PROPERTY
};
GherkinGherkinDialectProviderTest* gherkin_gherkin_dialect_provider_test_new (void);
GherkinGherkinDialectProviderTest* gherkin_gherkin_dialect_provider_test_construct (GType object_type);
GherkinTestCase* gherkin_test_case_construct (GType object_type, const gchar* name);
void gherkin_test_case_add_test (GherkinTestCase* self, const gchar* name, GherkinTestCaseTestMethod test, void* test_target, GDestroyNotify test_target_destroy_notify);
void gherkin_gherkin_dialect_provider_test_providesEmojiDialect (GherkinGherkinDialectProviderTest* self);
static void _gherkin_gherkin_dialect_provider_test_providesEmojiDialect_gherkin_test_case_test_method (gpointer self);


static void _gherkin_gherkin_dialect_provider_test_providesEmojiDialect_gherkin_test_case_test_method (gpointer self) {
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinDialectProviderTest.vala"
	gherkin_gherkin_dialect_provider_test_providesEmojiDialect ((GherkinGherkinDialectProviderTest*) self);
#line 82 "GherkinDialectProviderTest.c"
}


GherkinGherkinDialectProviderTest* gherkin_gherkin_dialect_provider_test_construct (GType object_type) {
	GherkinGherkinDialectProviderTest * self = NULL;
#line 6 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinDialectProviderTest.vala"
	self = (GherkinGherkinDialectProviderTest*) gherkin_test_case_construct (object_type, "GherkinDialectProviderTest");
#line 7 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinDialectProviderTest.vala"
	gherkin_test_case_add_test ((GherkinTestCase*) self, "providesEmojiDialect", _gherkin_gherkin_dialect_provider_test_providesEmojiDialect_gherkin_test_case_test_method, g_object_ref (self), g_object_unref);
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinDialectProviderTest.vala"
	return self;
#line 94 "GherkinDialectProviderTest.c"
}


GherkinGherkinDialectProviderTest* gherkin_gherkin_dialect_provider_test_new (void) {
#line 5 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinDialectProviderTest.vala"
	return gherkin_gherkin_dialect_provider_test_construct (GHERKIN_TYPE_GHERKIN_DIALECT_PROVIDER_TEST);
#line 101 "GherkinDialectProviderTest.c"
}


void gherkin_gherkin_dialect_provider_test_providesEmojiDialect (GherkinGherkinDialectProviderTest* self) {
	GherkinGherkinDialect* em = NULL;
	GherkinGherkinDialectProvider* _tmp0_ = NULL;
	GherkinGherkinDialectProvider* _tmp1_ = NULL;
	GherkinGherkinDialect* _tmp2_ = NULL;
	GherkinGherkinDialect* _tmp3_ = NULL;
	GeeArrayList* _tmp4_ = NULL;
	GeeArrayList* _tmp5_ = NULL;
	gpointer _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gint _tmp8_ = 0;
	gint _tmp9_ = 0;
#line 10 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinDialectProviderTest.vala"
	g_return_if_fail (self != NULL);
#line 11 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinDialectProviderTest.vala"
	_tmp0_ = gherkin_gherkin_dialect_provider_new ("en");
#line 11 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinDialectProviderTest.vala"
	_tmp1_ = _tmp0_;
#line 11 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinDialectProviderTest.vala"
	_tmp2_ = gherkin_igherkin_dialect_provider_get_dialect ((GherkinIGherkinDialectProvider*) _tmp1_, "em", NULL);
#line 11 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinDialectProviderTest.vala"
	_tmp3_ = _tmp2_;
#line 11 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinDialectProviderTest.vala"
	_g_object_unref0 (_tmp1_);
#line 11 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinDialectProviderTest.vala"
	em = _tmp3_;
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinDialectProviderTest.vala"
	_tmp4_ = gherkin_gherkin_dialect_get_scenario_keywords (em);
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinDialectProviderTest.vala"
	_tmp5_ = _tmp4_;
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinDialectProviderTest.vala"
	_tmp6_ = gee_abstract_list_get ((GeeAbstractList*) _tmp5_, 0);
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinDialectProviderTest.vala"
	_tmp7_ = (gchar*) _tmp6_;
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinDialectProviderTest.vala"
	_tmp8_ = strlen (_tmp7_);
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinDialectProviderTest.vala"
	_tmp9_ = _tmp8_;
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinDialectProviderTest.vala"
	_vala_assert (4 == _tmp9_, "4 == em.get_scenario_keywords().get(0).length");
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinDialectProviderTest.vala"
	_g_free0 (_tmp7_);
#line 14 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinDialectProviderTest.vala"
	_g_object_unref0 (_tmp5_);
#line 10 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinDialectProviderTest.vala"
	_g_object_unref0 (em);
#line 151 "GherkinDialectProviderTest.c"
}


static void gherkin_gherkin_dialect_provider_test_class_init (GherkinGherkinDialectProviderTestClass * klass) {
#line 3 "/home/bizarro/Documents/projects/gherkin-vala/tests/gherkin/GherkinDialectProviderTest.vala"
	gherkin_gherkin_dialect_provider_test_parent_class = g_type_class_peek_parent (klass);
#line 158 "GherkinDialectProviderTest.c"
}


static void gherkin_gherkin_dialect_provider_test_instance_init (GherkinGherkinDialectProviderTest * self) {
}


GType gherkin_gherkin_dialect_provider_test_get_type (void) {
	static volatile gsize gherkin_gherkin_dialect_provider_test_type_id__volatile = 0;
	if (g_once_init_enter (&gherkin_gherkin_dialect_provider_test_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GherkinGherkinDialectProviderTestClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gherkin_gherkin_dialect_provider_test_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GherkinGherkinDialectProviderTest), 0, (GInstanceInitFunc) gherkin_gherkin_dialect_provider_test_instance_init, NULL };
		GType gherkin_gherkin_dialect_provider_test_type_id;
		gherkin_gherkin_dialect_provider_test_type_id = g_type_register_static (GHERKIN_TYPE_TEST_CASE, "GherkinGherkinDialectProviderTest", &g_define_type_info, 0);
		g_once_init_leave (&gherkin_gherkin_dialect_provider_test_type_id__volatile, gherkin_gherkin_dialect_provider_test_type_id);
	}
	return gherkin_gherkin_dialect_provider_test_type_id__volatile;
}



